// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package atlassianserver

import (
	"context"
	"database/sql"
	"github.com/icholy/xagent/internal/model"
	"sync"
)

// Ensure, that StoreMock does implement Store.
// If this is not the case, regenerate this file with moq.
var _ Store = &StoreMock{}

// StoreMock is a mock implementation of Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked Store
//		mockedStore := &StoreMock{
//			GetOrgAtlassianWebhookSecretFunc: func(ctx context.Context, tx *sql.Tx, orgID int64) (string, error) {
//				panic("mock out the GetOrgAtlassianWebhookSecret method")
//			},
//			GetUserByAtlassianAccountIDFunc: func(ctx context.Context, tx *sql.Tx, atlassianAccountID string) (*model.User, error) {
//				panic("mock out the GetUserByAtlassianAccountID method")
//			},
//		}
//
//		// use mockedStore in code that requires Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// GetOrgAtlassianWebhookSecretFunc mocks the GetOrgAtlassianWebhookSecret method.
	GetOrgAtlassianWebhookSecretFunc func(ctx context.Context, tx *sql.Tx, orgID int64) (string, error)

	// GetUserByAtlassianAccountIDFunc mocks the GetUserByAtlassianAccountID method.
	GetUserByAtlassianAccountIDFunc func(ctx context.Context, tx *sql.Tx, atlassianAccountID string) (*model.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetOrgAtlassianWebhookSecret holds details about calls to the GetOrgAtlassianWebhookSecret method.
		GetOrgAtlassianWebhookSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// OrgID is the orgID argument value.
			OrgID int64
		}
		// GetUserByAtlassianAccountID holds details about calls to the GetUserByAtlassianAccountID method.
		GetUserByAtlassianAccountID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// AtlassianAccountID is the atlassianAccountID argument value.
			AtlassianAccountID string
		}
	}
	lockGetOrgAtlassianWebhookSecret sync.RWMutex
	lockGetUserByAtlassianAccountID  sync.RWMutex
}

// GetOrgAtlassianWebhookSecret calls GetOrgAtlassianWebhookSecretFunc.
func (mock *StoreMock) GetOrgAtlassianWebhookSecret(ctx context.Context, tx *sql.Tx, orgID int64) (string, error) {
	if mock.GetOrgAtlassianWebhookSecretFunc == nil {
		panic("StoreMock.GetOrgAtlassianWebhookSecretFunc: method is nil but Store.GetOrgAtlassianWebhookSecret was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Tx    *sql.Tx
		OrgID int64
	}{
		Ctx:   ctx,
		Tx:    tx,
		OrgID: orgID,
	}
	mock.lockGetOrgAtlassianWebhookSecret.Lock()
	mock.calls.GetOrgAtlassianWebhookSecret = append(mock.calls.GetOrgAtlassianWebhookSecret, callInfo)
	mock.lockGetOrgAtlassianWebhookSecret.Unlock()
	return mock.GetOrgAtlassianWebhookSecretFunc(ctx, tx, orgID)
}

// GetOrgAtlassianWebhookSecretCalls gets all the calls that were made to GetOrgAtlassianWebhookSecret.
// Check the length with:
//
//	len(mockedStore.GetOrgAtlassianWebhookSecretCalls())
func (mock *StoreMock) GetOrgAtlassianWebhookSecretCalls() []struct {
	Ctx   context.Context
	Tx    *sql.Tx
	OrgID int64
} {
	var calls []struct {
		Ctx   context.Context
		Tx    *sql.Tx
		OrgID int64
	}
	mock.lockGetOrgAtlassianWebhookSecret.RLock()
	calls = mock.calls.GetOrgAtlassianWebhookSecret
	mock.lockGetOrgAtlassianWebhookSecret.RUnlock()
	return calls
}

// GetUserByAtlassianAccountID calls GetUserByAtlassianAccountIDFunc.
func (mock *StoreMock) GetUserByAtlassianAccountID(ctx context.Context, tx *sql.Tx, atlassianAccountID string) (*model.User, error) {
	if mock.GetUserByAtlassianAccountIDFunc == nil {
		panic("StoreMock.GetUserByAtlassianAccountIDFunc: method is nil but Store.GetUserByAtlassianAccountID was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		Tx                 *sql.Tx
		AtlassianAccountID string
	}{
		Ctx:                ctx,
		Tx:                 tx,
		AtlassianAccountID: atlassianAccountID,
	}
	mock.lockGetUserByAtlassianAccountID.Lock()
	mock.calls.GetUserByAtlassianAccountID = append(mock.calls.GetUserByAtlassianAccountID, callInfo)
	mock.lockGetUserByAtlassianAccountID.Unlock()
	return mock.GetUserByAtlassianAccountIDFunc(ctx, tx, atlassianAccountID)
}

// GetUserByAtlassianAccountIDCalls gets all the calls that were made to GetUserByAtlassianAccountID.
// Check the length with:
//
//	len(mockedStore.GetUserByAtlassianAccountIDCalls())
func (mock *StoreMock) GetUserByAtlassianAccountIDCalls() []struct {
	Ctx                context.Context
	Tx                 *sql.Tx
	AtlassianAccountID string
} {
	var calls []struct {
		Ctx                context.Context
		Tx                 *sql.Tx
		AtlassianAccountID string
	}
	mock.lockGetUserByAtlassianAccountID.RLock()
	calls = mock.calls.GetUserByAtlassianAccountID
	mock.lockGetUserByAtlassianAccountID.RUnlock()
	return calls
}
