/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces.index'
import { Route as WebhooksIndexRouteImport } from './routes/webhooks.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as WebhooksNewRouteImport } from './routes/webhooks.new'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsIdRouteImport } from './routes/events.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksIndexRoute = WebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksNewRoute = WebhooksNewRouteImport.update({
  id: '/webhooks/new',
  path: '/webhooks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$id': typeof EventsIdRoute
  '/events/new': typeof EventsNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/webhooks/new': typeof WebhooksNewRoute
  '/events': typeof EventsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/webhooks': typeof WebhooksIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$id': typeof EventsIdRoute
  '/events/new': typeof EventsNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/webhooks/new': typeof WebhooksNewRoute
  '/events': typeof EventsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/webhooks': typeof WebhooksIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$id': typeof EventsIdRoute
  '/events/new': typeof EventsNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/webhooks/new': typeof WebhooksNewRoute
  '/events/': typeof EventsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/webhooks/': typeof WebhooksIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$id'
    | '/events/new'
    | '/tasks/$id'
    | '/tasks/new'
    | '/webhooks/new'
    | '/events'
    | '/tasks'
    | '/webhooks'
    | '/workspaces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/$id'
    | '/events/new'
    | '/tasks/$id'
    | '/tasks/new'
    | '/webhooks/new'
    | '/events'
    | '/tasks'
    | '/webhooks'
    | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/events/$id'
    | '/events/new'
    | '/tasks/$id'
    | '/tasks/new'
    | '/webhooks/new'
    | '/events/'
    | '/tasks/'
    | '/webhooks/'
    | '/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsIdRoute: typeof EventsIdRoute
  EventsNewRoute: typeof EventsNewRoute
  TasksIdRoute: typeof TasksIdRoute
  TasksNewRoute: typeof TasksNewRoute
  WebhooksNewRoute: typeof WebhooksNewRoute
  EventsIndexRoute: typeof EventsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  WebhooksIndexRoute: typeof WebhooksIndexRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/': {
      id: '/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/new': {
      id: '/webhooks/new'
      path: '/webhooks/new'
      fullPath: '/webhooks/new'
      preLoaderRoute: typeof WebhooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsIdRoute: EventsIdRoute,
  EventsNewRoute: EventsNewRoute,
  TasksIdRoute: TasksIdRoute,
  TasksNewRoute: TasksNewRoute,
  WebhooksNewRoute: WebhooksNewRoute,
  EventsIndexRoute: EventsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  WebhooksIndexRoute: WebhooksIndexRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
