// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package backend

import (
	"context"
	"github.com/icholy/xagent/internal/runner/workspace"
	"sync"
)

// Ensure, that BackendMock does implement Backend.
// If this is not the case, regenerate this file with moq.
var _ Backend = &BackendMock{}

// BackendMock is a mock implementation of Backend.
//
//	func TestSomethingThatUsesBackend(t *testing.T) {
//
//		// make and configure a mocked Backend
//		mockedBackend := &BackendMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			DestroyFunc: func(ctx context.Context, h Handle) error {
//				panic("mock out the Destroy method")
//			},
//			LaunchFunc: func(ctx context.Context, spec *Spec, reuse *Handle) (Handle, error) {
//				panic("mock out the Launch method")
//			},
//			ProbeFunc: func(ctx context.Context, h Handle) (State, error) {
//				panic("mock out the Probe method")
//			},
//			SignalFunc: func(ctx context.Context, h Handle) (bool, error) {
//				panic("mock out the Signal method")
//			},
//			ValidateWorkspaceFunc: func(ws *workspace.Workspace) error {
//				panic("mock out the ValidateWorkspace method")
//			},
//			WatchFunc: func(ctx context.Context, handle func(HandleExit)) error {
//				panic("mock out the Watch method")
//			},
//		}
//
//		// use mockedBackend in code that requires Backend
//		// and then make assertions.
//
//	}
type BackendMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// DestroyFunc mocks the Destroy method.
	DestroyFunc func(ctx context.Context, h Handle) error

	// LaunchFunc mocks the Launch method.
	LaunchFunc func(ctx context.Context, spec *Spec, reuse *Handle) (Handle, error)

	// ProbeFunc mocks the Probe method.
	ProbeFunc func(ctx context.Context, h Handle) (State, error)

	// SignalFunc mocks the Signal method.
	SignalFunc func(ctx context.Context, h Handle) (bool, error)

	// ValidateWorkspaceFunc mocks the ValidateWorkspace method.
	ValidateWorkspaceFunc func(ws *workspace.Workspace) error

	// WatchFunc mocks the Watch method.
	WatchFunc func(ctx context.Context, handle func(HandleExit)) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Destroy holds details about calls to the Destroy method.
		Destroy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// H is the h argument value.
			H Handle
		}
		// Launch holds details about calls to the Launch method.
		Launch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Spec is the spec argument value.
			Spec *Spec
			// Reuse is the reuse argument value.
			Reuse *Handle
		}
		// Probe holds details about calls to the Probe method.
		Probe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// H is the h argument value.
			H Handle
		}
		// Signal holds details about calls to the Signal method.
		Signal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// H is the h argument value.
			H Handle
		}
		// ValidateWorkspace holds details about calls to the ValidateWorkspace method.
		ValidateWorkspace []struct {
			// Ws is the ws argument value.
			Ws *workspace.Workspace
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Handle is the handle argument value.
			Handle func(HandleExit)
		}
	}
	lockClose             sync.RWMutex
	lockDestroy           sync.RWMutex
	lockLaunch            sync.RWMutex
	lockProbe             sync.RWMutex
	lockSignal            sync.RWMutex
	lockValidateWorkspace sync.RWMutex
	lockWatch             sync.RWMutex
}

// Close calls CloseFunc.
func (mock *BackendMock) Close() error {
	if mock.CloseFunc == nil {
		panic("BackendMock.CloseFunc: method is nil but Backend.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedBackend.CloseCalls())
func (mock *BackendMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Destroy calls DestroyFunc.
func (mock *BackendMock) Destroy(ctx context.Context, h Handle) error {
	if mock.DestroyFunc == nil {
		panic("BackendMock.DestroyFunc: method is nil but Backend.Destroy was just called")
	}
	callInfo := struct {
		Ctx context.Context
		H   Handle
	}{
		Ctx: ctx,
		H:   h,
	}
	mock.lockDestroy.Lock()
	mock.calls.Destroy = append(mock.calls.Destroy, callInfo)
	mock.lockDestroy.Unlock()
	return mock.DestroyFunc(ctx, h)
}

// DestroyCalls gets all the calls that were made to Destroy.
// Check the length with:
//
//	len(mockedBackend.DestroyCalls())
func (mock *BackendMock) DestroyCalls() []struct {
	Ctx context.Context
	H   Handle
} {
	var calls []struct {
		Ctx context.Context
		H   Handle
	}
	mock.lockDestroy.RLock()
	calls = mock.calls.Destroy
	mock.lockDestroy.RUnlock()
	return calls
}

// Launch calls LaunchFunc.
func (mock *BackendMock) Launch(ctx context.Context, spec *Spec, reuse *Handle) (Handle, error) {
	if mock.LaunchFunc == nil {
		panic("BackendMock.LaunchFunc: method is nil but Backend.Launch was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Spec  *Spec
		Reuse *Handle
	}{
		Ctx:   ctx,
		Spec:  spec,
		Reuse: reuse,
	}
	mock.lockLaunch.Lock()
	mock.calls.Launch = append(mock.calls.Launch, callInfo)
	mock.lockLaunch.Unlock()
	return mock.LaunchFunc(ctx, spec, reuse)
}

// LaunchCalls gets all the calls that were made to Launch.
// Check the length with:
//
//	len(mockedBackend.LaunchCalls())
func (mock *BackendMock) LaunchCalls() []struct {
	Ctx   context.Context
	Spec  *Spec
	Reuse *Handle
} {
	var calls []struct {
		Ctx   context.Context
		Spec  *Spec
		Reuse *Handle
	}
	mock.lockLaunch.RLock()
	calls = mock.calls.Launch
	mock.lockLaunch.RUnlock()
	return calls
}

// Probe calls ProbeFunc.
func (mock *BackendMock) Probe(ctx context.Context, h Handle) (State, error) {
	if mock.ProbeFunc == nil {
		panic("BackendMock.ProbeFunc: method is nil but Backend.Probe was just called")
	}
	callInfo := struct {
		Ctx context.Context
		H   Handle
	}{
		Ctx: ctx,
		H:   h,
	}
	mock.lockProbe.Lock()
	mock.calls.Probe = append(mock.calls.Probe, callInfo)
	mock.lockProbe.Unlock()
	return mock.ProbeFunc(ctx, h)
}

// ProbeCalls gets all the calls that were made to Probe.
// Check the length with:
//
//	len(mockedBackend.ProbeCalls())
func (mock *BackendMock) ProbeCalls() []struct {
	Ctx context.Context
	H   Handle
} {
	var calls []struct {
		Ctx context.Context
		H   Handle
	}
	mock.lockProbe.RLock()
	calls = mock.calls.Probe
	mock.lockProbe.RUnlock()
	return calls
}

// Signal calls SignalFunc.
func (mock *BackendMock) Signal(ctx context.Context, h Handle) (bool, error) {
	if mock.SignalFunc == nil {
		panic("BackendMock.SignalFunc: method is nil but Backend.Signal was just called")
	}
	callInfo := struct {
		Ctx context.Context
		H   Handle
	}{
		Ctx: ctx,
		H:   h,
	}
	mock.lockSignal.Lock()
	mock.calls.Signal = append(mock.calls.Signal, callInfo)
	mock.lockSignal.Unlock()
	return mock.SignalFunc(ctx, h)
}

// SignalCalls gets all the calls that were made to Signal.
// Check the length with:
//
//	len(mockedBackend.SignalCalls())
func (mock *BackendMock) SignalCalls() []struct {
	Ctx context.Context
	H   Handle
} {
	var calls []struct {
		Ctx context.Context
		H   Handle
	}
	mock.lockSignal.RLock()
	calls = mock.calls.Signal
	mock.lockSignal.RUnlock()
	return calls
}

// ValidateWorkspace calls ValidateWorkspaceFunc.
func (mock *BackendMock) ValidateWorkspace(ws *workspace.Workspace) error {
	if mock.ValidateWorkspaceFunc == nil {
		panic("BackendMock.ValidateWorkspaceFunc: method is nil but Backend.ValidateWorkspace was just called")
	}
	callInfo := struct {
		Ws *workspace.Workspace
	}{
		Ws: ws,
	}
	mock.lockValidateWorkspace.Lock()
	mock.calls.ValidateWorkspace = append(mock.calls.ValidateWorkspace, callInfo)
	mock.lockValidateWorkspace.Unlock()
	return mock.ValidateWorkspaceFunc(ws)
}

// ValidateWorkspaceCalls gets all the calls that were made to ValidateWorkspace.
// Check the length with:
//
//	len(mockedBackend.ValidateWorkspaceCalls())
func (mock *BackendMock) ValidateWorkspaceCalls() []struct {
	Ws *workspace.Workspace
} {
	var calls []struct {
		Ws *workspace.Workspace
	}
	mock.lockValidateWorkspace.RLock()
	calls = mock.calls.ValidateWorkspace
	mock.lockValidateWorkspace.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *BackendMock) Watch(ctx context.Context, handle func(HandleExit)) error {
	if mock.WatchFunc == nil {
		panic("BackendMock.WatchFunc: method is nil but Backend.Watch was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Handle func(HandleExit)
	}{
		Ctx:    ctx,
		Handle: handle,
	}
	mock.lockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	mock.lockWatch.Unlock()
	return mock.WatchFunc(ctx, handle)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//
//	len(mockedBackend.WatchCalls())
func (mock *BackendMock) WatchCalls() []struct {
	Ctx    context.Context
	Handle func(HandleExit)
} {
	var calls []struct {
		Ctx    context.Context
		Handle func(HandleExit)
	}
	mock.lockWatch.RLock()
	calls = mock.calls.Watch
	mock.lockWatch.RUnlock()
	return calls
}
