// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package xagentclient

import (
	"context"
	"github.com/icholy/xagent/internal/proto/xagent/v1"
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			AddEventTaskFunc: func(contextMoqParam context.Context, addEventTaskRequest *xagentv1.AddEventTaskRequest) (*xagentv1.AddEventTaskResponse, error) {
//				panic("mock out the AddEventTask method")
//			},
//			ArchiveTaskFunc: func(contextMoqParam context.Context, archiveTaskRequest *xagentv1.ArchiveTaskRequest) (*xagentv1.ArchiveTaskResponse, error) {
//				panic("mock out the ArchiveTask method")
//			},
//			CancelTaskFunc: func(contextMoqParam context.Context, cancelTaskRequest *xagentv1.CancelTaskRequest) (*xagentv1.CancelTaskResponse, error) {
//				panic("mock out the CancelTask method")
//			},
//			ClearWorkspacesFunc: func(contextMoqParam context.Context, clearWorkspacesRequest *xagentv1.ClearWorkspacesRequest) (*xagentv1.ClearWorkspacesResponse, error) {
//				panic("mock out the ClearWorkspaces method")
//			},
//			CreateEventFunc: func(contextMoqParam context.Context, createEventRequest *xagentv1.CreateEventRequest) (*xagentv1.CreateEventResponse, error) {
//				panic("mock out the CreateEvent method")
//			},
//			CreateKeyFunc: func(contextMoqParam context.Context, createKeyRequest *xagentv1.CreateKeyRequest) (*xagentv1.CreateKeyResponse, error) {
//				panic("mock out the CreateKey method")
//			},
//			CreateLinkFunc: func(contextMoqParam context.Context, createLinkRequest *xagentv1.CreateLinkRequest) (*xagentv1.CreateLinkResponse, error) {
//				panic("mock out the CreateLink method")
//			},
//			CreateTaskFunc: func(contextMoqParam context.Context, createTaskRequest *xagentv1.CreateTaskRequest) (*xagentv1.CreateTaskResponse, error) {
//				panic("mock out the CreateTask method")
//			},
//			DeleteEventFunc: func(contextMoqParam context.Context, deleteEventRequest *xagentv1.DeleteEventRequest) (*xagentv1.DeleteEventResponse, error) {
//				panic("mock out the DeleteEvent method")
//			},
//			DeleteKeyFunc: func(contextMoqParam context.Context, deleteKeyRequest *xagentv1.DeleteKeyRequest) (*xagentv1.DeleteKeyResponse, error) {
//				panic("mock out the DeleteKey method")
//			},
//			DeleteTaskFunc: func(contextMoqParam context.Context, deleteTaskRequest *xagentv1.DeleteTaskRequest) (*xagentv1.DeleteTaskResponse, error) {
//				panic("mock out the DeleteTask method")
//			},
//			FindLinksByURLFunc: func(contextMoqParam context.Context, findLinksByURLRequest *xagentv1.FindLinksByURLRequest) (*xagentv1.FindLinksByURLResponse, error) {
//				panic("mock out the FindLinksByURL method")
//			},
//			GetEventFunc: func(contextMoqParam context.Context, getEventRequest *xagentv1.GetEventRequest) (*xagentv1.GetEventResponse, error) {
//				panic("mock out the GetEvent method")
//			},
//			GetGitHubAccountFunc: func(contextMoqParam context.Context, getGitHubAccountRequest *xagentv1.GetGitHubAccountRequest) (*xagentv1.GetGitHubAccountResponse, error) {
//				panic("mock out the GetGitHubAccount method")
//			},
//			GetProfileFunc: func(contextMoqParam context.Context, getProfileRequest *xagentv1.GetProfileRequest) (*xagentv1.GetProfileResponse, error) {
//				panic("mock out the GetProfile method")
//			},
//			GetTaskFunc: func(contextMoqParam context.Context, getTaskRequest *xagentv1.GetTaskRequest) (*xagentv1.GetTaskResponse, error) {
//				panic("mock out the GetTask method")
//			},
//			GetTaskDetailsFunc: func(contextMoqParam context.Context, getTaskDetailsRequest *xagentv1.GetTaskDetailsRequest) (*xagentv1.GetTaskDetailsResponse, error) {
//				panic("mock out the GetTaskDetails method")
//			},
//			ListChildTasksFunc: func(contextMoqParam context.Context, listChildTasksRequest *xagentv1.ListChildTasksRequest) (*xagentv1.ListChildTasksResponse, error) {
//				panic("mock out the ListChildTasks method")
//			},
//			ListEventTasksFunc: func(contextMoqParam context.Context, listEventTasksRequest *xagentv1.ListEventTasksRequest) (*xagentv1.ListEventTasksResponse, error) {
//				panic("mock out the ListEventTasks method")
//			},
//			ListEventsFunc: func(contextMoqParam context.Context, listEventsRequest *xagentv1.ListEventsRequest) (*xagentv1.ListEventsResponse, error) {
//				panic("mock out the ListEvents method")
//			},
//			ListEventsByTaskFunc: func(contextMoqParam context.Context, listEventsByTaskRequest *xagentv1.ListEventsByTaskRequest) (*xagentv1.ListEventsByTaskResponse, error) {
//				panic("mock out the ListEventsByTask method")
//			},
//			ListKeysFunc: func(contextMoqParam context.Context, listKeysRequest *xagentv1.ListKeysRequest) (*xagentv1.ListKeysResponse, error) {
//				panic("mock out the ListKeys method")
//			},
//			ListLinksFunc: func(contextMoqParam context.Context, listLinksRequest *xagentv1.ListLinksRequest) (*xagentv1.ListLinksResponse, error) {
//				panic("mock out the ListLinks method")
//			},
//			ListLogsFunc: func(contextMoqParam context.Context, listLogsRequest *xagentv1.ListLogsRequest) (*xagentv1.ListLogsResponse, error) {
//				panic("mock out the ListLogs method")
//			},
//			ListRunnerTasksFunc: func(contextMoqParam context.Context, listRunnerTasksRequest *xagentv1.ListRunnerTasksRequest) (*xagentv1.ListRunnerTasksResponse, error) {
//				panic("mock out the ListRunnerTasks method")
//			},
//			ListTasksFunc: func(contextMoqParam context.Context, listTasksRequest *xagentv1.ListTasksRequest) (*xagentv1.ListTasksResponse, error) {
//				panic("mock out the ListTasks method")
//			},
//			ListWorkspacesFunc: func(contextMoqParam context.Context, listWorkspacesRequest *xagentv1.ListWorkspacesRequest) (*xagentv1.ListWorkspacesResponse, error) {
//				panic("mock out the ListWorkspaces method")
//			},
//			PingFunc: func(contextMoqParam context.Context, pingRequest *xagentv1.PingRequest) (*xagentv1.PingResponse, error) {
//				panic("mock out the Ping method")
//			},
//			ProcessEventFunc: func(contextMoqParam context.Context, processEventRequest *xagentv1.ProcessEventRequest) (*xagentv1.ProcessEventResponse, error) {
//				panic("mock out the ProcessEvent method")
//			},
//			RegisterWorkspacesFunc: func(contextMoqParam context.Context, registerWorkspacesRequest *xagentv1.RegisterWorkspacesRequest) (*xagentv1.RegisterWorkspacesResponse, error) {
//				panic("mock out the RegisterWorkspaces method")
//			},
//			RemoveEventTaskFunc: func(contextMoqParam context.Context, removeEventTaskRequest *xagentv1.RemoveEventTaskRequest) (*xagentv1.RemoveEventTaskResponse, error) {
//				panic("mock out the RemoveEventTask method")
//			},
//			RestartTaskFunc: func(contextMoqParam context.Context, restartTaskRequest *xagentv1.RestartTaskRequest) (*xagentv1.RestartTaskResponse, error) {
//				panic("mock out the RestartTask method")
//			},
//			SubmitRunnerEventsFunc: func(contextMoqParam context.Context, submitRunnerEventsRequest *xagentv1.SubmitRunnerEventsRequest) (*xagentv1.SubmitRunnerEventsResponse, error) {
//				panic("mock out the SubmitRunnerEvents method")
//			},
//			UnarchiveTaskFunc: func(contextMoqParam context.Context, unarchiveTaskRequest *xagentv1.UnarchiveTaskRequest) (*xagentv1.UnarchiveTaskResponse, error) {
//				panic("mock out the UnarchiveTask method")
//			},
//			UnlinkGitHubAccountFunc: func(contextMoqParam context.Context, unlinkGitHubAccountRequest *xagentv1.UnlinkGitHubAccountRequest) (*xagentv1.UnlinkGitHubAccountResponse, error) {
//				panic("mock out the UnlinkGitHubAccount method")
//			},
//			UpdateTaskFunc: func(contextMoqParam context.Context, updateTaskRequest *xagentv1.UpdateTaskRequest) (*xagentv1.UpdateTaskResponse, error) {
//				panic("mock out the UpdateTask method")
//			},
//			UploadLogsFunc: func(contextMoqParam context.Context, uploadLogsRequest *xagentv1.UploadLogsRequest) (*xagentv1.UploadLogsResponse, error) {
//				panic("mock out the UploadLogs method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// AddEventTaskFunc mocks the AddEventTask method.
	AddEventTaskFunc func(contextMoqParam context.Context, addEventTaskRequest *xagentv1.AddEventTaskRequest) (*xagentv1.AddEventTaskResponse, error)

	// ArchiveTaskFunc mocks the ArchiveTask method.
	ArchiveTaskFunc func(contextMoqParam context.Context, archiveTaskRequest *xagentv1.ArchiveTaskRequest) (*xagentv1.ArchiveTaskResponse, error)

	// CancelTaskFunc mocks the CancelTask method.
	CancelTaskFunc func(contextMoqParam context.Context, cancelTaskRequest *xagentv1.CancelTaskRequest) (*xagentv1.CancelTaskResponse, error)

	// ClearWorkspacesFunc mocks the ClearWorkspaces method.
	ClearWorkspacesFunc func(contextMoqParam context.Context, clearWorkspacesRequest *xagentv1.ClearWorkspacesRequest) (*xagentv1.ClearWorkspacesResponse, error)

	// CreateEventFunc mocks the CreateEvent method.
	CreateEventFunc func(contextMoqParam context.Context, createEventRequest *xagentv1.CreateEventRequest) (*xagentv1.CreateEventResponse, error)

	// CreateKeyFunc mocks the CreateKey method.
	CreateKeyFunc func(contextMoqParam context.Context, createKeyRequest *xagentv1.CreateKeyRequest) (*xagentv1.CreateKeyResponse, error)

	// CreateLinkFunc mocks the CreateLink method.
	CreateLinkFunc func(contextMoqParam context.Context, createLinkRequest *xagentv1.CreateLinkRequest) (*xagentv1.CreateLinkResponse, error)

	// CreateTaskFunc mocks the CreateTask method.
	CreateTaskFunc func(contextMoqParam context.Context, createTaskRequest *xagentv1.CreateTaskRequest) (*xagentv1.CreateTaskResponse, error)

	// DeleteEventFunc mocks the DeleteEvent method.
	DeleteEventFunc func(contextMoqParam context.Context, deleteEventRequest *xagentv1.DeleteEventRequest) (*xagentv1.DeleteEventResponse, error)

	// DeleteKeyFunc mocks the DeleteKey method.
	DeleteKeyFunc func(contextMoqParam context.Context, deleteKeyRequest *xagentv1.DeleteKeyRequest) (*xagentv1.DeleteKeyResponse, error)

	// DeleteTaskFunc mocks the DeleteTask method.
	DeleteTaskFunc func(contextMoqParam context.Context, deleteTaskRequest *xagentv1.DeleteTaskRequest) (*xagentv1.DeleteTaskResponse, error)

	// FindLinksByURLFunc mocks the FindLinksByURL method.
	FindLinksByURLFunc func(contextMoqParam context.Context, findLinksByURLRequest *xagentv1.FindLinksByURLRequest) (*xagentv1.FindLinksByURLResponse, error)

	// GetEventFunc mocks the GetEvent method.
	GetEventFunc func(contextMoqParam context.Context, getEventRequest *xagentv1.GetEventRequest) (*xagentv1.GetEventResponse, error)

	// GetGitHubAccountFunc mocks the GetGitHubAccount method.
	GetGitHubAccountFunc func(contextMoqParam context.Context, getGitHubAccountRequest *xagentv1.GetGitHubAccountRequest) (*xagentv1.GetGitHubAccountResponse, error)

	// GetProfileFunc mocks the GetProfile method.
	GetProfileFunc func(contextMoqParam context.Context, getProfileRequest *xagentv1.GetProfileRequest) (*xagentv1.GetProfileResponse, error)

	// GetTaskFunc mocks the GetTask method.
	GetTaskFunc func(contextMoqParam context.Context, getTaskRequest *xagentv1.GetTaskRequest) (*xagentv1.GetTaskResponse, error)

	// GetTaskDetailsFunc mocks the GetTaskDetails method.
	GetTaskDetailsFunc func(contextMoqParam context.Context, getTaskDetailsRequest *xagentv1.GetTaskDetailsRequest) (*xagentv1.GetTaskDetailsResponse, error)

	// ListChildTasksFunc mocks the ListChildTasks method.
	ListChildTasksFunc func(contextMoqParam context.Context, listChildTasksRequest *xagentv1.ListChildTasksRequest) (*xagentv1.ListChildTasksResponse, error)

	// ListEventTasksFunc mocks the ListEventTasks method.
	ListEventTasksFunc func(contextMoqParam context.Context, listEventTasksRequest *xagentv1.ListEventTasksRequest) (*xagentv1.ListEventTasksResponse, error)

	// ListEventsFunc mocks the ListEvents method.
	ListEventsFunc func(contextMoqParam context.Context, listEventsRequest *xagentv1.ListEventsRequest) (*xagentv1.ListEventsResponse, error)

	// ListEventsByTaskFunc mocks the ListEventsByTask method.
	ListEventsByTaskFunc func(contextMoqParam context.Context, listEventsByTaskRequest *xagentv1.ListEventsByTaskRequest) (*xagentv1.ListEventsByTaskResponse, error)

	// ListKeysFunc mocks the ListKeys method.
	ListKeysFunc func(contextMoqParam context.Context, listKeysRequest *xagentv1.ListKeysRequest) (*xagentv1.ListKeysResponse, error)

	// ListLinksFunc mocks the ListLinks method.
	ListLinksFunc func(contextMoqParam context.Context, listLinksRequest *xagentv1.ListLinksRequest) (*xagentv1.ListLinksResponse, error)

	// ListLogsFunc mocks the ListLogs method.
	ListLogsFunc func(contextMoqParam context.Context, listLogsRequest *xagentv1.ListLogsRequest) (*xagentv1.ListLogsResponse, error)

	// ListRunnerTasksFunc mocks the ListRunnerTasks method.
	ListRunnerTasksFunc func(contextMoqParam context.Context, listRunnerTasksRequest *xagentv1.ListRunnerTasksRequest) (*xagentv1.ListRunnerTasksResponse, error)

	// ListTasksFunc mocks the ListTasks method.
	ListTasksFunc func(contextMoqParam context.Context, listTasksRequest *xagentv1.ListTasksRequest) (*xagentv1.ListTasksResponse, error)

	// ListWorkspacesFunc mocks the ListWorkspaces method.
	ListWorkspacesFunc func(contextMoqParam context.Context, listWorkspacesRequest *xagentv1.ListWorkspacesRequest) (*xagentv1.ListWorkspacesResponse, error)

	// PingFunc mocks the Ping method.
	PingFunc func(contextMoqParam context.Context, pingRequest *xagentv1.PingRequest) (*xagentv1.PingResponse, error)

	// ProcessEventFunc mocks the ProcessEvent method.
	ProcessEventFunc func(contextMoqParam context.Context, processEventRequest *xagentv1.ProcessEventRequest) (*xagentv1.ProcessEventResponse, error)

	// RegisterWorkspacesFunc mocks the RegisterWorkspaces method.
	RegisterWorkspacesFunc func(contextMoqParam context.Context, registerWorkspacesRequest *xagentv1.RegisterWorkspacesRequest) (*xagentv1.RegisterWorkspacesResponse, error)

	// RemoveEventTaskFunc mocks the RemoveEventTask method.
	RemoveEventTaskFunc func(contextMoqParam context.Context, removeEventTaskRequest *xagentv1.RemoveEventTaskRequest) (*xagentv1.RemoveEventTaskResponse, error)

	// RestartTaskFunc mocks the RestartTask method.
	RestartTaskFunc func(contextMoqParam context.Context, restartTaskRequest *xagentv1.RestartTaskRequest) (*xagentv1.RestartTaskResponse, error)

	// SubmitRunnerEventsFunc mocks the SubmitRunnerEvents method.
	SubmitRunnerEventsFunc func(contextMoqParam context.Context, submitRunnerEventsRequest *xagentv1.SubmitRunnerEventsRequest) (*xagentv1.SubmitRunnerEventsResponse, error)

	// UnarchiveTaskFunc mocks the UnarchiveTask method.
	UnarchiveTaskFunc func(contextMoqParam context.Context, unarchiveTaskRequest *xagentv1.UnarchiveTaskRequest) (*xagentv1.UnarchiveTaskResponse, error)

	// UnlinkGitHubAccountFunc mocks the UnlinkGitHubAccount method.
	UnlinkGitHubAccountFunc func(contextMoqParam context.Context, unlinkGitHubAccountRequest *xagentv1.UnlinkGitHubAccountRequest) (*xagentv1.UnlinkGitHubAccountResponse, error)

	// UpdateTaskFunc mocks the UpdateTask method.
	UpdateTaskFunc func(contextMoqParam context.Context, updateTaskRequest *xagentv1.UpdateTaskRequest) (*xagentv1.UpdateTaskResponse, error)

	// UploadLogsFunc mocks the UploadLogs method.
	UploadLogsFunc func(contextMoqParam context.Context, uploadLogsRequest *xagentv1.UploadLogsRequest) (*xagentv1.UploadLogsResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddEventTask holds details about calls to the AddEventTask method.
		AddEventTask []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// AddEventTaskRequest is the addEventTaskRequest argument value.
			AddEventTaskRequest *xagentv1.AddEventTaskRequest
		}
		// ArchiveTask holds details about calls to the ArchiveTask method.
		ArchiveTask []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ArchiveTaskRequest is the archiveTaskRequest argument value.
			ArchiveTaskRequest *xagentv1.ArchiveTaskRequest
		}
		// CancelTask holds details about calls to the CancelTask method.
		CancelTask []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// CancelTaskRequest is the cancelTaskRequest argument value.
			CancelTaskRequest *xagentv1.CancelTaskRequest
		}
		// ClearWorkspaces holds details about calls to the ClearWorkspaces method.
		ClearWorkspaces []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ClearWorkspacesRequest is the clearWorkspacesRequest argument value.
			ClearWorkspacesRequest *xagentv1.ClearWorkspacesRequest
		}
		// CreateEvent holds details about calls to the CreateEvent method.
		CreateEvent []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// CreateEventRequest is the createEventRequest argument value.
			CreateEventRequest *xagentv1.CreateEventRequest
		}
		// CreateKey holds details about calls to the CreateKey method.
		CreateKey []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// CreateKeyRequest is the createKeyRequest argument value.
			CreateKeyRequest *xagentv1.CreateKeyRequest
		}
		// CreateLink holds details about calls to the CreateLink method.
		CreateLink []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// CreateLinkRequest is the createLinkRequest argument value.
			CreateLinkRequest *xagentv1.CreateLinkRequest
		}
		// CreateTask holds details about calls to the CreateTask method.
		CreateTask []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// CreateTaskRequest is the createTaskRequest argument value.
			CreateTaskRequest *xagentv1.CreateTaskRequest
		}
		// DeleteEvent holds details about calls to the DeleteEvent method.
		DeleteEvent []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DeleteEventRequest is the deleteEventRequest argument value.
			DeleteEventRequest *xagentv1.DeleteEventRequest
		}
		// DeleteKey holds details about calls to the DeleteKey method.
		DeleteKey []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DeleteKeyRequest is the deleteKeyRequest argument value.
			DeleteKeyRequest *xagentv1.DeleteKeyRequest
		}
		// DeleteTask holds details about calls to the DeleteTask method.
		DeleteTask []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DeleteTaskRequest is the deleteTaskRequest argument value.
			DeleteTaskRequest *xagentv1.DeleteTaskRequest
		}
		// FindLinksByURL holds details about calls to the FindLinksByURL method.
		FindLinksByURL []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// FindLinksByURLRequest is the findLinksByURLRequest argument value.
			FindLinksByURLRequest *xagentv1.FindLinksByURLRequest
		}
		// GetEvent holds details about calls to the GetEvent method.
		GetEvent []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// GetEventRequest is the getEventRequest argument value.
			GetEventRequest *xagentv1.GetEventRequest
		}
		// GetGitHubAccount holds details about calls to the GetGitHubAccount method.
		GetGitHubAccount []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// GetGitHubAccountRequest is the getGitHubAccountRequest argument value.
			GetGitHubAccountRequest *xagentv1.GetGitHubAccountRequest
		}
		// GetProfile holds details about calls to the GetProfile method.
		GetProfile []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// GetProfileRequest is the getProfileRequest argument value.
			GetProfileRequest *xagentv1.GetProfileRequest
		}
		// GetTask holds details about calls to the GetTask method.
		GetTask []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// GetTaskRequest is the getTaskRequest argument value.
			GetTaskRequest *xagentv1.GetTaskRequest
		}
		// GetTaskDetails holds details about calls to the GetTaskDetails method.
		GetTaskDetails []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// GetTaskDetailsRequest is the getTaskDetailsRequest argument value.
			GetTaskDetailsRequest *xagentv1.GetTaskDetailsRequest
		}
		// ListChildTasks holds details about calls to the ListChildTasks method.
		ListChildTasks []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListChildTasksRequest is the listChildTasksRequest argument value.
			ListChildTasksRequest *xagentv1.ListChildTasksRequest
		}
		// ListEventTasks holds details about calls to the ListEventTasks method.
		ListEventTasks []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListEventTasksRequest is the listEventTasksRequest argument value.
			ListEventTasksRequest *xagentv1.ListEventTasksRequest
		}
		// ListEvents holds details about calls to the ListEvents method.
		ListEvents []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListEventsRequest is the listEventsRequest argument value.
			ListEventsRequest *xagentv1.ListEventsRequest
		}
		// ListEventsByTask holds details about calls to the ListEventsByTask method.
		ListEventsByTask []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListEventsByTaskRequest is the listEventsByTaskRequest argument value.
			ListEventsByTaskRequest *xagentv1.ListEventsByTaskRequest
		}
		// ListKeys holds details about calls to the ListKeys method.
		ListKeys []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListKeysRequest is the listKeysRequest argument value.
			ListKeysRequest *xagentv1.ListKeysRequest
		}
		// ListLinks holds details about calls to the ListLinks method.
		ListLinks []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListLinksRequest is the listLinksRequest argument value.
			ListLinksRequest *xagentv1.ListLinksRequest
		}
		// ListLogs holds details about calls to the ListLogs method.
		ListLogs []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListLogsRequest is the listLogsRequest argument value.
			ListLogsRequest *xagentv1.ListLogsRequest
		}
		// ListRunnerTasks holds details about calls to the ListRunnerTasks method.
		ListRunnerTasks []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListRunnerTasksRequest is the listRunnerTasksRequest argument value.
			ListRunnerTasksRequest *xagentv1.ListRunnerTasksRequest
		}
		// ListTasks holds details about calls to the ListTasks method.
		ListTasks []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListTasksRequest is the listTasksRequest argument value.
			ListTasksRequest *xagentv1.ListTasksRequest
		}
		// ListWorkspaces holds details about calls to the ListWorkspaces method.
		ListWorkspaces []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListWorkspacesRequest is the listWorkspacesRequest argument value.
			ListWorkspacesRequest *xagentv1.ListWorkspacesRequest
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PingRequest is the pingRequest argument value.
			PingRequest *xagentv1.PingRequest
		}
		// ProcessEvent holds details about calls to the ProcessEvent method.
		ProcessEvent []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ProcessEventRequest is the processEventRequest argument value.
			ProcessEventRequest *xagentv1.ProcessEventRequest
		}
		// RegisterWorkspaces holds details about calls to the RegisterWorkspaces method.
		RegisterWorkspaces []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// RegisterWorkspacesRequest is the registerWorkspacesRequest argument value.
			RegisterWorkspacesRequest *xagentv1.RegisterWorkspacesRequest
		}
		// RemoveEventTask holds details about calls to the RemoveEventTask method.
		RemoveEventTask []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// RemoveEventTaskRequest is the removeEventTaskRequest argument value.
			RemoveEventTaskRequest *xagentv1.RemoveEventTaskRequest
		}
		// RestartTask holds details about calls to the RestartTask method.
		RestartTask []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// RestartTaskRequest is the restartTaskRequest argument value.
			RestartTaskRequest *xagentv1.RestartTaskRequest
		}
		// SubmitRunnerEvents holds details about calls to the SubmitRunnerEvents method.
		SubmitRunnerEvents []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// SubmitRunnerEventsRequest is the submitRunnerEventsRequest argument value.
			SubmitRunnerEventsRequest *xagentv1.SubmitRunnerEventsRequest
		}
		// UnarchiveTask holds details about calls to the UnarchiveTask method.
		UnarchiveTask []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UnarchiveTaskRequest is the unarchiveTaskRequest argument value.
			UnarchiveTaskRequest *xagentv1.UnarchiveTaskRequest
		}
		// UnlinkGitHubAccount holds details about calls to the UnlinkGitHubAccount method.
		UnlinkGitHubAccount []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UnlinkGitHubAccountRequest is the unlinkGitHubAccountRequest argument value.
			UnlinkGitHubAccountRequest *xagentv1.UnlinkGitHubAccountRequest
		}
		// UpdateTask holds details about calls to the UpdateTask method.
		UpdateTask []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UpdateTaskRequest is the updateTaskRequest argument value.
			UpdateTaskRequest *xagentv1.UpdateTaskRequest
		}
		// UploadLogs holds details about calls to the UploadLogs method.
		UploadLogs []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UploadLogsRequest is the uploadLogsRequest argument value.
			UploadLogsRequest *xagentv1.UploadLogsRequest
		}
	}
	lockAddEventTask        sync.RWMutex
	lockArchiveTask         sync.RWMutex
	lockCancelTask          sync.RWMutex
	lockClearWorkspaces     sync.RWMutex
	lockCreateEvent         sync.RWMutex
	lockCreateKey           sync.RWMutex
	lockCreateLink          sync.RWMutex
	lockCreateTask          sync.RWMutex
	lockDeleteEvent         sync.RWMutex
	lockDeleteKey           sync.RWMutex
	lockDeleteTask          sync.RWMutex
	lockFindLinksByURL      sync.RWMutex
	lockGetEvent            sync.RWMutex
	lockGetGitHubAccount    sync.RWMutex
	lockGetProfile          sync.RWMutex
	lockGetTask             sync.RWMutex
	lockGetTaskDetails      sync.RWMutex
	lockListChildTasks      sync.RWMutex
	lockListEventTasks      sync.RWMutex
	lockListEvents          sync.RWMutex
	lockListEventsByTask    sync.RWMutex
	lockListKeys            sync.RWMutex
	lockListLinks           sync.RWMutex
	lockListLogs            sync.RWMutex
	lockListRunnerTasks     sync.RWMutex
	lockListTasks           sync.RWMutex
	lockListWorkspaces      sync.RWMutex
	lockPing                sync.RWMutex
	lockProcessEvent        sync.RWMutex
	lockRegisterWorkspaces  sync.RWMutex
	lockRemoveEventTask     sync.RWMutex
	lockRestartTask         sync.RWMutex
	lockSubmitRunnerEvents  sync.RWMutex
	lockUnarchiveTask       sync.RWMutex
	lockUnlinkGitHubAccount sync.RWMutex
	lockUpdateTask          sync.RWMutex
	lockUploadLogs          sync.RWMutex
}

// AddEventTask calls AddEventTaskFunc.
func (mock *ClientMock) AddEventTask(contextMoqParam context.Context, addEventTaskRequest *xagentv1.AddEventTaskRequest) (*xagentv1.AddEventTaskResponse, error) {
	if mock.AddEventTaskFunc == nil {
		panic("ClientMock.AddEventTaskFunc: method is nil but Client.AddEventTask was just called")
	}
	callInfo := struct {
		ContextMoqParam     context.Context
		AddEventTaskRequest *xagentv1.AddEventTaskRequest
	}{
		ContextMoqParam:     contextMoqParam,
		AddEventTaskRequest: addEventTaskRequest,
	}
	mock.lockAddEventTask.Lock()
	mock.calls.AddEventTask = append(mock.calls.AddEventTask, callInfo)
	mock.lockAddEventTask.Unlock()
	return mock.AddEventTaskFunc(contextMoqParam, addEventTaskRequest)
}

// AddEventTaskCalls gets all the calls that were made to AddEventTask.
// Check the length with:
//
//	len(mockedClient.AddEventTaskCalls())
func (mock *ClientMock) AddEventTaskCalls() []struct {
	ContextMoqParam     context.Context
	AddEventTaskRequest *xagentv1.AddEventTaskRequest
} {
	var calls []struct {
		ContextMoqParam     context.Context
		AddEventTaskRequest *xagentv1.AddEventTaskRequest
	}
	mock.lockAddEventTask.RLock()
	calls = mock.calls.AddEventTask
	mock.lockAddEventTask.RUnlock()
	return calls
}

// ArchiveTask calls ArchiveTaskFunc.
func (mock *ClientMock) ArchiveTask(contextMoqParam context.Context, archiveTaskRequest *xagentv1.ArchiveTaskRequest) (*xagentv1.ArchiveTaskResponse, error) {
	if mock.ArchiveTaskFunc == nil {
		panic("ClientMock.ArchiveTaskFunc: method is nil but Client.ArchiveTask was just called")
	}
	callInfo := struct {
		ContextMoqParam    context.Context
		ArchiveTaskRequest *xagentv1.ArchiveTaskRequest
	}{
		ContextMoqParam:    contextMoqParam,
		ArchiveTaskRequest: archiveTaskRequest,
	}
	mock.lockArchiveTask.Lock()
	mock.calls.ArchiveTask = append(mock.calls.ArchiveTask, callInfo)
	mock.lockArchiveTask.Unlock()
	return mock.ArchiveTaskFunc(contextMoqParam, archiveTaskRequest)
}

// ArchiveTaskCalls gets all the calls that were made to ArchiveTask.
// Check the length with:
//
//	len(mockedClient.ArchiveTaskCalls())
func (mock *ClientMock) ArchiveTaskCalls() []struct {
	ContextMoqParam    context.Context
	ArchiveTaskRequest *xagentv1.ArchiveTaskRequest
} {
	var calls []struct {
		ContextMoqParam    context.Context
		ArchiveTaskRequest *xagentv1.ArchiveTaskRequest
	}
	mock.lockArchiveTask.RLock()
	calls = mock.calls.ArchiveTask
	mock.lockArchiveTask.RUnlock()
	return calls
}

// CancelTask calls CancelTaskFunc.
func (mock *ClientMock) CancelTask(contextMoqParam context.Context, cancelTaskRequest *xagentv1.CancelTaskRequest) (*xagentv1.CancelTaskResponse, error) {
	if mock.CancelTaskFunc == nil {
		panic("ClientMock.CancelTaskFunc: method is nil but Client.CancelTask was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		CancelTaskRequest *xagentv1.CancelTaskRequest
	}{
		ContextMoqParam:   contextMoqParam,
		CancelTaskRequest: cancelTaskRequest,
	}
	mock.lockCancelTask.Lock()
	mock.calls.CancelTask = append(mock.calls.CancelTask, callInfo)
	mock.lockCancelTask.Unlock()
	return mock.CancelTaskFunc(contextMoqParam, cancelTaskRequest)
}

// CancelTaskCalls gets all the calls that were made to CancelTask.
// Check the length with:
//
//	len(mockedClient.CancelTaskCalls())
func (mock *ClientMock) CancelTaskCalls() []struct {
	ContextMoqParam   context.Context
	CancelTaskRequest *xagentv1.CancelTaskRequest
} {
	var calls []struct {
		ContextMoqParam   context.Context
		CancelTaskRequest *xagentv1.CancelTaskRequest
	}
	mock.lockCancelTask.RLock()
	calls = mock.calls.CancelTask
	mock.lockCancelTask.RUnlock()
	return calls
}

// ClearWorkspaces calls ClearWorkspacesFunc.
func (mock *ClientMock) ClearWorkspaces(contextMoqParam context.Context, clearWorkspacesRequest *xagentv1.ClearWorkspacesRequest) (*xagentv1.ClearWorkspacesResponse, error) {
	if mock.ClearWorkspacesFunc == nil {
		panic("ClientMock.ClearWorkspacesFunc: method is nil but Client.ClearWorkspaces was just called")
	}
	callInfo := struct {
		ContextMoqParam        context.Context
		ClearWorkspacesRequest *xagentv1.ClearWorkspacesRequest
	}{
		ContextMoqParam:        contextMoqParam,
		ClearWorkspacesRequest: clearWorkspacesRequest,
	}
	mock.lockClearWorkspaces.Lock()
	mock.calls.ClearWorkspaces = append(mock.calls.ClearWorkspaces, callInfo)
	mock.lockClearWorkspaces.Unlock()
	return mock.ClearWorkspacesFunc(contextMoqParam, clearWorkspacesRequest)
}

// ClearWorkspacesCalls gets all the calls that were made to ClearWorkspaces.
// Check the length with:
//
//	len(mockedClient.ClearWorkspacesCalls())
func (mock *ClientMock) ClearWorkspacesCalls() []struct {
	ContextMoqParam        context.Context
	ClearWorkspacesRequest *xagentv1.ClearWorkspacesRequest
} {
	var calls []struct {
		ContextMoqParam        context.Context
		ClearWorkspacesRequest *xagentv1.ClearWorkspacesRequest
	}
	mock.lockClearWorkspaces.RLock()
	calls = mock.calls.ClearWorkspaces
	mock.lockClearWorkspaces.RUnlock()
	return calls
}

// CreateEvent calls CreateEventFunc.
func (mock *ClientMock) CreateEvent(contextMoqParam context.Context, createEventRequest *xagentv1.CreateEventRequest) (*xagentv1.CreateEventResponse, error) {
	if mock.CreateEventFunc == nil {
		panic("ClientMock.CreateEventFunc: method is nil but Client.CreateEvent was just called")
	}
	callInfo := struct {
		ContextMoqParam    context.Context
		CreateEventRequest *xagentv1.CreateEventRequest
	}{
		ContextMoqParam:    contextMoqParam,
		CreateEventRequest: createEventRequest,
	}
	mock.lockCreateEvent.Lock()
	mock.calls.CreateEvent = append(mock.calls.CreateEvent, callInfo)
	mock.lockCreateEvent.Unlock()
	return mock.CreateEventFunc(contextMoqParam, createEventRequest)
}

// CreateEventCalls gets all the calls that were made to CreateEvent.
// Check the length with:
//
//	len(mockedClient.CreateEventCalls())
func (mock *ClientMock) CreateEventCalls() []struct {
	ContextMoqParam    context.Context
	CreateEventRequest *xagentv1.CreateEventRequest
} {
	var calls []struct {
		ContextMoqParam    context.Context
		CreateEventRequest *xagentv1.CreateEventRequest
	}
	mock.lockCreateEvent.RLock()
	calls = mock.calls.CreateEvent
	mock.lockCreateEvent.RUnlock()
	return calls
}

// CreateKey calls CreateKeyFunc.
func (mock *ClientMock) CreateKey(contextMoqParam context.Context, createKeyRequest *xagentv1.CreateKeyRequest) (*xagentv1.CreateKeyResponse, error) {
	if mock.CreateKeyFunc == nil {
		panic("ClientMock.CreateKeyFunc: method is nil but Client.CreateKey was just called")
	}
	callInfo := struct {
		ContextMoqParam  context.Context
		CreateKeyRequest *xagentv1.CreateKeyRequest
	}{
		ContextMoqParam:  contextMoqParam,
		CreateKeyRequest: createKeyRequest,
	}
	mock.lockCreateKey.Lock()
	mock.calls.CreateKey = append(mock.calls.CreateKey, callInfo)
	mock.lockCreateKey.Unlock()
	return mock.CreateKeyFunc(contextMoqParam, createKeyRequest)
}

// CreateKeyCalls gets all the calls that were made to CreateKey.
// Check the length with:
//
//	len(mockedClient.CreateKeyCalls())
func (mock *ClientMock) CreateKeyCalls() []struct {
	ContextMoqParam  context.Context
	CreateKeyRequest *xagentv1.CreateKeyRequest
} {
	var calls []struct {
		ContextMoqParam  context.Context
		CreateKeyRequest *xagentv1.CreateKeyRequest
	}
	mock.lockCreateKey.RLock()
	calls = mock.calls.CreateKey
	mock.lockCreateKey.RUnlock()
	return calls
}

// CreateLink calls CreateLinkFunc.
func (mock *ClientMock) CreateLink(contextMoqParam context.Context, createLinkRequest *xagentv1.CreateLinkRequest) (*xagentv1.CreateLinkResponse, error) {
	if mock.CreateLinkFunc == nil {
		panic("ClientMock.CreateLinkFunc: method is nil but Client.CreateLink was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		CreateLinkRequest *xagentv1.CreateLinkRequest
	}{
		ContextMoqParam:   contextMoqParam,
		CreateLinkRequest: createLinkRequest,
	}
	mock.lockCreateLink.Lock()
	mock.calls.CreateLink = append(mock.calls.CreateLink, callInfo)
	mock.lockCreateLink.Unlock()
	return mock.CreateLinkFunc(contextMoqParam, createLinkRequest)
}

// CreateLinkCalls gets all the calls that were made to CreateLink.
// Check the length with:
//
//	len(mockedClient.CreateLinkCalls())
func (mock *ClientMock) CreateLinkCalls() []struct {
	ContextMoqParam   context.Context
	CreateLinkRequest *xagentv1.CreateLinkRequest
} {
	var calls []struct {
		ContextMoqParam   context.Context
		CreateLinkRequest *xagentv1.CreateLinkRequest
	}
	mock.lockCreateLink.RLock()
	calls = mock.calls.CreateLink
	mock.lockCreateLink.RUnlock()
	return calls
}

// CreateTask calls CreateTaskFunc.
func (mock *ClientMock) CreateTask(contextMoqParam context.Context, createTaskRequest *xagentv1.CreateTaskRequest) (*xagentv1.CreateTaskResponse, error) {
	if mock.CreateTaskFunc == nil {
		panic("ClientMock.CreateTaskFunc: method is nil but Client.CreateTask was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		CreateTaskRequest *xagentv1.CreateTaskRequest
	}{
		ContextMoqParam:   contextMoqParam,
		CreateTaskRequest: createTaskRequest,
	}
	mock.lockCreateTask.Lock()
	mock.calls.CreateTask = append(mock.calls.CreateTask, callInfo)
	mock.lockCreateTask.Unlock()
	return mock.CreateTaskFunc(contextMoqParam, createTaskRequest)
}

// CreateTaskCalls gets all the calls that were made to CreateTask.
// Check the length with:
//
//	len(mockedClient.CreateTaskCalls())
func (mock *ClientMock) CreateTaskCalls() []struct {
	ContextMoqParam   context.Context
	CreateTaskRequest *xagentv1.CreateTaskRequest
} {
	var calls []struct {
		ContextMoqParam   context.Context
		CreateTaskRequest *xagentv1.CreateTaskRequest
	}
	mock.lockCreateTask.RLock()
	calls = mock.calls.CreateTask
	mock.lockCreateTask.RUnlock()
	return calls
}

// DeleteEvent calls DeleteEventFunc.
func (mock *ClientMock) DeleteEvent(contextMoqParam context.Context, deleteEventRequest *xagentv1.DeleteEventRequest) (*xagentv1.DeleteEventResponse, error) {
	if mock.DeleteEventFunc == nil {
		panic("ClientMock.DeleteEventFunc: method is nil but Client.DeleteEvent was just called")
	}
	callInfo := struct {
		ContextMoqParam    context.Context
		DeleteEventRequest *xagentv1.DeleteEventRequest
	}{
		ContextMoqParam:    contextMoqParam,
		DeleteEventRequest: deleteEventRequest,
	}
	mock.lockDeleteEvent.Lock()
	mock.calls.DeleteEvent = append(mock.calls.DeleteEvent, callInfo)
	mock.lockDeleteEvent.Unlock()
	return mock.DeleteEventFunc(contextMoqParam, deleteEventRequest)
}

// DeleteEventCalls gets all the calls that were made to DeleteEvent.
// Check the length with:
//
//	len(mockedClient.DeleteEventCalls())
func (mock *ClientMock) DeleteEventCalls() []struct {
	ContextMoqParam    context.Context
	DeleteEventRequest *xagentv1.DeleteEventRequest
} {
	var calls []struct {
		ContextMoqParam    context.Context
		DeleteEventRequest *xagentv1.DeleteEventRequest
	}
	mock.lockDeleteEvent.RLock()
	calls = mock.calls.DeleteEvent
	mock.lockDeleteEvent.RUnlock()
	return calls
}

// DeleteKey calls DeleteKeyFunc.
func (mock *ClientMock) DeleteKey(contextMoqParam context.Context, deleteKeyRequest *xagentv1.DeleteKeyRequest) (*xagentv1.DeleteKeyResponse, error) {
	if mock.DeleteKeyFunc == nil {
		panic("ClientMock.DeleteKeyFunc: method is nil but Client.DeleteKey was just called")
	}
	callInfo := struct {
		ContextMoqParam  context.Context
		DeleteKeyRequest *xagentv1.DeleteKeyRequest
	}{
		ContextMoqParam:  contextMoqParam,
		DeleteKeyRequest: deleteKeyRequest,
	}
	mock.lockDeleteKey.Lock()
	mock.calls.DeleteKey = append(mock.calls.DeleteKey, callInfo)
	mock.lockDeleteKey.Unlock()
	return mock.DeleteKeyFunc(contextMoqParam, deleteKeyRequest)
}

// DeleteKeyCalls gets all the calls that were made to DeleteKey.
// Check the length with:
//
//	len(mockedClient.DeleteKeyCalls())
func (mock *ClientMock) DeleteKeyCalls() []struct {
	ContextMoqParam  context.Context
	DeleteKeyRequest *xagentv1.DeleteKeyRequest
} {
	var calls []struct {
		ContextMoqParam  context.Context
		DeleteKeyRequest *xagentv1.DeleteKeyRequest
	}
	mock.lockDeleteKey.RLock()
	calls = mock.calls.DeleteKey
	mock.lockDeleteKey.RUnlock()
	return calls
}

// DeleteTask calls DeleteTaskFunc.
func (mock *ClientMock) DeleteTask(contextMoqParam context.Context, deleteTaskRequest *xagentv1.DeleteTaskRequest) (*xagentv1.DeleteTaskResponse, error) {
	if mock.DeleteTaskFunc == nil {
		panic("ClientMock.DeleteTaskFunc: method is nil but Client.DeleteTask was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		DeleteTaskRequest *xagentv1.DeleteTaskRequest
	}{
		ContextMoqParam:   contextMoqParam,
		DeleteTaskRequest: deleteTaskRequest,
	}
	mock.lockDeleteTask.Lock()
	mock.calls.DeleteTask = append(mock.calls.DeleteTask, callInfo)
	mock.lockDeleteTask.Unlock()
	return mock.DeleteTaskFunc(contextMoqParam, deleteTaskRequest)
}

// DeleteTaskCalls gets all the calls that were made to DeleteTask.
// Check the length with:
//
//	len(mockedClient.DeleteTaskCalls())
func (mock *ClientMock) DeleteTaskCalls() []struct {
	ContextMoqParam   context.Context
	DeleteTaskRequest *xagentv1.DeleteTaskRequest
} {
	var calls []struct {
		ContextMoqParam   context.Context
		DeleteTaskRequest *xagentv1.DeleteTaskRequest
	}
	mock.lockDeleteTask.RLock()
	calls = mock.calls.DeleteTask
	mock.lockDeleteTask.RUnlock()
	return calls
}

// FindLinksByURL calls FindLinksByURLFunc.
func (mock *ClientMock) FindLinksByURL(contextMoqParam context.Context, findLinksByURLRequest *xagentv1.FindLinksByURLRequest) (*xagentv1.FindLinksByURLResponse, error) {
	if mock.FindLinksByURLFunc == nil {
		panic("ClientMock.FindLinksByURLFunc: method is nil but Client.FindLinksByURL was just called")
	}
	callInfo := struct {
		ContextMoqParam       context.Context
		FindLinksByURLRequest *xagentv1.FindLinksByURLRequest
	}{
		ContextMoqParam:       contextMoqParam,
		FindLinksByURLRequest: findLinksByURLRequest,
	}
	mock.lockFindLinksByURL.Lock()
	mock.calls.FindLinksByURL = append(mock.calls.FindLinksByURL, callInfo)
	mock.lockFindLinksByURL.Unlock()
	return mock.FindLinksByURLFunc(contextMoqParam, findLinksByURLRequest)
}

// FindLinksByURLCalls gets all the calls that were made to FindLinksByURL.
// Check the length with:
//
//	len(mockedClient.FindLinksByURLCalls())
func (mock *ClientMock) FindLinksByURLCalls() []struct {
	ContextMoqParam       context.Context
	FindLinksByURLRequest *xagentv1.FindLinksByURLRequest
} {
	var calls []struct {
		ContextMoqParam       context.Context
		FindLinksByURLRequest *xagentv1.FindLinksByURLRequest
	}
	mock.lockFindLinksByURL.RLock()
	calls = mock.calls.FindLinksByURL
	mock.lockFindLinksByURL.RUnlock()
	return calls
}

// GetEvent calls GetEventFunc.
func (mock *ClientMock) GetEvent(contextMoqParam context.Context, getEventRequest *xagentv1.GetEventRequest) (*xagentv1.GetEventResponse, error) {
	if mock.GetEventFunc == nil {
		panic("ClientMock.GetEventFunc: method is nil but Client.GetEvent was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		GetEventRequest *xagentv1.GetEventRequest
	}{
		ContextMoqParam: contextMoqParam,
		GetEventRequest: getEventRequest,
	}
	mock.lockGetEvent.Lock()
	mock.calls.GetEvent = append(mock.calls.GetEvent, callInfo)
	mock.lockGetEvent.Unlock()
	return mock.GetEventFunc(contextMoqParam, getEventRequest)
}

// GetEventCalls gets all the calls that were made to GetEvent.
// Check the length with:
//
//	len(mockedClient.GetEventCalls())
func (mock *ClientMock) GetEventCalls() []struct {
	ContextMoqParam context.Context
	GetEventRequest *xagentv1.GetEventRequest
} {
	var calls []struct {
		ContextMoqParam context.Context
		GetEventRequest *xagentv1.GetEventRequest
	}
	mock.lockGetEvent.RLock()
	calls = mock.calls.GetEvent
	mock.lockGetEvent.RUnlock()
	return calls
}

// GetGitHubAccount calls GetGitHubAccountFunc.
func (mock *ClientMock) GetGitHubAccount(contextMoqParam context.Context, getGitHubAccountRequest *xagentv1.GetGitHubAccountRequest) (*xagentv1.GetGitHubAccountResponse, error) {
	if mock.GetGitHubAccountFunc == nil {
		panic("ClientMock.GetGitHubAccountFunc: method is nil but Client.GetGitHubAccount was just called")
	}
	callInfo := struct {
		ContextMoqParam         context.Context
		GetGitHubAccountRequest *xagentv1.GetGitHubAccountRequest
	}{
		ContextMoqParam:         contextMoqParam,
		GetGitHubAccountRequest: getGitHubAccountRequest,
	}
	mock.lockGetGitHubAccount.Lock()
	mock.calls.GetGitHubAccount = append(mock.calls.GetGitHubAccount, callInfo)
	mock.lockGetGitHubAccount.Unlock()
	return mock.GetGitHubAccountFunc(contextMoqParam, getGitHubAccountRequest)
}

// GetGitHubAccountCalls gets all the calls that were made to GetGitHubAccount.
// Check the length with:
//
//	len(mockedClient.GetGitHubAccountCalls())
func (mock *ClientMock) GetGitHubAccountCalls() []struct {
	ContextMoqParam         context.Context
	GetGitHubAccountRequest *xagentv1.GetGitHubAccountRequest
} {
	var calls []struct {
		ContextMoqParam         context.Context
		GetGitHubAccountRequest *xagentv1.GetGitHubAccountRequest
	}
	mock.lockGetGitHubAccount.RLock()
	calls = mock.calls.GetGitHubAccount
	mock.lockGetGitHubAccount.RUnlock()
	return calls
}

// GetProfile calls GetProfileFunc.
func (mock *ClientMock) GetProfile(contextMoqParam context.Context, getProfileRequest *xagentv1.GetProfileRequest) (*xagentv1.GetProfileResponse, error) {
	if mock.GetProfileFunc == nil {
		panic("ClientMock.GetProfileFunc: method is nil but Client.GetProfile was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		GetProfileRequest *xagentv1.GetProfileRequest
	}{
		ContextMoqParam:   contextMoqParam,
		GetProfileRequest: getProfileRequest,
	}
	mock.lockGetProfile.Lock()
	mock.calls.GetProfile = append(mock.calls.GetProfile, callInfo)
	mock.lockGetProfile.Unlock()
	return mock.GetProfileFunc(contextMoqParam, getProfileRequest)
}

// GetProfileCalls gets all the calls that were made to GetProfile.
// Check the length with:
//
//	len(mockedClient.GetProfileCalls())
func (mock *ClientMock) GetProfileCalls() []struct {
	ContextMoqParam   context.Context
	GetProfileRequest *xagentv1.GetProfileRequest
} {
	var calls []struct {
		ContextMoqParam   context.Context
		GetProfileRequest *xagentv1.GetProfileRequest
	}
	mock.lockGetProfile.RLock()
	calls = mock.calls.GetProfile
	mock.lockGetProfile.RUnlock()
	return calls
}

// GetTask calls GetTaskFunc.
func (mock *ClientMock) GetTask(contextMoqParam context.Context, getTaskRequest *xagentv1.GetTaskRequest) (*xagentv1.GetTaskResponse, error) {
	if mock.GetTaskFunc == nil {
		panic("ClientMock.GetTaskFunc: method is nil but Client.GetTask was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		GetTaskRequest  *xagentv1.GetTaskRequest
	}{
		ContextMoqParam: contextMoqParam,
		GetTaskRequest:  getTaskRequest,
	}
	mock.lockGetTask.Lock()
	mock.calls.GetTask = append(mock.calls.GetTask, callInfo)
	mock.lockGetTask.Unlock()
	return mock.GetTaskFunc(contextMoqParam, getTaskRequest)
}

// GetTaskCalls gets all the calls that were made to GetTask.
// Check the length with:
//
//	len(mockedClient.GetTaskCalls())
func (mock *ClientMock) GetTaskCalls() []struct {
	ContextMoqParam context.Context
	GetTaskRequest  *xagentv1.GetTaskRequest
} {
	var calls []struct {
		ContextMoqParam context.Context
		GetTaskRequest  *xagentv1.GetTaskRequest
	}
	mock.lockGetTask.RLock()
	calls = mock.calls.GetTask
	mock.lockGetTask.RUnlock()
	return calls
}

// GetTaskDetails calls GetTaskDetailsFunc.
func (mock *ClientMock) GetTaskDetails(contextMoqParam context.Context, getTaskDetailsRequest *xagentv1.GetTaskDetailsRequest) (*xagentv1.GetTaskDetailsResponse, error) {
	if mock.GetTaskDetailsFunc == nil {
		panic("ClientMock.GetTaskDetailsFunc: method is nil but Client.GetTaskDetails was just called")
	}
	callInfo := struct {
		ContextMoqParam       context.Context
		GetTaskDetailsRequest *xagentv1.GetTaskDetailsRequest
	}{
		ContextMoqParam:       contextMoqParam,
		GetTaskDetailsRequest: getTaskDetailsRequest,
	}
	mock.lockGetTaskDetails.Lock()
	mock.calls.GetTaskDetails = append(mock.calls.GetTaskDetails, callInfo)
	mock.lockGetTaskDetails.Unlock()
	return mock.GetTaskDetailsFunc(contextMoqParam, getTaskDetailsRequest)
}

// GetTaskDetailsCalls gets all the calls that were made to GetTaskDetails.
// Check the length with:
//
//	len(mockedClient.GetTaskDetailsCalls())
func (mock *ClientMock) GetTaskDetailsCalls() []struct {
	ContextMoqParam       context.Context
	GetTaskDetailsRequest *xagentv1.GetTaskDetailsRequest
} {
	var calls []struct {
		ContextMoqParam       context.Context
		GetTaskDetailsRequest *xagentv1.GetTaskDetailsRequest
	}
	mock.lockGetTaskDetails.RLock()
	calls = mock.calls.GetTaskDetails
	mock.lockGetTaskDetails.RUnlock()
	return calls
}

// ListChildTasks calls ListChildTasksFunc.
func (mock *ClientMock) ListChildTasks(contextMoqParam context.Context, listChildTasksRequest *xagentv1.ListChildTasksRequest) (*xagentv1.ListChildTasksResponse, error) {
	if mock.ListChildTasksFunc == nil {
		panic("ClientMock.ListChildTasksFunc: method is nil but Client.ListChildTasks was just called")
	}
	callInfo := struct {
		ContextMoqParam       context.Context
		ListChildTasksRequest *xagentv1.ListChildTasksRequest
	}{
		ContextMoqParam:       contextMoqParam,
		ListChildTasksRequest: listChildTasksRequest,
	}
	mock.lockListChildTasks.Lock()
	mock.calls.ListChildTasks = append(mock.calls.ListChildTasks, callInfo)
	mock.lockListChildTasks.Unlock()
	return mock.ListChildTasksFunc(contextMoqParam, listChildTasksRequest)
}

// ListChildTasksCalls gets all the calls that were made to ListChildTasks.
// Check the length with:
//
//	len(mockedClient.ListChildTasksCalls())
func (mock *ClientMock) ListChildTasksCalls() []struct {
	ContextMoqParam       context.Context
	ListChildTasksRequest *xagentv1.ListChildTasksRequest
} {
	var calls []struct {
		ContextMoqParam       context.Context
		ListChildTasksRequest *xagentv1.ListChildTasksRequest
	}
	mock.lockListChildTasks.RLock()
	calls = mock.calls.ListChildTasks
	mock.lockListChildTasks.RUnlock()
	return calls
}

// ListEventTasks calls ListEventTasksFunc.
func (mock *ClientMock) ListEventTasks(contextMoqParam context.Context, listEventTasksRequest *xagentv1.ListEventTasksRequest) (*xagentv1.ListEventTasksResponse, error) {
	if mock.ListEventTasksFunc == nil {
		panic("ClientMock.ListEventTasksFunc: method is nil but Client.ListEventTasks was just called")
	}
	callInfo := struct {
		ContextMoqParam       context.Context
		ListEventTasksRequest *xagentv1.ListEventTasksRequest
	}{
		ContextMoqParam:       contextMoqParam,
		ListEventTasksRequest: listEventTasksRequest,
	}
	mock.lockListEventTasks.Lock()
	mock.calls.ListEventTasks = append(mock.calls.ListEventTasks, callInfo)
	mock.lockListEventTasks.Unlock()
	return mock.ListEventTasksFunc(contextMoqParam, listEventTasksRequest)
}

// ListEventTasksCalls gets all the calls that were made to ListEventTasks.
// Check the length with:
//
//	len(mockedClient.ListEventTasksCalls())
func (mock *ClientMock) ListEventTasksCalls() []struct {
	ContextMoqParam       context.Context
	ListEventTasksRequest *xagentv1.ListEventTasksRequest
} {
	var calls []struct {
		ContextMoqParam       context.Context
		ListEventTasksRequest *xagentv1.ListEventTasksRequest
	}
	mock.lockListEventTasks.RLock()
	calls = mock.calls.ListEventTasks
	mock.lockListEventTasks.RUnlock()
	return calls
}

// ListEvents calls ListEventsFunc.
func (mock *ClientMock) ListEvents(contextMoqParam context.Context, listEventsRequest *xagentv1.ListEventsRequest) (*xagentv1.ListEventsResponse, error) {
	if mock.ListEventsFunc == nil {
		panic("ClientMock.ListEventsFunc: method is nil but Client.ListEvents was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		ListEventsRequest *xagentv1.ListEventsRequest
	}{
		ContextMoqParam:   contextMoqParam,
		ListEventsRequest: listEventsRequest,
	}
	mock.lockListEvents.Lock()
	mock.calls.ListEvents = append(mock.calls.ListEvents, callInfo)
	mock.lockListEvents.Unlock()
	return mock.ListEventsFunc(contextMoqParam, listEventsRequest)
}

// ListEventsCalls gets all the calls that were made to ListEvents.
// Check the length with:
//
//	len(mockedClient.ListEventsCalls())
func (mock *ClientMock) ListEventsCalls() []struct {
	ContextMoqParam   context.Context
	ListEventsRequest *xagentv1.ListEventsRequest
} {
	var calls []struct {
		ContextMoqParam   context.Context
		ListEventsRequest *xagentv1.ListEventsRequest
	}
	mock.lockListEvents.RLock()
	calls = mock.calls.ListEvents
	mock.lockListEvents.RUnlock()
	return calls
}

// ListEventsByTask calls ListEventsByTaskFunc.
func (mock *ClientMock) ListEventsByTask(contextMoqParam context.Context, listEventsByTaskRequest *xagentv1.ListEventsByTaskRequest) (*xagentv1.ListEventsByTaskResponse, error) {
	if mock.ListEventsByTaskFunc == nil {
		panic("ClientMock.ListEventsByTaskFunc: method is nil but Client.ListEventsByTask was just called")
	}
	callInfo := struct {
		ContextMoqParam         context.Context
		ListEventsByTaskRequest *xagentv1.ListEventsByTaskRequest
	}{
		ContextMoqParam:         contextMoqParam,
		ListEventsByTaskRequest: listEventsByTaskRequest,
	}
	mock.lockListEventsByTask.Lock()
	mock.calls.ListEventsByTask = append(mock.calls.ListEventsByTask, callInfo)
	mock.lockListEventsByTask.Unlock()
	return mock.ListEventsByTaskFunc(contextMoqParam, listEventsByTaskRequest)
}

// ListEventsByTaskCalls gets all the calls that were made to ListEventsByTask.
// Check the length with:
//
//	len(mockedClient.ListEventsByTaskCalls())
func (mock *ClientMock) ListEventsByTaskCalls() []struct {
	ContextMoqParam         context.Context
	ListEventsByTaskRequest *xagentv1.ListEventsByTaskRequest
} {
	var calls []struct {
		ContextMoqParam         context.Context
		ListEventsByTaskRequest *xagentv1.ListEventsByTaskRequest
	}
	mock.lockListEventsByTask.RLock()
	calls = mock.calls.ListEventsByTask
	mock.lockListEventsByTask.RUnlock()
	return calls
}

// ListKeys calls ListKeysFunc.
func (mock *ClientMock) ListKeys(contextMoqParam context.Context, listKeysRequest *xagentv1.ListKeysRequest) (*xagentv1.ListKeysResponse, error) {
	if mock.ListKeysFunc == nil {
		panic("ClientMock.ListKeysFunc: method is nil but Client.ListKeys was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		ListKeysRequest *xagentv1.ListKeysRequest
	}{
		ContextMoqParam: contextMoqParam,
		ListKeysRequest: listKeysRequest,
	}
	mock.lockListKeys.Lock()
	mock.calls.ListKeys = append(mock.calls.ListKeys, callInfo)
	mock.lockListKeys.Unlock()
	return mock.ListKeysFunc(contextMoqParam, listKeysRequest)
}

// ListKeysCalls gets all the calls that were made to ListKeys.
// Check the length with:
//
//	len(mockedClient.ListKeysCalls())
func (mock *ClientMock) ListKeysCalls() []struct {
	ContextMoqParam context.Context
	ListKeysRequest *xagentv1.ListKeysRequest
} {
	var calls []struct {
		ContextMoqParam context.Context
		ListKeysRequest *xagentv1.ListKeysRequest
	}
	mock.lockListKeys.RLock()
	calls = mock.calls.ListKeys
	mock.lockListKeys.RUnlock()
	return calls
}

// ListLinks calls ListLinksFunc.
func (mock *ClientMock) ListLinks(contextMoqParam context.Context, listLinksRequest *xagentv1.ListLinksRequest) (*xagentv1.ListLinksResponse, error) {
	if mock.ListLinksFunc == nil {
		panic("ClientMock.ListLinksFunc: method is nil but Client.ListLinks was just called")
	}
	callInfo := struct {
		ContextMoqParam  context.Context
		ListLinksRequest *xagentv1.ListLinksRequest
	}{
		ContextMoqParam:  contextMoqParam,
		ListLinksRequest: listLinksRequest,
	}
	mock.lockListLinks.Lock()
	mock.calls.ListLinks = append(mock.calls.ListLinks, callInfo)
	mock.lockListLinks.Unlock()
	return mock.ListLinksFunc(contextMoqParam, listLinksRequest)
}

// ListLinksCalls gets all the calls that were made to ListLinks.
// Check the length with:
//
//	len(mockedClient.ListLinksCalls())
func (mock *ClientMock) ListLinksCalls() []struct {
	ContextMoqParam  context.Context
	ListLinksRequest *xagentv1.ListLinksRequest
} {
	var calls []struct {
		ContextMoqParam  context.Context
		ListLinksRequest *xagentv1.ListLinksRequest
	}
	mock.lockListLinks.RLock()
	calls = mock.calls.ListLinks
	mock.lockListLinks.RUnlock()
	return calls
}

// ListLogs calls ListLogsFunc.
func (mock *ClientMock) ListLogs(contextMoqParam context.Context, listLogsRequest *xagentv1.ListLogsRequest) (*xagentv1.ListLogsResponse, error) {
	if mock.ListLogsFunc == nil {
		panic("ClientMock.ListLogsFunc: method is nil but Client.ListLogs was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		ListLogsRequest *xagentv1.ListLogsRequest
	}{
		ContextMoqParam: contextMoqParam,
		ListLogsRequest: listLogsRequest,
	}
	mock.lockListLogs.Lock()
	mock.calls.ListLogs = append(mock.calls.ListLogs, callInfo)
	mock.lockListLogs.Unlock()
	return mock.ListLogsFunc(contextMoqParam, listLogsRequest)
}

// ListLogsCalls gets all the calls that were made to ListLogs.
// Check the length with:
//
//	len(mockedClient.ListLogsCalls())
func (mock *ClientMock) ListLogsCalls() []struct {
	ContextMoqParam context.Context
	ListLogsRequest *xagentv1.ListLogsRequest
} {
	var calls []struct {
		ContextMoqParam context.Context
		ListLogsRequest *xagentv1.ListLogsRequest
	}
	mock.lockListLogs.RLock()
	calls = mock.calls.ListLogs
	mock.lockListLogs.RUnlock()
	return calls
}

// ListRunnerTasks calls ListRunnerTasksFunc.
func (mock *ClientMock) ListRunnerTasks(contextMoqParam context.Context, listRunnerTasksRequest *xagentv1.ListRunnerTasksRequest) (*xagentv1.ListRunnerTasksResponse, error) {
	if mock.ListRunnerTasksFunc == nil {
		panic("ClientMock.ListRunnerTasksFunc: method is nil but Client.ListRunnerTasks was just called")
	}
	callInfo := struct {
		ContextMoqParam        context.Context
		ListRunnerTasksRequest *xagentv1.ListRunnerTasksRequest
	}{
		ContextMoqParam:        contextMoqParam,
		ListRunnerTasksRequest: listRunnerTasksRequest,
	}
	mock.lockListRunnerTasks.Lock()
	mock.calls.ListRunnerTasks = append(mock.calls.ListRunnerTasks, callInfo)
	mock.lockListRunnerTasks.Unlock()
	return mock.ListRunnerTasksFunc(contextMoqParam, listRunnerTasksRequest)
}

// ListRunnerTasksCalls gets all the calls that were made to ListRunnerTasks.
// Check the length with:
//
//	len(mockedClient.ListRunnerTasksCalls())
func (mock *ClientMock) ListRunnerTasksCalls() []struct {
	ContextMoqParam        context.Context
	ListRunnerTasksRequest *xagentv1.ListRunnerTasksRequest
} {
	var calls []struct {
		ContextMoqParam        context.Context
		ListRunnerTasksRequest *xagentv1.ListRunnerTasksRequest
	}
	mock.lockListRunnerTasks.RLock()
	calls = mock.calls.ListRunnerTasks
	mock.lockListRunnerTasks.RUnlock()
	return calls
}

// ListTasks calls ListTasksFunc.
func (mock *ClientMock) ListTasks(contextMoqParam context.Context, listTasksRequest *xagentv1.ListTasksRequest) (*xagentv1.ListTasksResponse, error) {
	if mock.ListTasksFunc == nil {
		panic("ClientMock.ListTasksFunc: method is nil but Client.ListTasks was just called")
	}
	callInfo := struct {
		ContextMoqParam  context.Context
		ListTasksRequest *xagentv1.ListTasksRequest
	}{
		ContextMoqParam:  contextMoqParam,
		ListTasksRequest: listTasksRequest,
	}
	mock.lockListTasks.Lock()
	mock.calls.ListTasks = append(mock.calls.ListTasks, callInfo)
	mock.lockListTasks.Unlock()
	return mock.ListTasksFunc(contextMoqParam, listTasksRequest)
}

// ListTasksCalls gets all the calls that were made to ListTasks.
// Check the length with:
//
//	len(mockedClient.ListTasksCalls())
func (mock *ClientMock) ListTasksCalls() []struct {
	ContextMoqParam  context.Context
	ListTasksRequest *xagentv1.ListTasksRequest
} {
	var calls []struct {
		ContextMoqParam  context.Context
		ListTasksRequest *xagentv1.ListTasksRequest
	}
	mock.lockListTasks.RLock()
	calls = mock.calls.ListTasks
	mock.lockListTasks.RUnlock()
	return calls
}

// ListWorkspaces calls ListWorkspacesFunc.
func (mock *ClientMock) ListWorkspaces(contextMoqParam context.Context, listWorkspacesRequest *xagentv1.ListWorkspacesRequest) (*xagentv1.ListWorkspacesResponse, error) {
	if mock.ListWorkspacesFunc == nil {
		panic("ClientMock.ListWorkspacesFunc: method is nil but Client.ListWorkspaces was just called")
	}
	callInfo := struct {
		ContextMoqParam       context.Context
		ListWorkspacesRequest *xagentv1.ListWorkspacesRequest
	}{
		ContextMoqParam:       contextMoqParam,
		ListWorkspacesRequest: listWorkspacesRequest,
	}
	mock.lockListWorkspaces.Lock()
	mock.calls.ListWorkspaces = append(mock.calls.ListWorkspaces, callInfo)
	mock.lockListWorkspaces.Unlock()
	return mock.ListWorkspacesFunc(contextMoqParam, listWorkspacesRequest)
}

// ListWorkspacesCalls gets all the calls that were made to ListWorkspaces.
// Check the length with:
//
//	len(mockedClient.ListWorkspacesCalls())
func (mock *ClientMock) ListWorkspacesCalls() []struct {
	ContextMoqParam       context.Context
	ListWorkspacesRequest *xagentv1.ListWorkspacesRequest
} {
	var calls []struct {
		ContextMoqParam       context.Context
		ListWorkspacesRequest *xagentv1.ListWorkspacesRequest
	}
	mock.lockListWorkspaces.RLock()
	calls = mock.calls.ListWorkspaces
	mock.lockListWorkspaces.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *ClientMock) Ping(contextMoqParam context.Context, pingRequest *xagentv1.PingRequest) (*xagentv1.PingResponse, error) {
	if mock.PingFunc == nil {
		panic("ClientMock.PingFunc: method is nil but Client.Ping was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PingRequest     *xagentv1.PingRequest
	}{
		ContextMoqParam: contextMoqParam,
		PingRequest:     pingRequest,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(contextMoqParam, pingRequest)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedClient.PingCalls())
func (mock *ClientMock) PingCalls() []struct {
	ContextMoqParam context.Context
	PingRequest     *xagentv1.PingRequest
} {
	var calls []struct {
		ContextMoqParam context.Context
		PingRequest     *xagentv1.PingRequest
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// ProcessEvent calls ProcessEventFunc.
func (mock *ClientMock) ProcessEvent(contextMoqParam context.Context, processEventRequest *xagentv1.ProcessEventRequest) (*xagentv1.ProcessEventResponse, error) {
	if mock.ProcessEventFunc == nil {
		panic("ClientMock.ProcessEventFunc: method is nil but Client.ProcessEvent was just called")
	}
	callInfo := struct {
		ContextMoqParam     context.Context
		ProcessEventRequest *xagentv1.ProcessEventRequest
	}{
		ContextMoqParam:     contextMoqParam,
		ProcessEventRequest: processEventRequest,
	}
	mock.lockProcessEvent.Lock()
	mock.calls.ProcessEvent = append(mock.calls.ProcessEvent, callInfo)
	mock.lockProcessEvent.Unlock()
	return mock.ProcessEventFunc(contextMoqParam, processEventRequest)
}

// ProcessEventCalls gets all the calls that were made to ProcessEvent.
// Check the length with:
//
//	len(mockedClient.ProcessEventCalls())
func (mock *ClientMock) ProcessEventCalls() []struct {
	ContextMoqParam     context.Context
	ProcessEventRequest *xagentv1.ProcessEventRequest
} {
	var calls []struct {
		ContextMoqParam     context.Context
		ProcessEventRequest *xagentv1.ProcessEventRequest
	}
	mock.lockProcessEvent.RLock()
	calls = mock.calls.ProcessEvent
	mock.lockProcessEvent.RUnlock()
	return calls
}

// RegisterWorkspaces calls RegisterWorkspacesFunc.
func (mock *ClientMock) RegisterWorkspaces(contextMoqParam context.Context, registerWorkspacesRequest *xagentv1.RegisterWorkspacesRequest) (*xagentv1.RegisterWorkspacesResponse, error) {
	if mock.RegisterWorkspacesFunc == nil {
		panic("ClientMock.RegisterWorkspacesFunc: method is nil but Client.RegisterWorkspaces was just called")
	}
	callInfo := struct {
		ContextMoqParam           context.Context
		RegisterWorkspacesRequest *xagentv1.RegisterWorkspacesRequest
	}{
		ContextMoqParam:           contextMoqParam,
		RegisterWorkspacesRequest: registerWorkspacesRequest,
	}
	mock.lockRegisterWorkspaces.Lock()
	mock.calls.RegisterWorkspaces = append(mock.calls.RegisterWorkspaces, callInfo)
	mock.lockRegisterWorkspaces.Unlock()
	return mock.RegisterWorkspacesFunc(contextMoqParam, registerWorkspacesRequest)
}

// RegisterWorkspacesCalls gets all the calls that were made to RegisterWorkspaces.
// Check the length with:
//
//	len(mockedClient.RegisterWorkspacesCalls())
func (mock *ClientMock) RegisterWorkspacesCalls() []struct {
	ContextMoqParam           context.Context
	RegisterWorkspacesRequest *xagentv1.RegisterWorkspacesRequest
} {
	var calls []struct {
		ContextMoqParam           context.Context
		RegisterWorkspacesRequest *xagentv1.RegisterWorkspacesRequest
	}
	mock.lockRegisterWorkspaces.RLock()
	calls = mock.calls.RegisterWorkspaces
	mock.lockRegisterWorkspaces.RUnlock()
	return calls
}

// RemoveEventTask calls RemoveEventTaskFunc.
func (mock *ClientMock) RemoveEventTask(contextMoqParam context.Context, removeEventTaskRequest *xagentv1.RemoveEventTaskRequest) (*xagentv1.RemoveEventTaskResponse, error) {
	if mock.RemoveEventTaskFunc == nil {
		panic("ClientMock.RemoveEventTaskFunc: method is nil but Client.RemoveEventTask was just called")
	}
	callInfo := struct {
		ContextMoqParam        context.Context
		RemoveEventTaskRequest *xagentv1.RemoveEventTaskRequest
	}{
		ContextMoqParam:        contextMoqParam,
		RemoveEventTaskRequest: removeEventTaskRequest,
	}
	mock.lockRemoveEventTask.Lock()
	mock.calls.RemoveEventTask = append(mock.calls.RemoveEventTask, callInfo)
	mock.lockRemoveEventTask.Unlock()
	return mock.RemoveEventTaskFunc(contextMoqParam, removeEventTaskRequest)
}

// RemoveEventTaskCalls gets all the calls that were made to RemoveEventTask.
// Check the length with:
//
//	len(mockedClient.RemoveEventTaskCalls())
func (mock *ClientMock) RemoveEventTaskCalls() []struct {
	ContextMoqParam        context.Context
	RemoveEventTaskRequest *xagentv1.RemoveEventTaskRequest
} {
	var calls []struct {
		ContextMoqParam        context.Context
		RemoveEventTaskRequest *xagentv1.RemoveEventTaskRequest
	}
	mock.lockRemoveEventTask.RLock()
	calls = mock.calls.RemoveEventTask
	mock.lockRemoveEventTask.RUnlock()
	return calls
}

// RestartTask calls RestartTaskFunc.
func (mock *ClientMock) RestartTask(contextMoqParam context.Context, restartTaskRequest *xagentv1.RestartTaskRequest) (*xagentv1.RestartTaskResponse, error) {
	if mock.RestartTaskFunc == nil {
		panic("ClientMock.RestartTaskFunc: method is nil but Client.RestartTask was just called")
	}
	callInfo := struct {
		ContextMoqParam    context.Context
		RestartTaskRequest *xagentv1.RestartTaskRequest
	}{
		ContextMoqParam:    contextMoqParam,
		RestartTaskRequest: restartTaskRequest,
	}
	mock.lockRestartTask.Lock()
	mock.calls.RestartTask = append(mock.calls.RestartTask, callInfo)
	mock.lockRestartTask.Unlock()
	return mock.RestartTaskFunc(contextMoqParam, restartTaskRequest)
}

// RestartTaskCalls gets all the calls that were made to RestartTask.
// Check the length with:
//
//	len(mockedClient.RestartTaskCalls())
func (mock *ClientMock) RestartTaskCalls() []struct {
	ContextMoqParam    context.Context
	RestartTaskRequest *xagentv1.RestartTaskRequest
} {
	var calls []struct {
		ContextMoqParam    context.Context
		RestartTaskRequest *xagentv1.RestartTaskRequest
	}
	mock.lockRestartTask.RLock()
	calls = mock.calls.RestartTask
	mock.lockRestartTask.RUnlock()
	return calls
}

// SubmitRunnerEvents calls SubmitRunnerEventsFunc.
func (mock *ClientMock) SubmitRunnerEvents(contextMoqParam context.Context, submitRunnerEventsRequest *xagentv1.SubmitRunnerEventsRequest) (*xagentv1.SubmitRunnerEventsResponse, error) {
	if mock.SubmitRunnerEventsFunc == nil {
		panic("ClientMock.SubmitRunnerEventsFunc: method is nil but Client.SubmitRunnerEvents was just called")
	}
	callInfo := struct {
		ContextMoqParam           context.Context
		SubmitRunnerEventsRequest *xagentv1.SubmitRunnerEventsRequest
	}{
		ContextMoqParam:           contextMoqParam,
		SubmitRunnerEventsRequest: submitRunnerEventsRequest,
	}
	mock.lockSubmitRunnerEvents.Lock()
	mock.calls.SubmitRunnerEvents = append(mock.calls.SubmitRunnerEvents, callInfo)
	mock.lockSubmitRunnerEvents.Unlock()
	return mock.SubmitRunnerEventsFunc(contextMoqParam, submitRunnerEventsRequest)
}

// SubmitRunnerEventsCalls gets all the calls that were made to SubmitRunnerEvents.
// Check the length with:
//
//	len(mockedClient.SubmitRunnerEventsCalls())
func (mock *ClientMock) SubmitRunnerEventsCalls() []struct {
	ContextMoqParam           context.Context
	SubmitRunnerEventsRequest *xagentv1.SubmitRunnerEventsRequest
} {
	var calls []struct {
		ContextMoqParam           context.Context
		SubmitRunnerEventsRequest *xagentv1.SubmitRunnerEventsRequest
	}
	mock.lockSubmitRunnerEvents.RLock()
	calls = mock.calls.SubmitRunnerEvents
	mock.lockSubmitRunnerEvents.RUnlock()
	return calls
}

// UnarchiveTask calls UnarchiveTaskFunc.
func (mock *ClientMock) UnarchiveTask(contextMoqParam context.Context, unarchiveTaskRequest *xagentv1.UnarchiveTaskRequest) (*xagentv1.UnarchiveTaskResponse, error) {
	if mock.UnarchiveTaskFunc == nil {
		panic("ClientMock.UnarchiveTaskFunc: method is nil but Client.UnarchiveTask was just called")
	}
	callInfo := struct {
		ContextMoqParam      context.Context
		UnarchiveTaskRequest *xagentv1.UnarchiveTaskRequest
	}{
		ContextMoqParam:      contextMoqParam,
		UnarchiveTaskRequest: unarchiveTaskRequest,
	}
	mock.lockUnarchiveTask.Lock()
	mock.calls.UnarchiveTask = append(mock.calls.UnarchiveTask, callInfo)
	mock.lockUnarchiveTask.Unlock()
	return mock.UnarchiveTaskFunc(contextMoqParam, unarchiveTaskRequest)
}

// UnarchiveTaskCalls gets all the calls that were made to UnarchiveTask.
// Check the length with:
//
//	len(mockedClient.UnarchiveTaskCalls())
func (mock *ClientMock) UnarchiveTaskCalls() []struct {
	ContextMoqParam      context.Context
	UnarchiveTaskRequest *xagentv1.UnarchiveTaskRequest
} {
	var calls []struct {
		ContextMoqParam      context.Context
		UnarchiveTaskRequest *xagentv1.UnarchiveTaskRequest
	}
	mock.lockUnarchiveTask.RLock()
	calls = mock.calls.UnarchiveTask
	mock.lockUnarchiveTask.RUnlock()
	return calls
}

// UnlinkGitHubAccount calls UnlinkGitHubAccountFunc.
func (mock *ClientMock) UnlinkGitHubAccount(contextMoqParam context.Context, unlinkGitHubAccountRequest *xagentv1.UnlinkGitHubAccountRequest) (*xagentv1.UnlinkGitHubAccountResponse, error) {
	if mock.UnlinkGitHubAccountFunc == nil {
		panic("ClientMock.UnlinkGitHubAccountFunc: method is nil but Client.UnlinkGitHubAccount was just called")
	}
	callInfo := struct {
		ContextMoqParam            context.Context
		UnlinkGitHubAccountRequest *xagentv1.UnlinkGitHubAccountRequest
	}{
		ContextMoqParam:            contextMoqParam,
		UnlinkGitHubAccountRequest: unlinkGitHubAccountRequest,
	}
	mock.lockUnlinkGitHubAccount.Lock()
	mock.calls.UnlinkGitHubAccount = append(mock.calls.UnlinkGitHubAccount, callInfo)
	mock.lockUnlinkGitHubAccount.Unlock()
	return mock.UnlinkGitHubAccountFunc(contextMoqParam, unlinkGitHubAccountRequest)
}

// UnlinkGitHubAccountCalls gets all the calls that were made to UnlinkGitHubAccount.
// Check the length with:
//
//	len(mockedClient.UnlinkGitHubAccountCalls())
func (mock *ClientMock) UnlinkGitHubAccountCalls() []struct {
	ContextMoqParam            context.Context
	UnlinkGitHubAccountRequest *xagentv1.UnlinkGitHubAccountRequest
} {
	var calls []struct {
		ContextMoqParam            context.Context
		UnlinkGitHubAccountRequest *xagentv1.UnlinkGitHubAccountRequest
	}
	mock.lockUnlinkGitHubAccount.RLock()
	calls = mock.calls.UnlinkGitHubAccount
	mock.lockUnlinkGitHubAccount.RUnlock()
	return calls
}

// UpdateTask calls UpdateTaskFunc.
func (mock *ClientMock) UpdateTask(contextMoqParam context.Context, updateTaskRequest *xagentv1.UpdateTaskRequest) (*xagentv1.UpdateTaskResponse, error) {
	if mock.UpdateTaskFunc == nil {
		panic("ClientMock.UpdateTaskFunc: method is nil but Client.UpdateTask was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		UpdateTaskRequest *xagentv1.UpdateTaskRequest
	}{
		ContextMoqParam:   contextMoqParam,
		UpdateTaskRequest: updateTaskRequest,
	}
	mock.lockUpdateTask.Lock()
	mock.calls.UpdateTask = append(mock.calls.UpdateTask, callInfo)
	mock.lockUpdateTask.Unlock()
	return mock.UpdateTaskFunc(contextMoqParam, updateTaskRequest)
}

// UpdateTaskCalls gets all the calls that were made to UpdateTask.
// Check the length with:
//
//	len(mockedClient.UpdateTaskCalls())
func (mock *ClientMock) UpdateTaskCalls() []struct {
	ContextMoqParam   context.Context
	UpdateTaskRequest *xagentv1.UpdateTaskRequest
} {
	var calls []struct {
		ContextMoqParam   context.Context
		UpdateTaskRequest *xagentv1.UpdateTaskRequest
	}
	mock.lockUpdateTask.RLock()
	calls = mock.calls.UpdateTask
	mock.lockUpdateTask.RUnlock()
	return calls
}

// UploadLogs calls UploadLogsFunc.
func (mock *ClientMock) UploadLogs(contextMoqParam context.Context, uploadLogsRequest *xagentv1.UploadLogsRequest) (*xagentv1.UploadLogsResponse, error) {
	if mock.UploadLogsFunc == nil {
		panic("ClientMock.UploadLogsFunc: method is nil but Client.UploadLogs was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		UploadLogsRequest *xagentv1.UploadLogsRequest
	}{
		ContextMoqParam:   contextMoqParam,
		UploadLogsRequest: uploadLogsRequest,
	}
	mock.lockUploadLogs.Lock()
	mock.calls.UploadLogs = append(mock.calls.UploadLogs, callInfo)
	mock.lockUploadLogs.Unlock()
	return mock.UploadLogsFunc(contextMoqParam, uploadLogsRequest)
}

// UploadLogsCalls gets all the calls that were made to UploadLogs.
// Check the length with:
//
//	len(mockedClient.UploadLogsCalls())
func (mock *ClientMock) UploadLogsCalls() []struct {
	ContextMoqParam   context.Context
	UploadLogsRequest *xagentv1.UploadLogsRequest
} {
	var calls []struct {
		ContextMoqParam   context.Context
		UploadLogsRequest *xagentv1.UploadLogsRequest
	}
	mock.lockUploadLogs.RLock()
	calls = mock.calls.UploadLogs
	mock.lockUploadLogs.RUnlock()
	return calls
}
