// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package pagination

import (
	"context"
	"sync"
)

// Ensure, that SourceMock does implement Source.
// If this is not the case, regenerate this file with moq.
var _ Source[any, any] = &SourceMock[any, any]{}

// SourceMock is a mock implementation of Source.
//
//	func TestSomethingThatUsesSource(t *testing.T) {
//
//		// make and configure a mocked Source
//		mockedSource := &SourceMock{
//			CursorFunc: func(row T) C {
//				panic("mock out the Cursor method")
//			},
//			QueryFunc: func(ctx context.Context, token Token[C], limit int) ([]T, error) {
//				panic("mock out the Query method")
//			},
//		}
//
//		// use mockedSource in code that requires Source
//		// and then make assertions.
//
//	}
type SourceMock[T any, C any] struct {
	// CursorFunc mocks the Cursor method.
	CursorFunc func(row T) C

	// QueryFunc mocks the Query method.
	QueryFunc func(ctx context.Context, token Token[C], limit int) ([]T, error)

	// calls tracks calls to the methods.
	calls struct {
		// Cursor holds details about calls to the Cursor method.
		Cursor []struct {
			// Row is the row argument value.
			Row T
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token Token[C]
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockCursor sync.RWMutex
	lockQuery  sync.RWMutex
}

// Cursor calls CursorFunc.
func (mock *SourceMock[T, C]) Cursor(row T) C {
	if mock.CursorFunc == nil {
		panic("SourceMock.CursorFunc: method is nil but Source.Cursor was just called")
	}
	callInfo := struct {
		Row T
	}{
		Row: row,
	}
	mock.lockCursor.Lock()
	mock.calls.Cursor = append(mock.calls.Cursor, callInfo)
	mock.lockCursor.Unlock()
	return mock.CursorFunc(row)
}

// CursorCalls gets all the calls that were made to Cursor.
// Check the length with:
//
//	len(mockedSource.CursorCalls())
func (mock *SourceMock[T, C]) CursorCalls() []struct {
	Row T
} {
	var calls []struct {
		Row T
	}
	mock.lockCursor.RLock()
	calls = mock.calls.Cursor
	mock.lockCursor.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *SourceMock[T, C]) Query(ctx context.Context, token Token[C], limit int) ([]T, error) {
	if mock.QueryFunc == nil {
		panic("SourceMock.QueryFunc: method is nil but Source.Query was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token Token[C]
		Limit int
	}{
		Ctx:   ctx,
		Token: token,
		Limit: limit,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(ctx, token, limit)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedSource.QueryCalls())
func (mock *SourceMock[T, C]) QueryCalls() []struct {
	Ctx   context.Context
	Token Token[C]
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Token Token[C]
		Limit int
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}
