workspaces:
  dummy:
    description: Dummy workspace for testing
    container:
      image: xagent-sysbox-workspace
      runtime: sysbox-runc
      networks:
        - runner_default
      environment:
        REGISTRY_MIRROR: http://registry:5000
    agent:
      type: dummy
