// Code generated by "stringer -type=TaskCommand -trimprefix=TaskCommand"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TaskCommandNone-0]
	_ = x[TaskCommandRestart-1]
	_ = x[TaskCommandStop-2]
	_ = x[TaskCommandStart-3]
}

const _TaskCommand_name = "NoneRestartStopStart"

var _TaskCommand_index = [...]uint8{0, 4, 11, 15, 20}

func (i TaskCommand) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TaskCommand_index)-1 {
		return "TaskCommand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskCommand_name[_TaskCommand_index[idx]:_TaskCommand_index[idx+1]]
}
