// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: xagent/v1/xagent.proto

package xagentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/icholy/xagent/internal/proto/xagent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// XAgentServiceName is the fully-qualified name of the XAgentService service.
	XAgentServiceName = "xagent.v1.XAgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// XAgentServiceListTasksProcedure is the fully-qualified name of the XAgentService's ListTasks RPC.
	XAgentServiceListTasksProcedure = "/xagent.v1.XAgentService/ListTasks"
	// XAgentServiceListChildTasksProcedure is the fully-qualified name of the XAgentService's
	// ListChildTasks RPC.
	XAgentServiceListChildTasksProcedure = "/xagent.v1.XAgentService/ListChildTasks"
	// XAgentServiceCreateTaskProcedure is the fully-qualified name of the XAgentService's CreateTask
	// RPC.
	XAgentServiceCreateTaskProcedure = "/xagent.v1.XAgentService/CreateTask"
	// XAgentServiceGetTaskProcedure is the fully-qualified name of the XAgentService's GetTask RPC.
	XAgentServiceGetTaskProcedure = "/xagent.v1.XAgentService/GetTask"
	// XAgentServiceGetTaskDetailsProcedure is the fully-qualified name of the XAgentService's
	// GetTaskDetails RPC.
	XAgentServiceGetTaskDetailsProcedure = "/xagent.v1.XAgentService/GetTaskDetails"
	// XAgentServiceUpdateTaskProcedure is the fully-qualified name of the XAgentService's UpdateTask
	// RPC.
	XAgentServiceUpdateTaskProcedure = "/xagent.v1.XAgentService/UpdateTask"
	// XAgentServiceDeleteTaskProcedure is the fully-qualified name of the XAgentService's DeleteTask
	// RPC.
	XAgentServiceDeleteTaskProcedure = "/xagent.v1.XAgentService/DeleteTask"
	// XAgentServiceArchiveTaskProcedure is the fully-qualified name of the XAgentService's ArchiveTask
	// RPC.
	XAgentServiceArchiveTaskProcedure = "/xagent.v1.XAgentService/ArchiveTask"
	// XAgentServiceCancelTaskProcedure is the fully-qualified name of the XAgentService's CancelTask
	// RPC.
	XAgentServiceCancelTaskProcedure = "/xagent.v1.XAgentService/CancelTask"
	// XAgentServiceRestartTaskProcedure is the fully-qualified name of the XAgentService's RestartTask
	// RPC.
	XAgentServiceRestartTaskProcedure = "/xagent.v1.XAgentService/RestartTask"
	// XAgentServiceUploadLogsProcedure is the fully-qualified name of the XAgentService's UploadLogs
	// RPC.
	XAgentServiceUploadLogsProcedure = "/xagent.v1.XAgentService/UploadLogs"
	// XAgentServiceListLogsProcedure is the fully-qualified name of the XAgentService's ListLogs RPC.
	XAgentServiceListLogsProcedure = "/xagent.v1.XAgentService/ListLogs"
	// XAgentServiceCreateLinkProcedure is the fully-qualified name of the XAgentService's CreateLink
	// RPC.
	XAgentServiceCreateLinkProcedure = "/xagent.v1.XAgentService/CreateLink"
	// XAgentServiceListLinksProcedure is the fully-qualified name of the XAgentService's ListLinks RPC.
	XAgentServiceListLinksProcedure = "/xagent.v1.XAgentService/ListLinks"
	// XAgentServiceFindLinksByURLProcedure is the fully-qualified name of the XAgentService's
	// FindLinksByURL RPC.
	XAgentServiceFindLinksByURLProcedure = "/xagent.v1.XAgentService/FindLinksByURL"
	// XAgentServiceListEventsProcedure is the fully-qualified name of the XAgentService's ListEvents
	// RPC.
	XAgentServiceListEventsProcedure = "/xagent.v1.XAgentService/ListEvents"
	// XAgentServiceCreateEventProcedure is the fully-qualified name of the XAgentService's CreateEvent
	// RPC.
	XAgentServiceCreateEventProcedure = "/xagent.v1.XAgentService/CreateEvent"
	// XAgentServiceGetEventProcedure is the fully-qualified name of the XAgentService's GetEvent RPC.
	XAgentServiceGetEventProcedure = "/xagent.v1.XAgentService/GetEvent"
	// XAgentServiceDeleteEventProcedure is the fully-qualified name of the XAgentService's DeleteEvent
	// RPC.
	XAgentServiceDeleteEventProcedure = "/xagent.v1.XAgentService/DeleteEvent"
	// XAgentServiceAddEventTaskProcedure is the fully-qualified name of the XAgentService's
	// AddEventTask RPC.
	XAgentServiceAddEventTaskProcedure = "/xagent.v1.XAgentService/AddEventTask"
	// XAgentServiceRemoveEventTaskProcedure is the fully-qualified name of the XAgentService's
	// RemoveEventTask RPC.
	XAgentServiceRemoveEventTaskProcedure = "/xagent.v1.XAgentService/RemoveEventTask"
	// XAgentServiceListEventTasksProcedure is the fully-qualified name of the XAgentService's
	// ListEventTasks RPC.
	XAgentServiceListEventTasksProcedure = "/xagent.v1.XAgentService/ListEventTasks"
	// XAgentServiceListEventsByTaskProcedure is the fully-qualified name of the XAgentService's
	// ListEventsByTask RPC.
	XAgentServiceListEventsByTaskProcedure = "/xagent.v1.XAgentService/ListEventsByTask"
	// XAgentServiceProcessEventProcedure is the fully-qualified name of the XAgentService's
	// ProcessEvent RPC.
	XAgentServiceProcessEventProcedure = "/xagent.v1.XAgentService/ProcessEvent"
	// XAgentServiceSubmitRunnerEventsProcedure is the fully-qualified name of the XAgentService's
	// SubmitRunnerEvents RPC.
	XAgentServiceSubmitRunnerEventsProcedure = "/xagent.v1.XAgentService/SubmitRunnerEvents"
)

// XAgentServiceClient is a client for the xagent.v1.XAgentService service.
type XAgentServiceClient interface {
	ListTasks(context.Context, *v1.ListTasksRequest) (*v1.ListTasksResponse, error)
	ListChildTasks(context.Context, *v1.ListChildTasksRequest) (*v1.ListChildTasksResponse, error)
	CreateTask(context.Context, *v1.CreateTaskRequest) (*v1.CreateTaskResponse, error)
	GetTask(context.Context, *v1.GetTaskRequest) (*v1.GetTaskResponse, error)
	GetTaskDetails(context.Context, *v1.GetTaskDetailsRequest) (*v1.GetTaskDetailsResponse, error)
	UpdateTask(context.Context, *v1.UpdateTaskRequest) (*v1.UpdateTaskResponse, error)
	DeleteTask(context.Context, *v1.DeleteTaskRequest) (*v1.DeleteTaskResponse, error)
	ArchiveTask(context.Context, *v1.ArchiveTaskRequest) (*v1.ArchiveTaskResponse, error)
	CancelTask(context.Context, *v1.CancelTaskRequest) (*v1.CancelTaskResponse, error)
	RestartTask(context.Context, *v1.RestartTaskRequest) (*v1.RestartTaskResponse, error)
	UploadLogs(context.Context, *v1.UploadLogsRequest) (*v1.UploadLogsResponse, error)
	ListLogs(context.Context, *v1.ListLogsRequest) (*v1.ListLogsResponse, error)
	CreateLink(context.Context, *v1.CreateLinkRequest) (*v1.CreateLinkResponse, error)
	ListLinks(context.Context, *v1.ListLinksRequest) (*v1.ListLinksResponse, error)
	FindLinksByURL(context.Context, *v1.FindLinksByURLRequest) (*v1.FindLinksByURLResponse, error)
	ListEvents(context.Context, *v1.ListEventsRequest) (*v1.ListEventsResponse, error)
	CreateEvent(context.Context, *v1.CreateEventRequest) (*v1.CreateEventResponse, error)
	GetEvent(context.Context, *v1.GetEventRequest) (*v1.GetEventResponse, error)
	DeleteEvent(context.Context, *v1.DeleteEventRequest) (*v1.DeleteEventResponse, error)
	AddEventTask(context.Context, *v1.AddEventTaskRequest) (*v1.AddEventTaskResponse, error)
	RemoveEventTask(context.Context, *v1.RemoveEventTaskRequest) (*v1.RemoveEventTaskResponse, error)
	ListEventTasks(context.Context, *v1.ListEventTasksRequest) (*v1.ListEventTasksResponse, error)
	ListEventsByTask(context.Context, *v1.ListEventsByTaskRequest) (*v1.ListEventsByTaskResponse, error)
	ProcessEvent(context.Context, *v1.ProcessEventRequest) (*v1.ProcessEventResponse, error)
	SubmitRunnerEvents(context.Context, *v1.SubmitRunnerEventsRequest) (*v1.SubmitRunnerEventsResponse, error)
}

// NewXAgentServiceClient constructs a client for the xagent.v1.XAgentService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewXAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) XAgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	xAgentServiceMethods := v1.File_xagent_v1_xagent_proto.Services().ByName("XAgentService").Methods()
	return &xAgentServiceClient{
		listTasks: connect.NewClient[v1.ListTasksRequest, v1.ListTasksResponse](
			httpClient,
			baseURL+XAgentServiceListTasksProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("ListTasks")),
			connect.WithClientOptions(opts...),
		),
		listChildTasks: connect.NewClient[v1.ListChildTasksRequest, v1.ListChildTasksResponse](
			httpClient,
			baseURL+XAgentServiceListChildTasksProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("ListChildTasks")),
			connect.WithClientOptions(opts...),
		),
		createTask: connect.NewClient[v1.CreateTaskRequest, v1.CreateTaskResponse](
			httpClient,
			baseURL+XAgentServiceCreateTaskProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("CreateTask")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[v1.GetTaskRequest, v1.GetTaskResponse](
			httpClient,
			baseURL+XAgentServiceGetTaskProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
		getTaskDetails: connect.NewClient[v1.GetTaskDetailsRequest, v1.GetTaskDetailsResponse](
			httpClient,
			baseURL+XAgentServiceGetTaskDetailsProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("GetTaskDetails")),
			connect.WithClientOptions(opts...),
		),
		updateTask: connect.NewClient[v1.UpdateTaskRequest, v1.UpdateTaskResponse](
			httpClient,
			baseURL+XAgentServiceUpdateTaskProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("UpdateTask")),
			connect.WithClientOptions(opts...),
		),
		deleteTask: connect.NewClient[v1.DeleteTaskRequest, v1.DeleteTaskResponse](
			httpClient,
			baseURL+XAgentServiceDeleteTaskProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("DeleteTask")),
			connect.WithClientOptions(opts...),
		),
		archiveTask: connect.NewClient[v1.ArchiveTaskRequest, v1.ArchiveTaskResponse](
			httpClient,
			baseURL+XAgentServiceArchiveTaskProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("ArchiveTask")),
			connect.WithClientOptions(opts...),
		),
		cancelTask: connect.NewClient[v1.CancelTaskRequest, v1.CancelTaskResponse](
			httpClient,
			baseURL+XAgentServiceCancelTaskProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("CancelTask")),
			connect.WithClientOptions(opts...),
		),
		restartTask: connect.NewClient[v1.RestartTaskRequest, v1.RestartTaskResponse](
			httpClient,
			baseURL+XAgentServiceRestartTaskProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("RestartTask")),
			connect.WithClientOptions(opts...),
		),
		uploadLogs: connect.NewClient[v1.UploadLogsRequest, v1.UploadLogsResponse](
			httpClient,
			baseURL+XAgentServiceUploadLogsProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("UploadLogs")),
			connect.WithClientOptions(opts...),
		),
		listLogs: connect.NewClient[v1.ListLogsRequest, v1.ListLogsResponse](
			httpClient,
			baseURL+XAgentServiceListLogsProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("ListLogs")),
			connect.WithClientOptions(opts...),
		),
		createLink: connect.NewClient[v1.CreateLinkRequest, v1.CreateLinkResponse](
			httpClient,
			baseURL+XAgentServiceCreateLinkProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("CreateLink")),
			connect.WithClientOptions(opts...),
		),
		listLinks: connect.NewClient[v1.ListLinksRequest, v1.ListLinksResponse](
			httpClient,
			baseURL+XAgentServiceListLinksProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("ListLinks")),
			connect.WithClientOptions(opts...),
		),
		findLinksByURL: connect.NewClient[v1.FindLinksByURLRequest, v1.FindLinksByURLResponse](
			httpClient,
			baseURL+XAgentServiceFindLinksByURLProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("FindLinksByURL")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[v1.ListEventsRequest, v1.ListEventsResponse](
			httpClient,
			baseURL+XAgentServiceListEventsProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		createEvent: connect.NewClient[v1.CreateEventRequest, v1.CreateEventResponse](
			httpClient,
			baseURL+XAgentServiceCreateEventProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("CreateEvent")),
			connect.WithClientOptions(opts...),
		),
		getEvent: connect.NewClient[v1.GetEventRequest, v1.GetEventResponse](
			httpClient,
			baseURL+XAgentServiceGetEventProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("GetEvent")),
			connect.WithClientOptions(opts...),
		),
		deleteEvent: connect.NewClient[v1.DeleteEventRequest, v1.DeleteEventResponse](
			httpClient,
			baseURL+XAgentServiceDeleteEventProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("DeleteEvent")),
			connect.WithClientOptions(opts...),
		),
		addEventTask: connect.NewClient[v1.AddEventTaskRequest, v1.AddEventTaskResponse](
			httpClient,
			baseURL+XAgentServiceAddEventTaskProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("AddEventTask")),
			connect.WithClientOptions(opts...),
		),
		removeEventTask: connect.NewClient[v1.RemoveEventTaskRequest, v1.RemoveEventTaskResponse](
			httpClient,
			baseURL+XAgentServiceRemoveEventTaskProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("RemoveEventTask")),
			connect.WithClientOptions(opts...),
		),
		listEventTasks: connect.NewClient[v1.ListEventTasksRequest, v1.ListEventTasksResponse](
			httpClient,
			baseURL+XAgentServiceListEventTasksProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("ListEventTasks")),
			connect.WithClientOptions(opts...),
		),
		listEventsByTask: connect.NewClient[v1.ListEventsByTaskRequest, v1.ListEventsByTaskResponse](
			httpClient,
			baseURL+XAgentServiceListEventsByTaskProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("ListEventsByTask")),
			connect.WithClientOptions(opts...),
		),
		processEvent: connect.NewClient[v1.ProcessEventRequest, v1.ProcessEventResponse](
			httpClient,
			baseURL+XAgentServiceProcessEventProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("ProcessEvent")),
			connect.WithClientOptions(opts...),
		),
		submitRunnerEvents: connect.NewClient[v1.SubmitRunnerEventsRequest, v1.SubmitRunnerEventsResponse](
			httpClient,
			baseURL+XAgentServiceSubmitRunnerEventsProcedure,
			connect.WithSchema(xAgentServiceMethods.ByName("SubmitRunnerEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// xAgentServiceClient implements XAgentServiceClient.
type xAgentServiceClient struct {
	listTasks          *connect.Client[v1.ListTasksRequest, v1.ListTasksResponse]
	listChildTasks     *connect.Client[v1.ListChildTasksRequest, v1.ListChildTasksResponse]
	createTask         *connect.Client[v1.CreateTaskRequest, v1.CreateTaskResponse]
	getTask            *connect.Client[v1.GetTaskRequest, v1.GetTaskResponse]
	getTaskDetails     *connect.Client[v1.GetTaskDetailsRequest, v1.GetTaskDetailsResponse]
	updateTask         *connect.Client[v1.UpdateTaskRequest, v1.UpdateTaskResponse]
	deleteTask         *connect.Client[v1.DeleteTaskRequest, v1.DeleteTaskResponse]
	archiveTask        *connect.Client[v1.ArchiveTaskRequest, v1.ArchiveTaskResponse]
	cancelTask         *connect.Client[v1.CancelTaskRequest, v1.CancelTaskResponse]
	restartTask        *connect.Client[v1.RestartTaskRequest, v1.RestartTaskResponse]
	uploadLogs         *connect.Client[v1.UploadLogsRequest, v1.UploadLogsResponse]
	listLogs           *connect.Client[v1.ListLogsRequest, v1.ListLogsResponse]
	createLink         *connect.Client[v1.CreateLinkRequest, v1.CreateLinkResponse]
	listLinks          *connect.Client[v1.ListLinksRequest, v1.ListLinksResponse]
	findLinksByURL     *connect.Client[v1.FindLinksByURLRequest, v1.FindLinksByURLResponse]
	listEvents         *connect.Client[v1.ListEventsRequest, v1.ListEventsResponse]
	createEvent        *connect.Client[v1.CreateEventRequest, v1.CreateEventResponse]
	getEvent           *connect.Client[v1.GetEventRequest, v1.GetEventResponse]
	deleteEvent        *connect.Client[v1.DeleteEventRequest, v1.DeleteEventResponse]
	addEventTask       *connect.Client[v1.AddEventTaskRequest, v1.AddEventTaskResponse]
	removeEventTask    *connect.Client[v1.RemoveEventTaskRequest, v1.RemoveEventTaskResponse]
	listEventTasks     *connect.Client[v1.ListEventTasksRequest, v1.ListEventTasksResponse]
	listEventsByTask   *connect.Client[v1.ListEventsByTaskRequest, v1.ListEventsByTaskResponse]
	processEvent       *connect.Client[v1.ProcessEventRequest, v1.ProcessEventResponse]
	submitRunnerEvents *connect.Client[v1.SubmitRunnerEventsRequest, v1.SubmitRunnerEventsResponse]
}

// ListTasks calls xagent.v1.XAgentService.ListTasks.
func (c *xAgentServiceClient) ListTasks(ctx context.Context, req *v1.ListTasksRequest) (*v1.ListTasksResponse, error) {
	response, err := c.listTasks.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListChildTasks calls xagent.v1.XAgentService.ListChildTasks.
func (c *xAgentServiceClient) ListChildTasks(ctx context.Context, req *v1.ListChildTasksRequest) (*v1.ListChildTasksResponse, error) {
	response, err := c.listChildTasks.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateTask calls xagent.v1.XAgentService.CreateTask.
func (c *xAgentServiceClient) CreateTask(ctx context.Context, req *v1.CreateTaskRequest) (*v1.CreateTaskResponse, error) {
	response, err := c.createTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetTask calls xagent.v1.XAgentService.GetTask.
func (c *xAgentServiceClient) GetTask(ctx context.Context, req *v1.GetTaskRequest) (*v1.GetTaskResponse, error) {
	response, err := c.getTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetTaskDetails calls xagent.v1.XAgentService.GetTaskDetails.
func (c *xAgentServiceClient) GetTaskDetails(ctx context.Context, req *v1.GetTaskDetailsRequest) (*v1.GetTaskDetailsResponse, error) {
	response, err := c.getTaskDetails.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateTask calls xagent.v1.XAgentService.UpdateTask.
func (c *xAgentServiceClient) UpdateTask(ctx context.Context, req *v1.UpdateTaskRequest) (*v1.UpdateTaskResponse, error) {
	response, err := c.updateTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteTask calls xagent.v1.XAgentService.DeleteTask.
func (c *xAgentServiceClient) DeleteTask(ctx context.Context, req *v1.DeleteTaskRequest) (*v1.DeleteTaskResponse, error) {
	response, err := c.deleteTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ArchiveTask calls xagent.v1.XAgentService.ArchiveTask.
func (c *xAgentServiceClient) ArchiveTask(ctx context.Context, req *v1.ArchiveTaskRequest) (*v1.ArchiveTaskResponse, error) {
	response, err := c.archiveTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CancelTask calls xagent.v1.XAgentService.CancelTask.
func (c *xAgentServiceClient) CancelTask(ctx context.Context, req *v1.CancelTaskRequest) (*v1.CancelTaskResponse, error) {
	response, err := c.cancelTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RestartTask calls xagent.v1.XAgentService.RestartTask.
func (c *xAgentServiceClient) RestartTask(ctx context.Context, req *v1.RestartTaskRequest) (*v1.RestartTaskResponse, error) {
	response, err := c.restartTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UploadLogs calls xagent.v1.XAgentService.UploadLogs.
func (c *xAgentServiceClient) UploadLogs(ctx context.Context, req *v1.UploadLogsRequest) (*v1.UploadLogsResponse, error) {
	response, err := c.uploadLogs.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListLogs calls xagent.v1.XAgentService.ListLogs.
func (c *xAgentServiceClient) ListLogs(ctx context.Context, req *v1.ListLogsRequest) (*v1.ListLogsResponse, error) {
	response, err := c.listLogs.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateLink calls xagent.v1.XAgentService.CreateLink.
func (c *xAgentServiceClient) CreateLink(ctx context.Context, req *v1.CreateLinkRequest) (*v1.CreateLinkResponse, error) {
	response, err := c.createLink.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListLinks calls xagent.v1.XAgentService.ListLinks.
func (c *xAgentServiceClient) ListLinks(ctx context.Context, req *v1.ListLinksRequest) (*v1.ListLinksResponse, error) {
	response, err := c.listLinks.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// FindLinksByURL calls xagent.v1.XAgentService.FindLinksByURL.
func (c *xAgentServiceClient) FindLinksByURL(ctx context.Context, req *v1.FindLinksByURLRequest) (*v1.FindLinksByURLResponse, error) {
	response, err := c.findLinksByURL.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListEvents calls xagent.v1.XAgentService.ListEvents.
func (c *xAgentServiceClient) ListEvents(ctx context.Context, req *v1.ListEventsRequest) (*v1.ListEventsResponse, error) {
	response, err := c.listEvents.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateEvent calls xagent.v1.XAgentService.CreateEvent.
func (c *xAgentServiceClient) CreateEvent(ctx context.Context, req *v1.CreateEventRequest) (*v1.CreateEventResponse, error) {
	response, err := c.createEvent.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetEvent calls xagent.v1.XAgentService.GetEvent.
func (c *xAgentServiceClient) GetEvent(ctx context.Context, req *v1.GetEventRequest) (*v1.GetEventResponse, error) {
	response, err := c.getEvent.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteEvent calls xagent.v1.XAgentService.DeleteEvent.
func (c *xAgentServiceClient) DeleteEvent(ctx context.Context, req *v1.DeleteEventRequest) (*v1.DeleteEventResponse, error) {
	response, err := c.deleteEvent.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AddEventTask calls xagent.v1.XAgentService.AddEventTask.
func (c *xAgentServiceClient) AddEventTask(ctx context.Context, req *v1.AddEventTaskRequest) (*v1.AddEventTaskResponse, error) {
	response, err := c.addEventTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RemoveEventTask calls xagent.v1.XAgentService.RemoveEventTask.
func (c *xAgentServiceClient) RemoveEventTask(ctx context.Context, req *v1.RemoveEventTaskRequest) (*v1.RemoveEventTaskResponse, error) {
	response, err := c.removeEventTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListEventTasks calls xagent.v1.XAgentService.ListEventTasks.
func (c *xAgentServiceClient) ListEventTasks(ctx context.Context, req *v1.ListEventTasksRequest) (*v1.ListEventTasksResponse, error) {
	response, err := c.listEventTasks.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListEventsByTask calls xagent.v1.XAgentService.ListEventsByTask.
func (c *xAgentServiceClient) ListEventsByTask(ctx context.Context, req *v1.ListEventsByTaskRequest) (*v1.ListEventsByTaskResponse, error) {
	response, err := c.listEventsByTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ProcessEvent calls xagent.v1.XAgentService.ProcessEvent.
func (c *xAgentServiceClient) ProcessEvent(ctx context.Context, req *v1.ProcessEventRequest) (*v1.ProcessEventResponse, error) {
	response, err := c.processEvent.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SubmitRunnerEvents calls xagent.v1.XAgentService.SubmitRunnerEvents.
func (c *xAgentServiceClient) SubmitRunnerEvents(ctx context.Context, req *v1.SubmitRunnerEventsRequest) (*v1.SubmitRunnerEventsResponse, error) {
	response, err := c.submitRunnerEvents.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// XAgentServiceHandler is an implementation of the xagent.v1.XAgentService service.
type XAgentServiceHandler interface {
	ListTasks(context.Context, *v1.ListTasksRequest) (*v1.ListTasksResponse, error)
	ListChildTasks(context.Context, *v1.ListChildTasksRequest) (*v1.ListChildTasksResponse, error)
	CreateTask(context.Context, *v1.CreateTaskRequest) (*v1.CreateTaskResponse, error)
	GetTask(context.Context, *v1.GetTaskRequest) (*v1.GetTaskResponse, error)
	GetTaskDetails(context.Context, *v1.GetTaskDetailsRequest) (*v1.GetTaskDetailsResponse, error)
	UpdateTask(context.Context, *v1.UpdateTaskRequest) (*v1.UpdateTaskResponse, error)
	DeleteTask(context.Context, *v1.DeleteTaskRequest) (*v1.DeleteTaskResponse, error)
	ArchiveTask(context.Context, *v1.ArchiveTaskRequest) (*v1.ArchiveTaskResponse, error)
	CancelTask(context.Context, *v1.CancelTaskRequest) (*v1.CancelTaskResponse, error)
	RestartTask(context.Context, *v1.RestartTaskRequest) (*v1.RestartTaskResponse, error)
	UploadLogs(context.Context, *v1.UploadLogsRequest) (*v1.UploadLogsResponse, error)
	ListLogs(context.Context, *v1.ListLogsRequest) (*v1.ListLogsResponse, error)
	CreateLink(context.Context, *v1.CreateLinkRequest) (*v1.CreateLinkResponse, error)
	ListLinks(context.Context, *v1.ListLinksRequest) (*v1.ListLinksResponse, error)
	FindLinksByURL(context.Context, *v1.FindLinksByURLRequest) (*v1.FindLinksByURLResponse, error)
	ListEvents(context.Context, *v1.ListEventsRequest) (*v1.ListEventsResponse, error)
	CreateEvent(context.Context, *v1.CreateEventRequest) (*v1.CreateEventResponse, error)
	GetEvent(context.Context, *v1.GetEventRequest) (*v1.GetEventResponse, error)
	DeleteEvent(context.Context, *v1.DeleteEventRequest) (*v1.DeleteEventResponse, error)
	AddEventTask(context.Context, *v1.AddEventTaskRequest) (*v1.AddEventTaskResponse, error)
	RemoveEventTask(context.Context, *v1.RemoveEventTaskRequest) (*v1.RemoveEventTaskResponse, error)
	ListEventTasks(context.Context, *v1.ListEventTasksRequest) (*v1.ListEventTasksResponse, error)
	ListEventsByTask(context.Context, *v1.ListEventsByTaskRequest) (*v1.ListEventsByTaskResponse, error)
	ProcessEvent(context.Context, *v1.ProcessEventRequest) (*v1.ProcessEventResponse, error)
	SubmitRunnerEvents(context.Context, *v1.SubmitRunnerEventsRequest) (*v1.SubmitRunnerEventsResponse, error)
}

// NewXAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewXAgentServiceHandler(svc XAgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	xAgentServiceMethods := v1.File_xagent_v1_xagent_proto.Services().ByName("XAgentService").Methods()
	xAgentServiceListTasksHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceListTasksProcedure,
		svc.ListTasks,
		connect.WithSchema(xAgentServiceMethods.ByName("ListTasks")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceListChildTasksHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceListChildTasksProcedure,
		svc.ListChildTasks,
		connect.WithSchema(xAgentServiceMethods.ByName("ListChildTasks")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceCreateTaskHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(xAgentServiceMethods.ByName("CreateTask")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceGetTaskHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(xAgentServiceMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceGetTaskDetailsHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceGetTaskDetailsProcedure,
		svc.GetTaskDetails,
		connect.WithSchema(xAgentServiceMethods.ByName("GetTaskDetails")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceUpdateTaskHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceUpdateTaskProcedure,
		svc.UpdateTask,
		connect.WithSchema(xAgentServiceMethods.ByName("UpdateTask")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceDeleteTaskHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceDeleteTaskProcedure,
		svc.DeleteTask,
		connect.WithSchema(xAgentServiceMethods.ByName("DeleteTask")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceArchiveTaskHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceArchiveTaskProcedure,
		svc.ArchiveTask,
		connect.WithSchema(xAgentServiceMethods.ByName("ArchiveTask")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceCancelTaskHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceCancelTaskProcedure,
		svc.CancelTask,
		connect.WithSchema(xAgentServiceMethods.ByName("CancelTask")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceRestartTaskHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceRestartTaskProcedure,
		svc.RestartTask,
		connect.WithSchema(xAgentServiceMethods.ByName("RestartTask")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceUploadLogsHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceUploadLogsProcedure,
		svc.UploadLogs,
		connect.WithSchema(xAgentServiceMethods.ByName("UploadLogs")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceListLogsHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceListLogsProcedure,
		svc.ListLogs,
		connect.WithSchema(xAgentServiceMethods.ByName("ListLogs")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceCreateLinkHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceCreateLinkProcedure,
		svc.CreateLink,
		connect.WithSchema(xAgentServiceMethods.ByName("CreateLink")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceListLinksHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceListLinksProcedure,
		svc.ListLinks,
		connect.WithSchema(xAgentServiceMethods.ByName("ListLinks")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceFindLinksByURLHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceFindLinksByURLProcedure,
		svc.FindLinksByURL,
		connect.WithSchema(xAgentServiceMethods.ByName("FindLinksByURL")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceListEventsHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(xAgentServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceCreateEventHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceCreateEventProcedure,
		svc.CreateEvent,
		connect.WithSchema(xAgentServiceMethods.ByName("CreateEvent")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceGetEventHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceGetEventProcedure,
		svc.GetEvent,
		connect.WithSchema(xAgentServiceMethods.ByName("GetEvent")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceDeleteEventHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceDeleteEventProcedure,
		svc.DeleteEvent,
		connect.WithSchema(xAgentServiceMethods.ByName("DeleteEvent")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceAddEventTaskHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceAddEventTaskProcedure,
		svc.AddEventTask,
		connect.WithSchema(xAgentServiceMethods.ByName("AddEventTask")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceRemoveEventTaskHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceRemoveEventTaskProcedure,
		svc.RemoveEventTask,
		connect.WithSchema(xAgentServiceMethods.ByName("RemoveEventTask")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceListEventTasksHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceListEventTasksProcedure,
		svc.ListEventTasks,
		connect.WithSchema(xAgentServiceMethods.ByName("ListEventTasks")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceListEventsByTaskHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceListEventsByTaskProcedure,
		svc.ListEventsByTask,
		connect.WithSchema(xAgentServiceMethods.ByName("ListEventsByTask")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceProcessEventHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceProcessEventProcedure,
		svc.ProcessEvent,
		connect.WithSchema(xAgentServiceMethods.ByName("ProcessEvent")),
		connect.WithHandlerOptions(opts...),
	)
	xAgentServiceSubmitRunnerEventsHandler := connect.NewUnaryHandlerSimple(
		XAgentServiceSubmitRunnerEventsProcedure,
		svc.SubmitRunnerEvents,
		connect.WithSchema(xAgentServiceMethods.ByName("SubmitRunnerEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/xagent.v1.XAgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case XAgentServiceListTasksProcedure:
			xAgentServiceListTasksHandler.ServeHTTP(w, r)
		case XAgentServiceListChildTasksProcedure:
			xAgentServiceListChildTasksHandler.ServeHTTP(w, r)
		case XAgentServiceCreateTaskProcedure:
			xAgentServiceCreateTaskHandler.ServeHTTP(w, r)
		case XAgentServiceGetTaskProcedure:
			xAgentServiceGetTaskHandler.ServeHTTP(w, r)
		case XAgentServiceGetTaskDetailsProcedure:
			xAgentServiceGetTaskDetailsHandler.ServeHTTP(w, r)
		case XAgentServiceUpdateTaskProcedure:
			xAgentServiceUpdateTaskHandler.ServeHTTP(w, r)
		case XAgentServiceDeleteTaskProcedure:
			xAgentServiceDeleteTaskHandler.ServeHTTP(w, r)
		case XAgentServiceArchiveTaskProcedure:
			xAgentServiceArchiveTaskHandler.ServeHTTP(w, r)
		case XAgentServiceCancelTaskProcedure:
			xAgentServiceCancelTaskHandler.ServeHTTP(w, r)
		case XAgentServiceRestartTaskProcedure:
			xAgentServiceRestartTaskHandler.ServeHTTP(w, r)
		case XAgentServiceUploadLogsProcedure:
			xAgentServiceUploadLogsHandler.ServeHTTP(w, r)
		case XAgentServiceListLogsProcedure:
			xAgentServiceListLogsHandler.ServeHTTP(w, r)
		case XAgentServiceCreateLinkProcedure:
			xAgentServiceCreateLinkHandler.ServeHTTP(w, r)
		case XAgentServiceListLinksProcedure:
			xAgentServiceListLinksHandler.ServeHTTP(w, r)
		case XAgentServiceFindLinksByURLProcedure:
			xAgentServiceFindLinksByURLHandler.ServeHTTP(w, r)
		case XAgentServiceListEventsProcedure:
			xAgentServiceListEventsHandler.ServeHTTP(w, r)
		case XAgentServiceCreateEventProcedure:
			xAgentServiceCreateEventHandler.ServeHTTP(w, r)
		case XAgentServiceGetEventProcedure:
			xAgentServiceGetEventHandler.ServeHTTP(w, r)
		case XAgentServiceDeleteEventProcedure:
			xAgentServiceDeleteEventHandler.ServeHTTP(w, r)
		case XAgentServiceAddEventTaskProcedure:
			xAgentServiceAddEventTaskHandler.ServeHTTP(w, r)
		case XAgentServiceRemoveEventTaskProcedure:
			xAgentServiceRemoveEventTaskHandler.ServeHTTP(w, r)
		case XAgentServiceListEventTasksProcedure:
			xAgentServiceListEventTasksHandler.ServeHTTP(w, r)
		case XAgentServiceListEventsByTaskProcedure:
			xAgentServiceListEventsByTaskHandler.ServeHTTP(w, r)
		case XAgentServiceProcessEventProcedure:
			xAgentServiceProcessEventHandler.ServeHTTP(w, r)
		case XAgentServiceSubmitRunnerEventsProcedure:
			xAgentServiceSubmitRunnerEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedXAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedXAgentServiceHandler struct{}

func (UnimplementedXAgentServiceHandler) ListTasks(context.Context, *v1.ListTasksRequest) (*v1.ListTasksResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.ListTasks is not implemented"))
}

func (UnimplementedXAgentServiceHandler) ListChildTasks(context.Context, *v1.ListChildTasksRequest) (*v1.ListChildTasksResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.ListChildTasks is not implemented"))
}

func (UnimplementedXAgentServiceHandler) CreateTask(context.Context, *v1.CreateTaskRequest) (*v1.CreateTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.CreateTask is not implemented"))
}

func (UnimplementedXAgentServiceHandler) GetTask(context.Context, *v1.GetTaskRequest) (*v1.GetTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.GetTask is not implemented"))
}

func (UnimplementedXAgentServiceHandler) GetTaskDetails(context.Context, *v1.GetTaskDetailsRequest) (*v1.GetTaskDetailsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.GetTaskDetails is not implemented"))
}

func (UnimplementedXAgentServiceHandler) UpdateTask(context.Context, *v1.UpdateTaskRequest) (*v1.UpdateTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.UpdateTask is not implemented"))
}

func (UnimplementedXAgentServiceHandler) DeleteTask(context.Context, *v1.DeleteTaskRequest) (*v1.DeleteTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.DeleteTask is not implemented"))
}

func (UnimplementedXAgentServiceHandler) ArchiveTask(context.Context, *v1.ArchiveTaskRequest) (*v1.ArchiveTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.ArchiveTask is not implemented"))
}

func (UnimplementedXAgentServiceHandler) CancelTask(context.Context, *v1.CancelTaskRequest) (*v1.CancelTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.CancelTask is not implemented"))
}

func (UnimplementedXAgentServiceHandler) RestartTask(context.Context, *v1.RestartTaskRequest) (*v1.RestartTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.RestartTask is not implemented"))
}

func (UnimplementedXAgentServiceHandler) UploadLogs(context.Context, *v1.UploadLogsRequest) (*v1.UploadLogsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.UploadLogs is not implemented"))
}

func (UnimplementedXAgentServiceHandler) ListLogs(context.Context, *v1.ListLogsRequest) (*v1.ListLogsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.ListLogs is not implemented"))
}

func (UnimplementedXAgentServiceHandler) CreateLink(context.Context, *v1.CreateLinkRequest) (*v1.CreateLinkResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.CreateLink is not implemented"))
}

func (UnimplementedXAgentServiceHandler) ListLinks(context.Context, *v1.ListLinksRequest) (*v1.ListLinksResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.ListLinks is not implemented"))
}

func (UnimplementedXAgentServiceHandler) FindLinksByURL(context.Context, *v1.FindLinksByURLRequest) (*v1.FindLinksByURLResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.FindLinksByURL is not implemented"))
}

func (UnimplementedXAgentServiceHandler) ListEvents(context.Context, *v1.ListEventsRequest) (*v1.ListEventsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.ListEvents is not implemented"))
}

func (UnimplementedXAgentServiceHandler) CreateEvent(context.Context, *v1.CreateEventRequest) (*v1.CreateEventResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.CreateEvent is not implemented"))
}

func (UnimplementedXAgentServiceHandler) GetEvent(context.Context, *v1.GetEventRequest) (*v1.GetEventResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.GetEvent is not implemented"))
}

func (UnimplementedXAgentServiceHandler) DeleteEvent(context.Context, *v1.DeleteEventRequest) (*v1.DeleteEventResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.DeleteEvent is not implemented"))
}

func (UnimplementedXAgentServiceHandler) AddEventTask(context.Context, *v1.AddEventTaskRequest) (*v1.AddEventTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.AddEventTask is not implemented"))
}

func (UnimplementedXAgentServiceHandler) RemoveEventTask(context.Context, *v1.RemoveEventTaskRequest) (*v1.RemoveEventTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.RemoveEventTask is not implemented"))
}

func (UnimplementedXAgentServiceHandler) ListEventTasks(context.Context, *v1.ListEventTasksRequest) (*v1.ListEventTasksResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.ListEventTasks is not implemented"))
}

func (UnimplementedXAgentServiceHandler) ListEventsByTask(context.Context, *v1.ListEventsByTaskRequest) (*v1.ListEventsByTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.ListEventsByTask is not implemented"))
}

func (UnimplementedXAgentServiceHandler) ProcessEvent(context.Context, *v1.ProcessEventRequest) (*v1.ProcessEventResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.ProcessEvent is not implemented"))
}

func (UnimplementedXAgentServiceHandler) SubmitRunnerEvents(context.Context, *v1.SubmitRunnerEventsRequest) (*v1.SubmitRunnerEventsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("xagent.v1.XAgentService.SubmitRunnerEvents is not implemented"))
}
