// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package webhook_test

import (
	"github.com/icholy/xagent/internal/webhook"
	"sync"
)

// Ensure, that PublisherMock does implement webhook.Publisher.
// If this is not the case, regenerate this file with moq.
var _ webhook.Publisher = &PublisherMock{}

// PublisherMock is a mock implementation of webhook.Publisher.
//
//	func TestSomethingThatUsesPublisher(t *testing.T) {
//
//		// make and configure a mocked webhook.Publisher
//		mockedPublisher := &PublisherMock{
//			PublishFunc: func(event *webhook.Event) error {
//				panic("mock out the Publish method")
//			},
//		}
//
//		// use mockedPublisher in code that requires webhook.Publisher
//		// and then make assertions.
//
//	}
type PublisherMock struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(event *webhook.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Event is the event argument value.
			Event *webhook.Event
		}
	}
	lockPublish sync.RWMutex
}

// Publish calls PublishFunc.
func (mock *PublisherMock) Publish(event *webhook.Event) error {
	if mock.PublishFunc == nil {
		panic("PublisherMock.PublishFunc: method is nil but Publisher.Publish was just called")
	}
	callInfo := struct {
		Event *webhook.Event
	}{
		Event: event,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	return mock.PublishFunc(event)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedPublisher.PublishCalls())
func (mock *PublisherMock) PublishCalls() []struct {
	Event *webhook.Event
} {
	var calls []struct {
		Event *webhook.Event
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}
