// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package apiserver

import (
	"context"
	"github.com/icholy/xagent/internal/model"
	"sync"
)

// Ensure, that GithubServerMock does implement GithubServer.
// If this is not the case, regenerate this file with moq.
var _ GithubServer = &GithubServerMock{}

// GithubServerMock is a mock implementation of GithubServer.
//
//	func TestSomethingThatUsesGithubServer(t *testing.T) {
//
//		// make and configure a mocked GithubServer
//		mockedGithubServer := &GithubServerMock{
//			AppInstallURLFunc: func() string {
//				panic("mock out the AppInstallURL method")
//			},
//			VerifyInstallationAccessFunc: func(ctx context.Context, installationID int64, user *model.User) error {
//				panic("mock out the VerifyInstallationAccess method")
//			},
//		}
//
//		// use mockedGithubServer in code that requires GithubServer
//		// and then make assertions.
//
//	}
type GithubServerMock struct {
	// AppInstallURLFunc mocks the AppInstallURL method.
	AppInstallURLFunc func() string

	// VerifyInstallationAccessFunc mocks the VerifyInstallationAccess method.
	VerifyInstallationAccessFunc func(ctx context.Context, installationID int64, user *model.User) error

	// calls tracks calls to the methods.
	calls struct {
		// AppInstallURL holds details about calls to the AppInstallURL method.
		AppInstallURL []struct {
		}
		// VerifyInstallationAccess holds details about calls to the VerifyInstallationAccess method.
		VerifyInstallationAccess []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// InstallationID is the installationID argument value.
			InstallationID int64
			// User is the user argument value.
			User *model.User
		}
	}
	lockAppInstallURL            sync.RWMutex
	lockVerifyInstallationAccess sync.RWMutex
}

// AppInstallURL calls AppInstallURLFunc.
func (mock *GithubServerMock) AppInstallURL() string {
	if mock.AppInstallURLFunc == nil {
		panic("GithubServerMock.AppInstallURLFunc: method is nil but GithubServer.AppInstallURL was just called")
	}
	callInfo := struct {
	}{}
	mock.lockAppInstallURL.Lock()
	mock.calls.AppInstallURL = append(mock.calls.AppInstallURL, callInfo)
	mock.lockAppInstallURL.Unlock()
	return mock.AppInstallURLFunc()
}

// AppInstallURLCalls gets all the calls that were made to AppInstallURL.
// Check the length with:
//
//	len(mockedGithubServer.AppInstallURLCalls())
func (mock *GithubServerMock) AppInstallURLCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAppInstallURL.RLock()
	calls = mock.calls.AppInstallURL
	mock.lockAppInstallURL.RUnlock()
	return calls
}

// VerifyInstallationAccess calls VerifyInstallationAccessFunc.
func (mock *GithubServerMock) VerifyInstallationAccess(ctx context.Context, installationID int64, user *model.User) error {
	if mock.VerifyInstallationAccessFunc == nil {
		panic("GithubServerMock.VerifyInstallationAccessFunc: method is nil but GithubServer.VerifyInstallationAccess was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		InstallationID int64
		User           *model.User
	}{
		Ctx:            ctx,
		InstallationID: installationID,
		User:           user,
	}
	mock.lockVerifyInstallationAccess.Lock()
	mock.calls.VerifyInstallationAccess = append(mock.calls.VerifyInstallationAccess, callInfo)
	mock.lockVerifyInstallationAccess.Unlock()
	return mock.VerifyInstallationAccessFunc(ctx, installationID, user)
}

// VerifyInstallationAccessCalls gets all the calls that were made to VerifyInstallationAccess.
// Check the length with:
//
//	len(mockedGithubServer.VerifyInstallationAccessCalls())
func (mock *GithubServerMock) VerifyInstallationAccessCalls() []struct {
	Ctx            context.Context
	InstallationID int64
	User           *model.User
} {
	var calls []struct {
		Ctx            context.Context
		InstallationID int64
		User           *model.User
	}
	mock.lockVerifyInstallationAccess.RLock()
	calls = mock.calls.VerifyInstallationAccess
	mock.lockVerifyInstallationAccess.RUnlock()
	return calls
}
