// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package apiserver

import (
	"sync"
)

// Ensure, that ShellRegistryMock does implement ShellRegistry.
// If this is not the case, regenerate this file with moq.
var _ ShellRegistry = &ShellRegistryMock{}

// ShellRegistryMock is a mock implementation of ShellRegistry.
//
//	func TestSomethingThatUsesShellRegistry(t *testing.T) {
//
//		// make and configure a mocked ShellRegistry
//		mockedShellRegistry := &ShellRegistryMock{
//			SeedFunc: func(id string, orgID int64, taskID int64) error {
//				panic("mock out the Seed method")
//			},
//		}
//
//		// use mockedShellRegistry in code that requires ShellRegistry
//		// and then make assertions.
//
//	}
type ShellRegistryMock struct {
	// SeedFunc mocks the Seed method.
	SeedFunc func(id string, orgID int64, taskID int64) error

	// calls tracks calls to the methods.
	calls struct {
		// Seed holds details about calls to the Seed method.
		Seed []struct {
			// ID is the id argument value.
			ID string
			// OrgID is the orgID argument value.
			OrgID int64
			// TaskID is the taskID argument value.
			TaskID int64
		}
	}
	lockSeed sync.RWMutex
}

// Seed calls SeedFunc.
func (mock *ShellRegistryMock) Seed(id string, orgID int64, taskID int64) error {
	if mock.SeedFunc == nil {
		panic("ShellRegistryMock.SeedFunc: method is nil but ShellRegistry.Seed was just called")
	}
	callInfo := struct {
		ID     string
		OrgID  int64
		TaskID int64
	}{
		ID:     id,
		OrgID:  orgID,
		TaskID: taskID,
	}
	mock.lockSeed.Lock()
	mock.calls.Seed = append(mock.calls.Seed, callInfo)
	mock.lockSeed.Unlock()
	return mock.SeedFunc(id, orgID, taskID)
}

// SeedCalls gets all the calls that were made to Seed.
// Check the length with:
//
//	len(mockedShellRegistry.SeedCalls())
func (mock *ShellRegistryMock) SeedCalls() []struct {
	ID     string
	OrgID  int64
	TaskID int64
} {
	var calls []struct {
		ID     string
		OrgID  int64
		TaskID int64
	}
	mock.lockSeed.RLock()
	calls = mock.calls.Seed
	mock.lockSeed.RUnlock()
	return calls
}
