// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xagent/v1/xagent.proto

package xagentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Instruction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{0}
}

func (x *Instruction) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Instruction) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Parent        int64                  `protobuf:"varint,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Workspace     string                 `protobuf:"bytes,4,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Instructions  []*Instruction         `protobuf:"bytes,5,rep,name=instructions,proto3" json:"instructions,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetParent() int64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *Task) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *Task) GetInstructions() []*Instruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type McpServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpServer) Reset() {
	*x = McpServer{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpServer) ProtoMessage() {}

func (x *McpServer) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpServer.ProtoReflect.Descriptor instead.
func (*McpServer) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{2}
}

func (x *McpServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *McpServer) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *McpServer) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *McpServer) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []string               `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{3}
}

func (x *ListTasksRequest) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ListChildTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      int64                  `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildTasksRequest) Reset() {
	*x = ListChildTasksRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildTasksRequest) ProtoMessage() {}

func (x *ListChildTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildTasksRequest.ProtoReflect.Descriptor instead.
func (*ListChildTasksRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{5}
}

func (x *ListChildTasksRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type ListChildTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildTasksResponse) Reset() {
	*x = ListChildTasksResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildTasksResponse) ProtoMessage() {}

func (x *ListChildTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildTasksResponse.ProtoReflect.Descriptor instead.
func (*ListChildTasksResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{6}
}

func (x *ListChildTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parent        int64                  `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Workspace     string                 `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Instructions  []*Instruction         `protobuf:"bytes,4,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetParent() int64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *CreateTaskRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *CreateTaskRequest) GetInstructions() []*Instruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDetailsRequest) Reset() {
	*x = GetTaskDetailsRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDetailsRequest) ProtoMessage() {}

func (x *GetTaskDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskDetailsRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{11}
}

func (x *GetTaskDetailsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTaskDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Children      []*Task                `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	Events        []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	Links         []*TaskLink            `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDetailsResponse) Reset() {
	*x = GetTaskDetailsResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDetailsResponse) ProtoMessage() {}

func (x *GetTaskDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskDetailsResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{12}
}

func (x *GetTaskDetailsResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *GetTaskDetailsResponse) GetChildren() []*Task {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *GetTaskDetailsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetTaskDetailsResponse) GetLinks() []*TaskLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type UpdateTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AddInstructions []*Instruction         `protobuf:"bytes,4,rep,name=add_instructions,json=addInstructions,proto3" json:"add_instructions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTaskRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTaskRequest) GetAddInstructions() []*Instruction {
	if x != nil {
		return x.AddInstructions
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{14}
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{16}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{17}
}

func (x *LogEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UploadLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLogsRequest) Reset() {
	*x = UploadLogsRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogsRequest) ProtoMessage() {}

func (x *UploadLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogsRequest.ProtoReflect.Descriptor instead.
func (*UploadLogsRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{18}
}

func (x *UploadLogsRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *UploadLogsRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type UploadLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLogsResponse) Reset() {
	*x = UploadLogsResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogsResponse) ProtoMessage() {}

func (x *UploadLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogsResponse.ProtoReflect.Descriptor instead.
func (*UploadLogsResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{19}
}

type ListLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsRequest) Reset() {
	*x = ListLogsRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsRequest) ProtoMessage() {}

func (x *ListLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsRequest.ProtoReflect.Descriptor instead.
func (*ListLogsRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{20}
}

func (x *ListLogsRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ListLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsResponse) Reset() {
	*x = ListLogsResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsResponse) ProtoMessage() {}

func (x *ListLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsResponse.ProtoReflect.Descriptor instead.
func (*ListLogsResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{21}
}

func (x *ListLogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type TaskLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Relevance     string                 `protobuf:"bytes,3,opt,name=relevance,proto3" json:"relevance,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Notify        bool                   `protobuf:"varint,6,opt,name=notify,proto3" json:"notify,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLink) Reset() {
	*x = TaskLink{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLink) ProtoMessage() {}

func (x *TaskLink) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLink.ProtoReflect.Descriptor instead.
func (*TaskLink) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{22}
}

func (x *TaskLink) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskLink) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskLink) GetRelevance() string {
	if x != nil {
		return x.Relevance
	}
	return ""
}

func (x *TaskLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TaskLink) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskLink) GetNotify() bool {
	if x != nil {
		return x.Notify
	}
	return false
}

func (x *TaskLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Relevance     string                 `protobuf:"bytes,2,opt,name=relevance,proto3" json:"relevance,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Notify        bool                   `protobuf:"varint,5,opt,name=notify,proto3" json:"notify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{23}
}

func (x *CreateLinkRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateLinkRequest) GetRelevance() string {
	if x != nil {
		return x.Relevance
	}
	return ""
}

func (x *CreateLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateLinkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLinkRequest) GetNotify() bool {
	if x != nil {
		return x.Notify
	}
	return false
}

type CreateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *TaskLink              `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{24}
}

func (x *CreateLinkResponse) GetLink() *TaskLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{25}
}

func (x *ListLinksRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*TaskLink            `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{26}
}

func (x *ListLinksResponse) GetLinks() []*TaskLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type FindLinksByURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindLinksByURLRequest) Reset() {
	*x = FindLinksByURLRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindLinksByURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLinksByURLRequest) ProtoMessage() {}

func (x *FindLinksByURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLinksByURLRequest.ProtoReflect.Descriptor instead.
func (*FindLinksByURLRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{27}
}

func (x *FindLinksByURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type FindLinksByURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*TaskLink            `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindLinksByURLResponse) Reset() {
	*x = FindLinksByURLResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindLinksByURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLinksByURLResponse) ProtoMessage() {}

func (x *FindLinksByURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLinksByURLResponse.ProtoReflect.Descriptor instead.
func (*FindLinksByURLResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{28}
}

func (x *FindLinksByURLResponse) GetLinks() []*TaskLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{29}
}

func (x *Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Event) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{30}
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{31}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{32}
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *CreateEventRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{33}
}

func (x *CreateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{34}
}

func (x *GetEventRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{35}
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteEventRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{37}
}

type AddEventTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventTaskRequest) Reset() {
	*x = AddEventTaskRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventTaskRequest) ProtoMessage() {}

func (x *AddEventTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventTaskRequest.ProtoReflect.Descriptor instead.
func (*AddEventTaskRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{38}
}

func (x *AddEventTaskRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *AddEventTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type AddEventTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventTaskResponse) Reset() {
	*x = AddEventTaskResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventTaskResponse) ProtoMessage() {}

func (x *AddEventTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventTaskResponse.ProtoReflect.Descriptor instead.
func (*AddEventTaskResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{39}
}

type RemoveEventTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEventTaskRequest) Reset() {
	*x = RemoveEventTaskRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEventTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEventTaskRequest) ProtoMessage() {}

func (x *RemoveEventTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEventTaskRequest.ProtoReflect.Descriptor instead.
func (*RemoveEventTaskRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{40}
}

func (x *RemoveEventTaskRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *RemoveEventTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type RemoveEventTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEventTaskResponse) Reset() {
	*x = RemoveEventTaskResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEventTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEventTaskResponse) ProtoMessage() {}

func (x *RemoveEventTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEventTaskResponse.ProtoReflect.Descriptor instead.
func (*RemoveEventTaskResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{41}
}

type ListEventTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventTasksRequest) Reset() {
	*x = ListEventTasksRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventTasksRequest) ProtoMessage() {}

func (x *ListEventTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventTasksRequest.ProtoReflect.Descriptor instead.
func (*ListEventTasksRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{42}
}

func (x *ListEventTasksRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type ListEventTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskIds       []int64                `protobuf:"varint,1,rep,packed,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventTasksResponse) Reset() {
	*x = ListEventTasksResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventTasksResponse) ProtoMessage() {}

func (x *ListEventTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventTasksResponse.ProtoReflect.Descriptor instead.
func (*ListEventTasksResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{43}
}

func (x *ListEventTasksResponse) GetTaskIds() []int64 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type ListEventsByTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsByTaskRequest) Reset() {
	*x = ListEventsByTaskRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsByTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsByTaskRequest) ProtoMessage() {}

func (x *ListEventsByTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsByTaskRequest.ProtoReflect.Descriptor instead.
func (*ListEventsByTaskRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{44}
}

func (x *ListEventsByTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ListEventsByTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsByTaskResponse) Reset() {
	*x = ListEventsByTaskResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsByTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsByTaskResponse) ProtoMessage() {}

func (x *ListEventsByTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsByTaskResponse.ProtoReflect.Descriptor instead.
func (*ListEventsByTaskResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{45}
}

func (x *ListEventsByTaskResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type ProcessEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEventRequest) Reset() {
	*x = ProcessEventRequest{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEventRequest) ProtoMessage() {}

func (x *ProcessEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEventRequest.ProtoReflect.Descriptor instead.
func (*ProcessEventRequest) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{46}
}

func (x *ProcessEventRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProcessEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskIds       []int64                `protobuf:"varint,1,rep,packed,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEventResponse) Reset() {
	*x = ProcessEventResponse{}
	mi := &file_xagent_v1_xagent_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEventResponse) ProtoMessage() {}

func (x *ProcessEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xagent_v1_xagent_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEventResponse.ProtoReflect.Descriptor instead.
func (*ProcessEventResponse) Descriptor() ([]byte, []int) {
	return file_xagent_v1_xagent_proto_rawDescGZIP(), []int{47}
}

func (x *ProcessEventResponse) GetTaskIds() []int64 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

var File_xagent_v1_xagent_proto protoreflect.FileDescriptor

const file_xagent_v1_xagent_proto_rawDesc = "" +
	"\n" +
	"\x16xagent/v1/xagent.proto\x12\txagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\vInstruction\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xaa\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\x03R\x06parent\x12\x1c\n" +
	"\tworkspace\x18\x04 \x01(\tR\tworkspace\x12:\n" +
	"\finstructions\x18\x05 \x03(\v2\x16.xagent.v1.InstructionR\finstructions\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb6\x01\n" +
	"\tMcpServer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12/\n" +
	"\x03env\x18\x04 \x03(\v2\x1d.xagent.v1.McpServer.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x10ListTasksRequest\x12\x1a\n" +
	"\bstatuses\x18\x01 \x03(\tR\bstatuses\":\n" +
	"\x11ListTasksResponse\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.xagent.v1.TaskR\x05tasks\"4\n" +
	"\x15ListChildTasksRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\x03R\bparentId\"?\n" +
	"\x16ListChildTasksResponse\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.xagent.v1.TaskR\x05tasks\"\x99\x01\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\x03R\x06parent\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\x12:\n" +
	"\finstructions\x18\x04 \x03(\v2\x16.xagent.v1.InstructionR\finstructions\"9\n" +
	"\x12CreateTaskResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.xagent.v1.TaskR\x04task\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"6\n" +
	"\x0fGetTaskResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.xagent.v1.TaskR\x04task\"'\n" +
	"\x15GetTaskDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xbf\x01\n" +
	"\x16GetTaskDetailsResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.xagent.v1.TaskR\x04task\x12+\n" +
	"\bchildren\x18\x02 \x03(\v2\x0f.xagent.v1.TaskR\bchildren\x12(\n" +
	"\x06events\x18\x03 \x03(\v2\x10.xagent.v1.EventR\x06events\x12)\n" +
	"\x05links\x18\x04 \x03(\v2\x13.xagent.v1.TaskLinkR\x05links\"\x92\x01\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12A\n" +
	"\x10add_instructions\x18\x04 \x03(\v2\x16.xagent.v1.InstructionR\x0faddInstructions\"\x14\n" +
	"\x12UpdateTaskResponse\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteTaskResponse\"8\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"[\n" +
	"\x11UploadLogsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12-\n" +
	"\aentries\x18\x02 \x03(\v2\x13.xagent.v1.LogEntryR\aentries\"\x14\n" +
	"\x12UploadLogsResponse\"*\n" +
	"\x0fListLogsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"A\n" +
	"\x10ListLogsResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.xagent.v1.LogEntryR\aentries\"\xcc\x01\n" +
	"\bTaskLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x1c\n" +
	"\trelevance\x18\x03 \x01(\tR\trelevance\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x16\n" +
	"\x06notify\x18\x06 \x01(\bR\x06notify\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8a\x01\n" +
	"\x11CreateLinkRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1c\n" +
	"\trelevance\x18\x02 \x01(\tR\trelevance\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06notify\x18\x05 \x01(\bR\x06notify\"=\n" +
	"\x12CreateLinkResponse\x12'\n" +
	"\x04link\x18\x01 \x01(\v2\x13.xagent.v1.TaskLinkR\x04link\"+\n" +
	"\x10ListLinksRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\">\n" +
	"\x11ListLinksResponse\x12)\n" +
	"\x05links\x18\x01 \x03(\v2\x13.xagent.v1.TaskLinkR\x05links\")\n" +
	"\x15FindLinksByURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"C\n" +
	"\x16FindLinksByURLResponse\x12)\n" +
	"\x05links\x18\x01 \x03(\v2\x13.xagent.v1.TaskLinkR\x05links\"\x9a\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x13\n" +
	"\x11ListEventsRequest\">\n" +
	"\x12ListEventsResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.xagent.v1.EventR\x06events\"\\\n" +
	"\x12CreateEventRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"=\n" +
	"\x13CreateEventResponse\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x10.xagent.v1.EventR\x05event\"!\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x10GetEventResponse\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x10.xagent.v1.EventR\x05event\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x15\n" +
	"\x13DeleteEventResponse\"I\n" +
	"\x13AddEventTaskRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\"\x16\n" +
	"\x14AddEventTaskResponse\"L\n" +
	"\x16RemoveEventTaskRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\"\x19\n" +
	"\x17RemoveEventTaskResponse\"2\n" +
	"\x15ListEventTasksRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\"3\n" +
	"\x16ListEventTasksResponse\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\x03R\ataskIds\"2\n" +
	"\x17ListEventsByTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"D\n" +
	"\x18ListEventsByTaskResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.xagent.v1.EventR\x06events\"%\n" +
	"\x13ProcessEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x14ProcessEventResponse\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\x03R\ataskIds2\xfe\f\n" +
	"\rXAgentService\x12F\n" +
	"\tListTasks\x12\x1b.xagent.v1.ListTasksRequest\x1a\x1c.xagent.v1.ListTasksResponse\x12U\n" +
	"\x0eListChildTasks\x12 .xagent.v1.ListChildTasksRequest\x1a!.xagent.v1.ListChildTasksResponse\x12I\n" +
	"\n" +
	"CreateTask\x12\x1c.xagent.v1.CreateTaskRequest\x1a\x1d.xagent.v1.CreateTaskResponse\x12@\n" +
	"\aGetTask\x12\x19.xagent.v1.GetTaskRequest\x1a\x1a.xagent.v1.GetTaskResponse\x12U\n" +
	"\x0eGetTaskDetails\x12 .xagent.v1.GetTaskDetailsRequest\x1a!.xagent.v1.GetTaskDetailsResponse\x12I\n" +
	"\n" +
	"UpdateTask\x12\x1c.xagent.v1.UpdateTaskRequest\x1a\x1d.xagent.v1.UpdateTaskResponse\x12I\n" +
	"\n" +
	"DeleteTask\x12\x1c.xagent.v1.DeleteTaskRequest\x1a\x1d.xagent.v1.DeleteTaskResponse\x12I\n" +
	"\n" +
	"UploadLogs\x12\x1c.xagent.v1.UploadLogsRequest\x1a\x1d.xagent.v1.UploadLogsResponse\x12C\n" +
	"\bListLogs\x12\x1a.xagent.v1.ListLogsRequest\x1a\x1b.xagent.v1.ListLogsResponse\x12I\n" +
	"\n" +
	"CreateLink\x12\x1c.xagent.v1.CreateLinkRequest\x1a\x1d.xagent.v1.CreateLinkResponse\x12F\n" +
	"\tListLinks\x12\x1b.xagent.v1.ListLinksRequest\x1a\x1c.xagent.v1.ListLinksResponse\x12U\n" +
	"\x0eFindLinksByURL\x12 .xagent.v1.FindLinksByURLRequest\x1a!.xagent.v1.FindLinksByURLResponse\x12I\n" +
	"\n" +
	"ListEvents\x12\x1c.xagent.v1.ListEventsRequest\x1a\x1d.xagent.v1.ListEventsResponse\x12L\n" +
	"\vCreateEvent\x12\x1d.xagent.v1.CreateEventRequest\x1a\x1e.xagent.v1.CreateEventResponse\x12C\n" +
	"\bGetEvent\x12\x1a.xagent.v1.GetEventRequest\x1a\x1b.xagent.v1.GetEventResponse\x12L\n" +
	"\vDeleteEvent\x12\x1d.xagent.v1.DeleteEventRequest\x1a\x1e.xagent.v1.DeleteEventResponse\x12O\n" +
	"\fAddEventTask\x12\x1e.xagent.v1.AddEventTaskRequest\x1a\x1f.xagent.v1.AddEventTaskResponse\x12X\n" +
	"\x0fRemoveEventTask\x12!.xagent.v1.RemoveEventTaskRequest\x1a\".xagent.v1.RemoveEventTaskResponse\x12U\n" +
	"\x0eListEventTasks\x12 .xagent.v1.ListEventTasksRequest\x1a!.xagent.v1.ListEventTasksResponse\x12[\n" +
	"\x10ListEventsByTask\x12\".xagent.v1.ListEventsByTaskRequest\x1a#.xagent.v1.ListEventsByTaskResponse\x12O\n" +
	"\fProcessEvent\x12\x1e.xagent.v1.ProcessEventRequest\x1a\x1f.xagent.v1.ProcessEventResponseB<Z:github.com/icholy/xagent/internal/proto/xagent/v1;xagentv1b\x06proto3"

var (
	file_xagent_v1_xagent_proto_rawDescOnce sync.Once
	file_xagent_v1_xagent_proto_rawDescData []byte
)

func file_xagent_v1_xagent_proto_rawDescGZIP() []byte {
	file_xagent_v1_xagent_proto_rawDescOnce.Do(func() {
		file_xagent_v1_xagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xagent_v1_xagent_proto_rawDesc), len(file_xagent_v1_xagent_proto_rawDesc)))
	})
	return file_xagent_v1_xagent_proto_rawDescData
}

var file_xagent_v1_xagent_proto_msgTypes = make([]protoimpl.MessageInfo, 49)
var file_xagent_v1_xagent_proto_goTypes = []any{
	(*Instruction)(nil),              // 0: xagent.v1.Instruction
	(*Task)(nil),                     // 1: xagent.v1.Task
	(*McpServer)(nil),                // 2: xagent.v1.McpServer
	(*ListTasksRequest)(nil),         // 3: xagent.v1.ListTasksRequest
	(*ListTasksResponse)(nil),        // 4: xagent.v1.ListTasksResponse
	(*ListChildTasksRequest)(nil),    // 5: xagent.v1.ListChildTasksRequest
	(*ListChildTasksResponse)(nil),   // 6: xagent.v1.ListChildTasksResponse
	(*CreateTaskRequest)(nil),        // 7: xagent.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),       // 8: xagent.v1.CreateTaskResponse
	(*GetTaskRequest)(nil),           // 9: xagent.v1.GetTaskRequest
	(*GetTaskResponse)(nil),          // 10: xagent.v1.GetTaskResponse
	(*GetTaskDetailsRequest)(nil),    // 11: xagent.v1.GetTaskDetailsRequest
	(*GetTaskDetailsResponse)(nil),   // 12: xagent.v1.GetTaskDetailsResponse
	(*UpdateTaskRequest)(nil),        // 13: xagent.v1.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),       // 14: xagent.v1.UpdateTaskResponse
	(*DeleteTaskRequest)(nil),        // 15: xagent.v1.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),       // 16: xagent.v1.DeleteTaskResponse
	(*LogEntry)(nil),                 // 17: xagent.v1.LogEntry
	(*UploadLogsRequest)(nil),        // 18: xagent.v1.UploadLogsRequest
	(*UploadLogsResponse)(nil),       // 19: xagent.v1.UploadLogsResponse
	(*ListLogsRequest)(nil),          // 20: xagent.v1.ListLogsRequest
	(*ListLogsResponse)(nil),         // 21: xagent.v1.ListLogsResponse
	(*TaskLink)(nil),                 // 22: xagent.v1.TaskLink
	(*CreateLinkRequest)(nil),        // 23: xagent.v1.CreateLinkRequest
	(*CreateLinkResponse)(nil),       // 24: xagent.v1.CreateLinkResponse
	(*ListLinksRequest)(nil),         // 25: xagent.v1.ListLinksRequest
	(*ListLinksResponse)(nil),        // 26: xagent.v1.ListLinksResponse
	(*FindLinksByURLRequest)(nil),    // 27: xagent.v1.FindLinksByURLRequest
	(*FindLinksByURLResponse)(nil),   // 28: xagent.v1.FindLinksByURLResponse
	(*Event)(nil),                    // 29: xagent.v1.Event
	(*ListEventsRequest)(nil),        // 30: xagent.v1.ListEventsRequest
	(*ListEventsResponse)(nil),       // 31: xagent.v1.ListEventsResponse
	(*CreateEventRequest)(nil),       // 32: xagent.v1.CreateEventRequest
	(*CreateEventResponse)(nil),      // 33: xagent.v1.CreateEventResponse
	(*GetEventRequest)(nil),          // 34: xagent.v1.GetEventRequest
	(*GetEventResponse)(nil),         // 35: xagent.v1.GetEventResponse
	(*DeleteEventRequest)(nil),       // 36: xagent.v1.DeleteEventRequest
	(*DeleteEventResponse)(nil),      // 37: xagent.v1.DeleteEventResponse
	(*AddEventTaskRequest)(nil),      // 38: xagent.v1.AddEventTaskRequest
	(*AddEventTaskResponse)(nil),     // 39: xagent.v1.AddEventTaskResponse
	(*RemoveEventTaskRequest)(nil),   // 40: xagent.v1.RemoveEventTaskRequest
	(*RemoveEventTaskResponse)(nil),  // 41: xagent.v1.RemoveEventTaskResponse
	(*ListEventTasksRequest)(nil),    // 42: xagent.v1.ListEventTasksRequest
	(*ListEventTasksResponse)(nil),   // 43: xagent.v1.ListEventTasksResponse
	(*ListEventsByTaskRequest)(nil),  // 44: xagent.v1.ListEventsByTaskRequest
	(*ListEventsByTaskResponse)(nil), // 45: xagent.v1.ListEventsByTaskResponse
	(*ProcessEventRequest)(nil),      // 46: xagent.v1.ProcessEventRequest
	(*ProcessEventResponse)(nil),     // 47: xagent.v1.ProcessEventResponse
	nil,                              // 48: xagent.v1.McpServer.EnvEntry
	(*timestamppb.Timestamp)(nil),    // 49: google.protobuf.Timestamp
}
var file_xagent_v1_xagent_proto_depIdxs = []int32{
	0,  // 0: xagent.v1.Task.instructions:type_name -> xagent.v1.Instruction
	49, // 1: xagent.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	49, // 2: xagent.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	48, // 3: xagent.v1.McpServer.env:type_name -> xagent.v1.McpServer.EnvEntry
	1,  // 4: xagent.v1.ListTasksResponse.tasks:type_name -> xagent.v1.Task
	1,  // 5: xagent.v1.ListChildTasksResponse.tasks:type_name -> xagent.v1.Task
	0,  // 6: xagent.v1.CreateTaskRequest.instructions:type_name -> xagent.v1.Instruction
	1,  // 7: xagent.v1.CreateTaskResponse.task:type_name -> xagent.v1.Task
	1,  // 8: xagent.v1.GetTaskResponse.task:type_name -> xagent.v1.Task
	1,  // 9: xagent.v1.GetTaskDetailsResponse.task:type_name -> xagent.v1.Task
	1,  // 10: xagent.v1.GetTaskDetailsResponse.children:type_name -> xagent.v1.Task
	29, // 11: xagent.v1.GetTaskDetailsResponse.events:type_name -> xagent.v1.Event
	22, // 12: xagent.v1.GetTaskDetailsResponse.links:type_name -> xagent.v1.TaskLink
	0,  // 13: xagent.v1.UpdateTaskRequest.add_instructions:type_name -> xagent.v1.Instruction
	17, // 14: xagent.v1.UploadLogsRequest.entries:type_name -> xagent.v1.LogEntry
	17, // 15: xagent.v1.ListLogsResponse.entries:type_name -> xagent.v1.LogEntry
	49, // 16: xagent.v1.TaskLink.created_at:type_name -> google.protobuf.Timestamp
	22, // 17: xagent.v1.CreateLinkResponse.link:type_name -> xagent.v1.TaskLink
	22, // 18: xagent.v1.ListLinksResponse.links:type_name -> xagent.v1.TaskLink
	22, // 19: xagent.v1.FindLinksByURLResponse.links:type_name -> xagent.v1.TaskLink
	49, // 20: xagent.v1.Event.created_at:type_name -> google.protobuf.Timestamp
	29, // 21: xagent.v1.ListEventsResponse.events:type_name -> xagent.v1.Event
	29, // 22: xagent.v1.CreateEventResponse.event:type_name -> xagent.v1.Event
	29, // 23: xagent.v1.GetEventResponse.event:type_name -> xagent.v1.Event
	29, // 24: xagent.v1.ListEventsByTaskResponse.events:type_name -> xagent.v1.Event
	3,  // 25: xagent.v1.XAgentService.ListTasks:input_type -> xagent.v1.ListTasksRequest
	5,  // 26: xagent.v1.XAgentService.ListChildTasks:input_type -> xagent.v1.ListChildTasksRequest
	7,  // 27: xagent.v1.XAgentService.CreateTask:input_type -> xagent.v1.CreateTaskRequest
	9,  // 28: xagent.v1.XAgentService.GetTask:input_type -> xagent.v1.GetTaskRequest
	11, // 29: xagent.v1.XAgentService.GetTaskDetails:input_type -> xagent.v1.GetTaskDetailsRequest
	13, // 30: xagent.v1.XAgentService.UpdateTask:input_type -> xagent.v1.UpdateTaskRequest
	15, // 31: xagent.v1.XAgentService.DeleteTask:input_type -> xagent.v1.DeleteTaskRequest
	18, // 32: xagent.v1.XAgentService.UploadLogs:input_type -> xagent.v1.UploadLogsRequest
	20, // 33: xagent.v1.XAgentService.ListLogs:input_type -> xagent.v1.ListLogsRequest
	23, // 34: xagent.v1.XAgentService.CreateLink:input_type -> xagent.v1.CreateLinkRequest
	25, // 35: xagent.v1.XAgentService.ListLinks:input_type -> xagent.v1.ListLinksRequest
	27, // 36: xagent.v1.XAgentService.FindLinksByURL:input_type -> xagent.v1.FindLinksByURLRequest
	30, // 37: xagent.v1.XAgentService.ListEvents:input_type -> xagent.v1.ListEventsRequest
	32, // 38: xagent.v1.XAgentService.CreateEvent:input_type -> xagent.v1.CreateEventRequest
	34, // 39: xagent.v1.XAgentService.GetEvent:input_type -> xagent.v1.GetEventRequest
	36, // 40: xagent.v1.XAgentService.DeleteEvent:input_type -> xagent.v1.DeleteEventRequest
	38, // 41: xagent.v1.XAgentService.AddEventTask:input_type -> xagent.v1.AddEventTaskRequest
	40, // 42: xagent.v1.XAgentService.RemoveEventTask:input_type -> xagent.v1.RemoveEventTaskRequest
	42, // 43: xagent.v1.XAgentService.ListEventTasks:input_type -> xagent.v1.ListEventTasksRequest
	44, // 44: xagent.v1.XAgentService.ListEventsByTask:input_type -> xagent.v1.ListEventsByTaskRequest
	46, // 45: xagent.v1.XAgentService.ProcessEvent:input_type -> xagent.v1.ProcessEventRequest
	4,  // 46: xagent.v1.XAgentService.ListTasks:output_type -> xagent.v1.ListTasksResponse
	6,  // 47: xagent.v1.XAgentService.ListChildTasks:output_type -> xagent.v1.ListChildTasksResponse
	8,  // 48: xagent.v1.XAgentService.CreateTask:output_type -> xagent.v1.CreateTaskResponse
	10, // 49: xagent.v1.XAgentService.GetTask:output_type -> xagent.v1.GetTaskResponse
	12, // 50: xagent.v1.XAgentService.GetTaskDetails:output_type -> xagent.v1.GetTaskDetailsResponse
	14, // 51: xagent.v1.XAgentService.UpdateTask:output_type -> xagent.v1.UpdateTaskResponse
	16, // 52: xagent.v1.XAgentService.DeleteTask:output_type -> xagent.v1.DeleteTaskResponse
	19, // 53: xagent.v1.XAgentService.UploadLogs:output_type -> xagent.v1.UploadLogsResponse
	21, // 54: xagent.v1.XAgentService.ListLogs:output_type -> xagent.v1.ListLogsResponse
	24, // 55: xagent.v1.XAgentService.CreateLink:output_type -> xagent.v1.CreateLinkResponse
	26, // 56: xagent.v1.XAgentService.ListLinks:output_type -> xagent.v1.ListLinksResponse
	28, // 57: xagent.v1.XAgentService.FindLinksByURL:output_type -> xagent.v1.FindLinksByURLResponse
	31, // 58: xagent.v1.XAgentService.ListEvents:output_type -> xagent.v1.ListEventsResponse
	33, // 59: xagent.v1.XAgentService.CreateEvent:output_type -> xagent.v1.CreateEventResponse
	35, // 60: xagent.v1.XAgentService.GetEvent:output_type -> xagent.v1.GetEventResponse
	37, // 61: xagent.v1.XAgentService.DeleteEvent:output_type -> xagent.v1.DeleteEventResponse
	39, // 62: xagent.v1.XAgentService.AddEventTask:output_type -> xagent.v1.AddEventTaskResponse
	41, // 63: xagent.v1.XAgentService.RemoveEventTask:output_type -> xagent.v1.RemoveEventTaskResponse
	43, // 64: xagent.v1.XAgentService.ListEventTasks:output_type -> xagent.v1.ListEventTasksResponse
	45, // 65: xagent.v1.XAgentService.ListEventsByTask:output_type -> xagent.v1.ListEventsByTaskResponse
	47, // 66: xagent.v1.XAgentService.ProcessEvent:output_type -> xagent.v1.ProcessEventResponse
	46, // [46:67] is the sub-list for method output_type
	25, // [25:46] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_xagent_v1_xagent_proto_init() }
func file_xagent_v1_xagent_proto_init() {
	if File_xagent_v1_xagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xagent_v1_xagent_proto_rawDesc), len(file_xagent_v1_xagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   49,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xagent_v1_xagent_proto_goTypes,
		DependencyIndexes: file_xagent_v1_xagent_proto_depIdxs,
		MessageInfos:      file_xagent_v1_xagent_proto_msgTypes,
	}.Build()
	File_xagent_v1_xagent_proto = out.File
	file_xagent_v1_xagent_proto_goTypes = nil
	file_xagent_v1_xagent_proto_depIdxs = nil
}
