// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mcpbridge

import (
	"context"
	"github.com/icholy/xagent/internal/x/mcpchannel"
	"sync"
)

// Ensure, that ChannelSenderMock does implement ChannelSender.
// If this is not the case, regenerate this file with moq.
var _ ChannelSender = &ChannelSenderMock{}

// ChannelSenderMock is a mock implementation of ChannelSender.
//
//	func TestSomethingThatUsesChannelSender(t *testing.T) {
//
//		// make and configure a mocked ChannelSender
//		mockedChannelSender := &ChannelSenderMock{
//			SendChannelFunc: func(ctx context.Context, p mcpchannel.Params) error {
//				panic("mock out the SendChannel method")
//			},
//		}
//
//		// use mockedChannelSender in code that requires ChannelSender
//		// and then make assertions.
//
//	}
type ChannelSenderMock struct {
	// SendChannelFunc mocks the SendChannel method.
	SendChannelFunc func(ctx context.Context, p mcpchannel.Params) error

	// calls tracks calls to the methods.
	calls struct {
		// SendChannel holds details about calls to the SendChannel method.
		SendChannel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P mcpchannel.Params
		}
	}
	lockSendChannel sync.RWMutex
}

// SendChannel calls SendChannelFunc.
func (mock *ChannelSenderMock) SendChannel(ctx context.Context, p mcpchannel.Params) error {
	if mock.SendChannelFunc == nil {
		panic("ChannelSenderMock.SendChannelFunc: method is nil but ChannelSender.SendChannel was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   mcpchannel.Params
	}{
		Ctx: ctx,
		P:   p,
	}
	mock.lockSendChannel.Lock()
	mock.calls.SendChannel = append(mock.calls.SendChannel, callInfo)
	mock.lockSendChannel.Unlock()
	return mock.SendChannelFunc(ctx, p)
}

// SendChannelCalls gets all the calls that were made to SendChannel.
// Check the length with:
//
//	len(mockedChannelSender.SendChannelCalls())
func (mock *ChannelSenderMock) SendChannelCalls() []struct {
	Ctx context.Context
	P   mcpchannel.Params
} {
	var calls []struct {
		Ctx context.Context
		P   mcpchannel.Params
	}
	mock.lockSendChannel.RLock()
	calls = mock.calls.SendChannel
	mock.lockSendChannel.RUnlock()
	return calls
}
