// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package eventrouter

import (
	"context"
	"database/sql"
	"github.com/icholy/xagent/internal/model"
	"github.com/icholy/xagent/internal/store"
	"sync"
)

// Ensure, that StoreMock does implement Store.
// If this is not the case, regenerate this file with moq.
var _ Store = &StoreMock{}

// StoreMock is a mock implementation of Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked Store
//		mockedStore := &StoreMock{
//			AddEventTaskFunc: func(ctx context.Context, tx *sql.Tx, eventID int64, taskID int64) error {
//				panic("mock out the AddEventTask method")
//			},
//			CreateEventFunc: func(ctx context.Context, tx *sql.Tx, event *model.Event) error {
//				panic("mock out the CreateEvent method")
//			},
//			CreateLogFunc: func(ctx context.Context, tx *sql.Tx, log *model.Log) error {
//				panic("mock out the CreateLog method")
//			},
//			FindSubscribedLinksByURLForUserFunc: func(ctx context.Context, tx *sql.Tx, url string, userID string) ([]store.LinkWithOrg, error) {
//				panic("mock out the FindSubscribedLinksByURLForUser method")
//			},
//			GetTaskForUpdateFunc: func(ctx context.Context, tx *sql.Tx, id int64, orgID int64) (*model.Task, error) {
//				panic("mock out the GetTaskForUpdate method")
//			},
//			UpdateTaskFunc: func(ctx context.Context, tx *sql.Tx, task *model.Task) error {
//				panic("mock out the UpdateTask method")
//			},
//			WithTxFunc: func(ctx context.Context, tx *sql.Tx, f func(tx *sql.Tx) error) error {
//				panic("mock out the WithTx method")
//			},
//		}
//
//		// use mockedStore in code that requires Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// AddEventTaskFunc mocks the AddEventTask method.
	AddEventTaskFunc func(ctx context.Context, tx *sql.Tx, eventID int64, taskID int64) error

	// CreateEventFunc mocks the CreateEvent method.
	CreateEventFunc func(ctx context.Context, tx *sql.Tx, event *model.Event) error

	// CreateLogFunc mocks the CreateLog method.
	CreateLogFunc func(ctx context.Context, tx *sql.Tx, log *model.Log) error

	// FindSubscribedLinksByURLForUserFunc mocks the FindSubscribedLinksByURLForUser method.
	FindSubscribedLinksByURLForUserFunc func(ctx context.Context, tx *sql.Tx, url string, userID string) ([]store.LinkWithOrg, error)

	// GetTaskForUpdateFunc mocks the GetTaskForUpdate method.
	GetTaskForUpdateFunc func(ctx context.Context, tx *sql.Tx, id int64, orgID int64) (*model.Task, error)

	// UpdateTaskFunc mocks the UpdateTask method.
	UpdateTaskFunc func(ctx context.Context, tx *sql.Tx, task *model.Task) error

	// WithTxFunc mocks the WithTx method.
	WithTxFunc func(ctx context.Context, tx *sql.Tx, f func(tx *sql.Tx) error) error

	// calls tracks calls to the methods.
	calls struct {
		// AddEventTask holds details about calls to the AddEventTask method.
		AddEventTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// EventID is the eventID argument value.
			EventID int64
			// TaskID is the taskID argument value.
			TaskID int64
		}
		// CreateEvent holds details about calls to the CreateEvent method.
		CreateEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// Event is the event argument value.
			Event *model.Event
		}
		// CreateLog holds details about calls to the CreateLog method.
		CreateLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// Log is the log argument value.
			Log *model.Log
		}
		// FindSubscribedLinksByURLForUser holds details about calls to the FindSubscribedLinksByURLForUser method.
		FindSubscribedLinksByURLForUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// URL is the url argument value.
			URL string
			// UserID is the userID argument value.
			UserID string
		}
		// GetTaskForUpdate holds details about calls to the GetTaskForUpdate method.
		GetTaskForUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// ID is the id argument value.
			ID int64
			// OrgID is the orgID argument value.
			OrgID int64
		}
		// UpdateTask holds details about calls to the UpdateTask method.
		UpdateTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// Task is the task argument value.
			Task *model.Task
		}
		// WithTx holds details about calls to the WithTx method.
		WithTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// F is the f argument value.
			F func(tx *sql.Tx) error
		}
	}
	lockAddEventTask                    sync.RWMutex
	lockCreateEvent                     sync.RWMutex
	lockCreateLog                       sync.RWMutex
	lockFindSubscribedLinksByURLForUser sync.RWMutex
	lockGetTaskForUpdate                sync.RWMutex
	lockUpdateTask                      sync.RWMutex
	lockWithTx                          sync.RWMutex
}

// AddEventTask calls AddEventTaskFunc.
func (mock *StoreMock) AddEventTask(ctx context.Context, tx *sql.Tx, eventID int64, taskID int64) error {
	if mock.AddEventTaskFunc == nil {
		panic("StoreMock.AddEventTaskFunc: method is nil but Store.AddEventTask was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Tx      *sql.Tx
		EventID int64
		TaskID  int64
	}{
		Ctx:     ctx,
		Tx:      tx,
		EventID: eventID,
		TaskID:  taskID,
	}
	mock.lockAddEventTask.Lock()
	mock.calls.AddEventTask = append(mock.calls.AddEventTask, callInfo)
	mock.lockAddEventTask.Unlock()
	return mock.AddEventTaskFunc(ctx, tx, eventID, taskID)
}

// AddEventTaskCalls gets all the calls that were made to AddEventTask.
// Check the length with:
//
//	len(mockedStore.AddEventTaskCalls())
func (mock *StoreMock) AddEventTaskCalls() []struct {
	Ctx     context.Context
	Tx      *sql.Tx
	EventID int64
	TaskID  int64
} {
	var calls []struct {
		Ctx     context.Context
		Tx      *sql.Tx
		EventID int64
		TaskID  int64
	}
	mock.lockAddEventTask.RLock()
	calls = mock.calls.AddEventTask
	mock.lockAddEventTask.RUnlock()
	return calls
}

// CreateEvent calls CreateEventFunc.
func (mock *StoreMock) CreateEvent(ctx context.Context, tx *sql.Tx, event *model.Event) error {
	if mock.CreateEventFunc == nil {
		panic("StoreMock.CreateEventFunc: method is nil but Store.CreateEvent was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Tx    *sql.Tx
		Event *model.Event
	}{
		Ctx:   ctx,
		Tx:    tx,
		Event: event,
	}
	mock.lockCreateEvent.Lock()
	mock.calls.CreateEvent = append(mock.calls.CreateEvent, callInfo)
	mock.lockCreateEvent.Unlock()
	return mock.CreateEventFunc(ctx, tx, event)
}

// CreateEventCalls gets all the calls that were made to CreateEvent.
// Check the length with:
//
//	len(mockedStore.CreateEventCalls())
func (mock *StoreMock) CreateEventCalls() []struct {
	Ctx   context.Context
	Tx    *sql.Tx
	Event *model.Event
} {
	var calls []struct {
		Ctx   context.Context
		Tx    *sql.Tx
		Event *model.Event
	}
	mock.lockCreateEvent.RLock()
	calls = mock.calls.CreateEvent
	mock.lockCreateEvent.RUnlock()
	return calls
}

// CreateLog calls CreateLogFunc.
func (mock *StoreMock) CreateLog(ctx context.Context, tx *sql.Tx, log *model.Log) error {
	if mock.CreateLogFunc == nil {
		panic("StoreMock.CreateLogFunc: method is nil but Store.CreateLog was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Tx  *sql.Tx
		Log *model.Log
	}{
		Ctx: ctx,
		Tx:  tx,
		Log: log,
	}
	mock.lockCreateLog.Lock()
	mock.calls.CreateLog = append(mock.calls.CreateLog, callInfo)
	mock.lockCreateLog.Unlock()
	return mock.CreateLogFunc(ctx, tx, log)
}

// CreateLogCalls gets all the calls that were made to CreateLog.
// Check the length with:
//
//	len(mockedStore.CreateLogCalls())
func (mock *StoreMock) CreateLogCalls() []struct {
	Ctx context.Context
	Tx  *sql.Tx
	Log *model.Log
} {
	var calls []struct {
		Ctx context.Context
		Tx  *sql.Tx
		Log *model.Log
	}
	mock.lockCreateLog.RLock()
	calls = mock.calls.CreateLog
	mock.lockCreateLog.RUnlock()
	return calls
}

// FindSubscribedLinksByURLForUser calls FindSubscribedLinksByURLForUserFunc.
func (mock *StoreMock) FindSubscribedLinksByURLForUser(ctx context.Context, tx *sql.Tx, url string, userID string) ([]store.LinkWithOrg, error) {
	if mock.FindSubscribedLinksByURLForUserFunc == nil {
		panic("StoreMock.FindSubscribedLinksByURLForUserFunc: method is nil but Store.FindSubscribedLinksByURLForUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Tx     *sql.Tx
		URL    string
		UserID string
	}{
		Ctx:    ctx,
		Tx:     tx,
		URL:    url,
		UserID: userID,
	}
	mock.lockFindSubscribedLinksByURLForUser.Lock()
	mock.calls.FindSubscribedLinksByURLForUser = append(mock.calls.FindSubscribedLinksByURLForUser, callInfo)
	mock.lockFindSubscribedLinksByURLForUser.Unlock()
	return mock.FindSubscribedLinksByURLForUserFunc(ctx, tx, url, userID)
}

// FindSubscribedLinksByURLForUserCalls gets all the calls that were made to FindSubscribedLinksByURLForUser.
// Check the length with:
//
//	len(mockedStore.FindSubscribedLinksByURLForUserCalls())
func (mock *StoreMock) FindSubscribedLinksByURLForUserCalls() []struct {
	Ctx    context.Context
	Tx     *sql.Tx
	URL    string
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		Tx     *sql.Tx
		URL    string
		UserID string
	}
	mock.lockFindSubscribedLinksByURLForUser.RLock()
	calls = mock.calls.FindSubscribedLinksByURLForUser
	mock.lockFindSubscribedLinksByURLForUser.RUnlock()
	return calls
}

// GetTaskForUpdate calls GetTaskForUpdateFunc.
func (mock *StoreMock) GetTaskForUpdate(ctx context.Context, tx *sql.Tx, id int64, orgID int64) (*model.Task, error) {
	if mock.GetTaskForUpdateFunc == nil {
		panic("StoreMock.GetTaskForUpdateFunc: method is nil but Store.GetTaskForUpdate was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Tx    *sql.Tx
		ID    int64
		OrgID int64
	}{
		Ctx:   ctx,
		Tx:    tx,
		ID:    id,
		OrgID: orgID,
	}
	mock.lockGetTaskForUpdate.Lock()
	mock.calls.GetTaskForUpdate = append(mock.calls.GetTaskForUpdate, callInfo)
	mock.lockGetTaskForUpdate.Unlock()
	return mock.GetTaskForUpdateFunc(ctx, tx, id, orgID)
}

// GetTaskForUpdateCalls gets all the calls that were made to GetTaskForUpdate.
// Check the length with:
//
//	len(mockedStore.GetTaskForUpdateCalls())
func (mock *StoreMock) GetTaskForUpdateCalls() []struct {
	Ctx   context.Context
	Tx    *sql.Tx
	ID    int64
	OrgID int64
} {
	var calls []struct {
		Ctx   context.Context
		Tx    *sql.Tx
		ID    int64
		OrgID int64
	}
	mock.lockGetTaskForUpdate.RLock()
	calls = mock.calls.GetTaskForUpdate
	mock.lockGetTaskForUpdate.RUnlock()
	return calls
}

// UpdateTask calls UpdateTaskFunc.
func (mock *StoreMock) UpdateTask(ctx context.Context, tx *sql.Tx, task *model.Task) error {
	if mock.UpdateTaskFunc == nil {
		panic("StoreMock.UpdateTaskFunc: method is nil but Store.UpdateTask was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Tx   *sql.Tx
		Task *model.Task
	}{
		Ctx:  ctx,
		Tx:   tx,
		Task: task,
	}
	mock.lockUpdateTask.Lock()
	mock.calls.UpdateTask = append(mock.calls.UpdateTask, callInfo)
	mock.lockUpdateTask.Unlock()
	return mock.UpdateTaskFunc(ctx, tx, task)
}

// UpdateTaskCalls gets all the calls that were made to UpdateTask.
// Check the length with:
//
//	len(mockedStore.UpdateTaskCalls())
func (mock *StoreMock) UpdateTaskCalls() []struct {
	Ctx  context.Context
	Tx   *sql.Tx
	Task *model.Task
} {
	var calls []struct {
		Ctx  context.Context
		Tx   *sql.Tx
		Task *model.Task
	}
	mock.lockUpdateTask.RLock()
	calls = mock.calls.UpdateTask
	mock.lockUpdateTask.RUnlock()
	return calls
}

// WithTx calls WithTxFunc.
func (mock *StoreMock) WithTx(ctx context.Context, tx *sql.Tx, f func(tx *sql.Tx) error) error {
	if mock.WithTxFunc == nil {
		panic("StoreMock.WithTxFunc: method is nil but Store.WithTx was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Tx  *sql.Tx
		F   func(tx *sql.Tx) error
	}{
		Ctx: ctx,
		Tx:  tx,
		F:   f,
	}
	mock.lockWithTx.Lock()
	mock.calls.WithTx = append(mock.calls.WithTx, callInfo)
	mock.lockWithTx.Unlock()
	return mock.WithTxFunc(ctx, tx, f)
}

// WithTxCalls gets all the calls that were made to WithTx.
// Check the length with:
//
//	len(mockedStore.WithTxCalls())
func (mock *StoreMock) WithTxCalls() []struct {
	Ctx context.Context
	Tx  *sql.Tx
	F   func(tx *sql.Tx) error
} {
	var calls []struct {
		Ctx context.Context
		Tx  *sql.Tx
		F   func(tx *sql.Tx) error
	}
	mock.lockWithTx.RLock()
	calls = mock.calls.WithTx
	mock.lockWithTx.RUnlock()
	return calls
}
