// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package githubserver

import (
	"context"
	"database/sql"
	"github.com/icholy/xagent/internal/model"
	"sync"
)

// Ensure, that StoreMock does implement Store.
// If this is not the case, regenerate this file with moq.
var _ Store = &StoreMock{}

// StoreMock is a mock implementation of Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked Store
//		mockedStore := &StoreMock{
//			ClearGitHubInstallationFunc: func(ctx context.Context, tx *sql.Tx, installationID int64) error {
//				panic("mock out the ClearGitHubInstallation method")
//			},
//			GetUserByGitHubUserIDFunc: func(ctx context.Context, tx *sql.Tx, githubUserID int64) (*model.User, error) {
//				panic("mock out the GetUserByGitHubUserID method")
//			},
//			ListOrgIDsByGitHubInstallationFunc: func(ctx context.Context, tx *sql.Tx, installationID int64) ([]int64, error) {
//				panic("mock out the ListOrgIDsByGitHubInstallation method")
//			},
//			UpdateGitHubUsernameFunc: func(ctx context.Context, tx *sql.Tx, githubUserID int64, username string) error {
//				panic("mock out the UpdateGitHubUsername method")
//			},
//		}
//
//		// use mockedStore in code that requires Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// ClearGitHubInstallationFunc mocks the ClearGitHubInstallation method.
	ClearGitHubInstallationFunc func(ctx context.Context, tx *sql.Tx, installationID int64) error

	// GetUserByGitHubUserIDFunc mocks the GetUserByGitHubUserID method.
	GetUserByGitHubUserIDFunc func(ctx context.Context, tx *sql.Tx, githubUserID int64) (*model.User, error)

	// ListOrgIDsByGitHubInstallationFunc mocks the ListOrgIDsByGitHubInstallation method.
	ListOrgIDsByGitHubInstallationFunc func(ctx context.Context, tx *sql.Tx, installationID int64) ([]int64, error)

	// UpdateGitHubUsernameFunc mocks the UpdateGitHubUsername method.
	UpdateGitHubUsernameFunc func(ctx context.Context, tx *sql.Tx, githubUserID int64, username string) error

	// calls tracks calls to the methods.
	calls struct {
		// ClearGitHubInstallation holds details about calls to the ClearGitHubInstallation method.
		ClearGitHubInstallation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// InstallationID is the installationID argument value.
			InstallationID int64
		}
		// GetUserByGitHubUserID holds details about calls to the GetUserByGitHubUserID method.
		GetUserByGitHubUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// GithubUserID is the githubUserID argument value.
			GithubUserID int64
		}
		// ListOrgIDsByGitHubInstallation holds details about calls to the ListOrgIDsByGitHubInstallation method.
		ListOrgIDsByGitHubInstallation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// InstallationID is the installationID argument value.
			InstallationID int64
		}
		// UpdateGitHubUsername holds details about calls to the UpdateGitHubUsername method.
		UpdateGitHubUsername []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx *sql.Tx
			// GithubUserID is the githubUserID argument value.
			GithubUserID int64
			// Username is the username argument value.
			Username string
		}
	}
	lockClearGitHubInstallation        sync.RWMutex
	lockGetUserByGitHubUserID          sync.RWMutex
	lockListOrgIDsByGitHubInstallation sync.RWMutex
	lockUpdateGitHubUsername           sync.RWMutex
}

// ClearGitHubInstallation calls ClearGitHubInstallationFunc.
func (mock *StoreMock) ClearGitHubInstallation(ctx context.Context, tx *sql.Tx, installationID int64) error {
	if mock.ClearGitHubInstallationFunc == nil {
		panic("StoreMock.ClearGitHubInstallationFunc: method is nil but Store.ClearGitHubInstallation was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Tx             *sql.Tx
		InstallationID int64
	}{
		Ctx:            ctx,
		Tx:             tx,
		InstallationID: installationID,
	}
	mock.lockClearGitHubInstallation.Lock()
	mock.calls.ClearGitHubInstallation = append(mock.calls.ClearGitHubInstallation, callInfo)
	mock.lockClearGitHubInstallation.Unlock()
	return mock.ClearGitHubInstallationFunc(ctx, tx, installationID)
}

// ClearGitHubInstallationCalls gets all the calls that were made to ClearGitHubInstallation.
// Check the length with:
//
//	len(mockedStore.ClearGitHubInstallationCalls())
func (mock *StoreMock) ClearGitHubInstallationCalls() []struct {
	Ctx            context.Context
	Tx             *sql.Tx
	InstallationID int64
} {
	var calls []struct {
		Ctx            context.Context
		Tx             *sql.Tx
		InstallationID int64
	}
	mock.lockClearGitHubInstallation.RLock()
	calls = mock.calls.ClearGitHubInstallation
	mock.lockClearGitHubInstallation.RUnlock()
	return calls
}

// GetUserByGitHubUserID calls GetUserByGitHubUserIDFunc.
func (mock *StoreMock) GetUserByGitHubUserID(ctx context.Context, tx *sql.Tx, githubUserID int64) (*model.User, error) {
	if mock.GetUserByGitHubUserIDFunc == nil {
		panic("StoreMock.GetUserByGitHubUserIDFunc: method is nil but Store.GetUserByGitHubUserID was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Tx           *sql.Tx
		GithubUserID int64
	}{
		Ctx:          ctx,
		Tx:           tx,
		GithubUserID: githubUserID,
	}
	mock.lockGetUserByGitHubUserID.Lock()
	mock.calls.GetUserByGitHubUserID = append(mock.calls.GetUserByGitHubUserID, callInfo)
	mock.lockGetUserByGitHubUserID.Unlock()
	return mock.GetUserByGitHubUserIDFunc(ctx, tx, githubUserID)
}

// GetUserByGitHubUserIDCalls gets all the calls that were made to GetUserByGitHubUserID.
// Check the length with:
//
//	len(mockedStore.GetUserByGitHubUserIDCalls())
func (mock *StoreMock) GetUserByGitHubUserIDCalls() []struct {
	Ctx          context.Context
	Tx           *sql.Tx
	GithubUserID int64
} {
	var calls []struct {
		Ctx          context.Context
		Tx           *sql.Tx
		GithubUserID int64
	}
	mock.lockGetUserByGitHubUserID.RLock()
	calls = mock.calls.GetUserByGitHubUserID
	mock.lockGetUserByGitHubUserID.RUnlock()
	return calls
}

// ListOrgIDsByGitHubInstallation calls ListOrgIDsByGitHubInstallationFunc.
func (mock *StoreMock) ListOrgIDsByGitHubInstallation(ctx context.Context, tx *sql.Tx, installationID int64) ([]int64, error) {
	if mock.ListOrgIDsByGitHubInstallationFunc == nil {
		panic("StoreMock.ListOrgIDsByGitHubInstallationFunc: method is nil but Store.ListOrgIDsByGitHubInstallation was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Tx             *sql.Tx
		InstallationID int64
	}{
		Ctx:            ctx,
		Tx:             tx,
		InstallationID: installationID,
	}
	mock.lockListOrgIDsByGitHubInstallation.Lock()
	mock.calls.ListOrgIDsByGitHubInstallation = append(mock.calls.ListOrgIDsByGitHubInstallation, callInfo)
	mock.lockListOrgIDsByGitHubInstallation.Unlock()
	return mock.ListOrgIDsByGitHubInstallationFunc(ctx, tx, installationID)
}

// ListOrgIDsByGitHubInstallationCalls gets all the calls that were made to ListOrgIDsByGitHubInstallation.
// Check the length with:
//
//	len(mockedStore.ListOrgIDsByGitHubInstallationCalls())
func (mock *StoreMock) ListOrgIDsByGitHubInstallationCalls() []struct {
	Ctx            context.Context
	Tx             *sql.Tx
	InstallationID int64
} {
	var calls []struct {
		Ctx            context.Context
		Tx             *sql.Tx
		InstallationID int64
	}
	mock.lockListOrgIDsByGitHubInstallation.RLock()
	calls = mock.calls.ListOrgIDsByGitHubInstallation
	mock.lockListOrgIDsByGitHubInstallation.RUnlock()
	return calls
}

// UpdateGitHubUsername calls UpdateGitHubUsernameFunc.
func (mock *StoreMock) UpdateGitHubUsername(ctx context.Context, tx *sql.Tx, githubUserID int64, username string) error {
	if mock.UpdateGitHubUsernameFunc == nil {
		panic("StoreMock.UpdateGitHubUsernameFunc: method is nil but Store.UpdateGitHubUsername was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Tx           *sql.Tx
		GithubUserID int64
		Username     string
	}{
		Ctx:          ctx,
		Tx:           tx,
		GithubUserID: githubUserID,
		Username:     username,
	}
	mock.lockUpdateGitHubUsername.Lock()
	mock.calls.UpdateGitHubUsername = append(mock.calls.UpdateGitHubUsername, callInfo)
	mock.lockUpdateGitHubUsername.Unlock()
	return mock.UpdateGitHubUsernameFunc(ctx, tx, githubUserID, username)
}

// UpdateGitHubUsernameCalls gets all the calls that were made to UpdateGitHubUsername.
// Check the length with:
//
//	len(mockedStore.UpdateGitHubUsernameCalls())
func (mock *StoreMock) UpdateGitHubUsernameCalls() []struct {
	Ctx          context.Context
	Tx           *sql.Tx
	GithubUserID int64
	Username     string
} {
	var calls []struct {
		Ctx          context.Context
		Tx           *sql.Tx
		GithubUserID int64
		Username     string
	}
	mock.lockUpdateGitHubUsername.RLock()
	calls = mock.calls.UpdateGitHubUsername
	mock.lockUpdateGitHubUsername.RUnlock()
	return calls
}
