// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package sqlc

import (
	"context"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (description, data, url, created_at, org_id, task_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateEventParams struct {
	Description string    `json:"description"`
	Data        string    `json:"data"`
	Url         string    `json:"url"`
	CreatedAt   time.Time `json:"created_at"`
	OrgID       int64     `json:"org_id"`
	TaskID      int64     `json:"task_id"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Description,
		arg.Data,
		arg.Url,
		arg.CreatedAt,
		arg.OrgID,
		arg.TaskID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1 AND org_id = $2
`

type DeleteEventParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, arg.ID, arg.OrgID)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, description, data, url, org_id, created_at, task_id
FROM events
WHERE id = $1 AND org_id = $2
`

type GetEventParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, arg.ID, arg.OrgID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Data,
		&i.Url,
		&i.OrgID,
		&i.CreatedAt,
		&i.TaskID,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, description, data, url, org_id, created_at, task_id
FROM events
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListEventsParams struct {
	OrgID int64 `json:"org_id"`
	Limit int32 `json:"limit"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Data,
			&i.Url,
			&i.OrgID,
			&i.CreatedAt,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTask = `-- name: ListEventsByTask :many
SELECT id, description, data, url, org_id, created_at, task_id
FROM events
WHERE task_id = $1 AND org_id = $2
ORDER BY created_at DESC
`

type ListEventsByTaskParams struct {
	TaskID int64 `json:"task_id"`
	OrgID  int64 `json:"org_id"`
}

func (q *Queries) ListEventsByTask(ctx context.Context, arg ListEventsByTaskParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByTask, arg.TaskID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Data,
			&i.Url,
			&i.OrgID,
			&i.CreatedAt,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
