// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (task_id, org_id, type, wake, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateEventParams struct {
	TaskID    int64           `json:"task_id"`
	OrgID     int64           `json:"org_id"`
	Type      string          `json:"type"`
	Wake      bool            `json:"wake"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.TaskID,
		arg.OrgID,
		arg.Type,
		arg.Wake,
		arg.Payload,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1 AND org_id = $2
`

type DeleteEventParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, arg.ID, arg.OrgID)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, org_id, created_at, task_id, type, wake, payload
FROM events
WHERE id = $1 AND org_id = $2
`

type GetEventParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, arg.ID, arg.OrgID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedAt,
		&i.TaskID,
		&i.Type,
		&i.Wake,
		&i.Payload,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, org_id, created_at, task_id, type, wake, payload
FROM events
WHERE org_id = $1
  AND (cardinality($3::text[]) = 0 OR type = ANY($3::text[]))
ORDER BY id DESC
LIMIT $2
`

type ListEventsParams struct {
	OrgID int64    `json:"org_id"`
	Limit int32    `json:"limit"`
	Types []string `json:"types"`
}

// The org event feed. The optional types filter ($3) narrows to specific arms —
// an empty/nil array matches all types — mirroring ListEventsByTask. The org
// feed is external-only, so its handler passes types = ['external'] to filter
// out non-external arms (instruction/link/...) that also carry an org_id but are
// not org-feed rows.
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.OrgID, arg.Limit, pq.Array(arg.Types))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CreatedAt,
			&i.TaskID,
			&i.Type,
			&i.Wake,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTask = `-- name: ListEventsByTask :many
SELECT id, org_id, created_at, task_id, type, wake, payload
FROM events
WHERE task_id = $1 AND org_id = $2
  AND (cardinality($3::text[]) = 0 OR type = ANY($3::text[]))
ORDER BY id
`

type ListEventsByTaskParams struct {
	TaskID int64    `json:"task_id"`
	OrgID  int64    `json:"org_id"`
	Types  []string `json:"types"`
}

// A task's events in chronological stream order (ORDER BY id). The optional
// types filter ($3) narrows to specific arms — an empty/nil array matches all
// types — so the same query serves both the full timeline and the agent's brief
// (instruction + external; see proposals/draft/unified-task-event-stream.md
// "The agent's brief").
func (q *Queries) ListEventsByTask(ctx context.Context, arg ListEventsByTaskParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByTask, arg.TaskID, arg.OrgID, pq.Array(arg.Types))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CreatedAt,
			&i.TaskID,
			&i.Type,
			&i.Wake,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
