// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package sqlc

import (
	"context"
	"time"
)

const addEventTask = `-- name: AddEventTask :exec
INSERT INTO event_tasks (event_id, task_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddEventTaskParams struct {
	EventID int64 `json:"event_id"`
	TaskID  int64 `json:"task_id"`
}

func (q *Queries) AddEventTask(ctx context.Context, arg AddEventTaskParams) error {
	_, err := q.db.ExecContext(ctx, addEventTask, arg.EventID, arg.TaskID)
	return err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (description, data, url, owner, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateEventParams struct {
	Description string    `json:"description"`
	Data        string    `json:"data"`
	Url         string    `json:"url"`
	Owner       string    `json:"owner"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Description,
		arg.Data,
		arg.Url,
		arg.Owner,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1 AND owner = $2
`

type DeleteEventParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, arg.ID, arg.Owner)
	return err
}

const deleteEventTasks = `-- name: DeleteEventTasks :exec
DELETE FROM event_tasks WHERE event_id = $1
`

func (q *Queries) DeleteEventTasks(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventTasks, eventID)
	return err
}

const findEventsByURL = `-- name: FindEventsByURL :many
SELECT id, description, data, url, owner, created_at
FROM events
WHERE url = $1
ORDER BY created_at DESC
`

func (q *Queries) FindEventsByURL(ctx context.Context, url string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, findEventsByURL, url)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Data,
			&i.Url,
			&i.Owner,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, description, data, url, owner, created_at
FROM events
WHERE id = $1 AND owner = $2
`

type GetEventParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, arg.ID, arg.Owner)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Data,
		&i.Url,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}

const hasEvent = `-- name: HasEvent :one
SELECT EXISTS(SELECT 1 FROM events WHERE id = $1 AND owner = $2)
`

type HasEventParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) HasEvent(ctx context.Context, arg HasEventParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasEvent, arg.ID, arg.Owner)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEventTasks = `-- name: ListEventTasks :many
SELECT et.task_id
FROM event_tasks et
JOIN tasks t ON et.task_id = t.id
WHERE et.event_id = $1 AND t.owner = $2
`

type ListEventTasksParams struct {
	EventID int64  `json:"event_id"`
	Owner   string `json:"owner"`
}

func (q *Queries) ListEventTasks(ctx context.Context, arg ListEventTasksParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEventTasks, arg.EventID, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var task_id int64
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, description, data, url, owner, created_at
FROM events
WHERE owner = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListEventsParams struct {
	Owner string `json:"owner"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.Owner, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Data,
			&i.Url,
			&i.Owner,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTask = `-- name: ListEventsByTask :many
SELECT e.id, e.description, e.data, e.url, e.owner, e.created_at
FROM events e
JOIN event_tasks et ON e.id = et.event_id
JOIN tasks t ON et.task_id = t.id
WHERE et.task_id = $1 AND t.owner = $2
ORDER BY e.created_at DESC
`

type ListEventsByTaskParams struct {
	TaskID int64  `json:"task_id"`
	Owner  string `json:"owner"`
}

func (q *Queries) ListEventsByTask(ctx context.Context, arg ListEventsByTaskParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByTask, arg.TaskID, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Data,
			&i.Url,
			&i.Owner,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEventTask = `-- name: RemoveEventTask :exec
DELETE FROM event_tasks WHERE event_id = $1 AND task_id = $2
`

type RemoveEventTaskParams struct {
	EventID int64 `json:"event_id"`
	TaskID  int64 `json:"task_id"`
}

func (q *Queries) RemoveEventTask(ctx context.Context, arg RemoveEventTaskParams) error {
	_, err := q.db.ExecContext(ctx, removeEventTask, arg.EventID, arg.TaskID)
	return err
}
