// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: key.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createKey = `-- name: CreateKey :exec
INSERT INTO keys (id, name, token_hash, expires_at, created_at, org_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateKeyParams struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	OrgID     int64        `json:"org_id"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) error {
	_, err := q.db.ExecContext(ctx, createKey,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.OrgID,
	)
	return err
}

const deleteKey = `-- name: DeleteKey :exec
DELETE FROM keys WHERE id = $1 AND org_id = $2
`

type DeleteKeyParams struct {
	ID    string `json:"id"`
	OrgID int64  `json:"org_id"`
}

func (q *Queries) DeleteKey(ctx context.Context, arg DeleteKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteKey, arg.ID, arg.OrgID)
	return err
}

const getKey = `-- name: GetKey :one
SELECT id, name, token_hash, expires_at, created_at, org_id
FROM keys
WHERE id = $1 AND org_id = $2
`

type GetKeyParams struct {
	ID    string `json:"id"`
	OrgID int64  `json:"org_id"`
}

func (q *Queries) GetKey(ctx context.Context, arg GetKeyParams) (Key, error) {
	row := q.db.QueryRowContext(ctx, getKey, arg.ID, arg.OrgID)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.OrgID,
	)
	return i, err
}

const getKeyByHash = `-- name: GetKeyByHash :one
SELECT id, name, token_hash, expires_at, created_at, org_id
FROM keys
WHERE token_hash = $1
`

func (q *Queries) GetKeyByHash(ctx context.Context, tokenHash string) (Key, error) {
	row := q.db.QueryRowContext(ctx, getKeyByHash, tokenHash)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.OrgID,
	)
	return i, err
}

const listKeys = `-- name: ListKeys :many
SELECT id, name, token_hash, expires_at, created_at, org_id
FROM keys
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListKeys(ctx context.Context, orgID int64) ([]Key, error) {
	rows, err := q.db.QueryContext(ctx, listKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Key{}
	for rows.Next() {
		var i Key
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
