// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link.sql

package sqlc

import (
	"context"
	"time"
)

const createLink = `-- name: CreateLink :one
INSERT INTO task_links (task_id, relevance, url, title, subscribe, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateLinkParams struct {
	TaskID    int64     `json:"task_id"`
	Relevance string    `json:"relevance"`
	Url       string    `json:"url"`
	Title     string    `json:"title"`
	Subscribe bool      `json:"subscribe"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLink,
		arg.TaskID,
		arg.Relevance,
		arg.Url,
		arg.Title,
		arg.Subscribe,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM task_links WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}

const findLinksByURL = `-- name: FindLinksByURL :many
SELECT l.id, l.task_id, l.relevance, l.url, l.title, l.subscribe, l.created_at
FROM task_links l
JOIN tasks t ON l.task_id = t.id
WHERE l.url = $1 AND t.archived = FALSE AND t.org_id = $2
ORDER BY l.created_at DESC
`

type FindLinksByURLParams struct {
	Url   string `json:"url"`
	OrgID int64  `json:"org_id"`
}

func (q *Queries) FindLinksByURL(ctx context.Context, arg FindLinksByURLParams) ([]TaskLink, error) {
	rows, err := q.db.QueryContext(ctx, findLinksByURL, arg.Url, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskLink{}
	for rows.Next() {
		var i TaskLink
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Relevance,
			&i.Url,
			&i.Title,
			&i.Subscribe,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubscribedLinksByURLForUser = `-- name: FindSubscribedLinksByURLForUser :many
SELECT l.id, l.task_id, l.relevance, l.url, l.title, l.subscribe, l.created_at, t.org_id
FROM task_links l
JOIN tasks t ON l.task_id = t.id
JOIN org_members om ON t.org_id = om.org_id
WHERE l.url = $1 AND l.subscribe = TRUE AND t.archived = FALSE AND om.user_id = $2
ORDER BY t.org_id, l.created_at DESC
`

type FindSubscribedLinksByURLForUserParams struct {
	Url    string `json:"url"`
	UserID string `json:"user_id"`
}

type FindSubscribedLinksByURLForUserRow struct {
	ID        int64     `json:"id"`
	TaskID    int64     `json:"task_id"`
	Relevance string    `json:"relevance"`
	Url       string    `json:"url"`
	Title     string    `json:"title"`
	Subscribe bool      `json:"subscribe"`
	CreatedAt time.Time `json:"created_at"`
	OrgID     int64     `json:"org_id"`
}

func (q *Queries) FindSubscribedLinksByURLForUser(ctx context.Context, arg FindSubscribedLinksByURLForUserParams) ([]FindSubscribedLinksByURLForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, findSubscribedLinksByURLForUser, arg.Url, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSubscribedLinksByURLForUserRow{}
	for rows.Next() {
		var i FindSubscribedLinksByURLForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Relevance,
			&i.Url,
			&i.Title,
			&i.Subscribe,
			&i.CreatedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksByTask = `-- name: ListLinksByTask :many
SELECT l.id, l.task_id, l.relevance, l.url, l.title, l.subscribe, l.created_at
FROM task_links l
JOIN tasks t ON l.task_id = t.id
WHERE l.task_id = $1 AND t.org_id = $2
ORDER BY l.created_at ASC
`

type ListLinksByTaskParams struct {
	TaskID int64 `json:"task_id"`
	OrgID  int64 `json:"org_id"`
}

func (q *Queries) ListLinksByTask(ctx context.Context, arg ListLinksByTaskParams) ([]TaskLink, error) {
	rows, err := q.db.QueryContext(ctx, listLinksByTask, arg.TaskID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskLink{}
	for rows.Next() {
		var i TaskLink
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Relevance,
			&i.Url,
			&i.Title,
			&i.Subscribe,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
