// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createLink = `-- name: CreateLink :execlastid
INSERT INTO task_links (task_id, relevance, url, title, notify, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateLinkParams struct {
	TaskID    int64          `json:"task_id"`
	Relevance string         `json:"relevance"`
	Url       string         `json:"url"`
	Title     sql.NullString `json:"title"`
	Notify    sql.NullBool   `json:"notify"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createLink,
		arg.TaskID,
		arg.Relevance,
		arg.Url,
		arg.Title,
		arg.Notify,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM task_links WHERE id = ?
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}

const findLinksByURL = `-- name: FindLinksByURL :many
SELECT l.id, l.task_id, l.relevance, l.url, l.title, l.notify, l.created_at
FROM task_links l
JOIN tasks t ON l.task_id = t.id
WHERE l.url = ? AND t.status != 'archived' AND t.owner = ?
ORDER BY l.created_at DESC
`

type FindLinksByURLParams struct {
	Url   string `json:"url"`
	Owner string `json:"owner"`
}

func (q *Queries) FindLinksByURL(ctx context.Context, arg FindLinksByURLParams) ([]TaskLink, error) {
	rows, err := q.db.QueryContext(ctx, findLinksByURL, arg.Url, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskLink{}
	for rows.Next() {
		var i TaskLink
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Relevance,
			&i.Url,
			&i.Title,
			&i.Notify,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksByTask = `-- name: ListLinksByTask :many
SELECT l.id, l.task_id, l.relevance, l.url, l.title, l.notify, l.created_at
FROM task_links l
JOIN tasks t ON l.task_id = t.id
WHERE l.task_id = ? AND t.owner = ?
ORDER BY l.created_at ASC
`

type ListLinksByTaskParams struct {
	TaskID int64  `json:"task_id"`
	Owner  string `json:"owner"`
}

func (q *Queries) ListLinksByTask(ctx context.Context, arg ListLinksByTaskParams) ([]TaskLink, error) {
	rows, err := q.db.QueryContext(ctx, listLinksByTask, arg.TaskID, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskLink{}
	for rows.Next() {
		var i TaskLink
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Relevance,
			&i.Url,
			&i.Title,
			&i.Notify,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
