// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log.sql

package sqlc

import (
	"context"
	"time"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (task_id, type, content, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateLogParams struct {
	TaskID    int64     `json:"task_id"`
	Type      string    `json:"type"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLog,
		arg.TaskID,
		arg.Type,
		arg.Content,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLogsByTask = `-- name: ListLogsByTask :many
SELECT l.id, l.task_id, l.type, l.content, l.created_at
FROM logs l
JOIN tasks t ON l.task_id = t.id
WHERE l.task_id = $1 AND t.owner = $2
ORDER BY l.created_at ASC
`

type ListLogsByTaskParams struct {
	TaskID int64  `json:"task_id"`
	Owner  string `json:"owner"`
}

func (q *Queries) ListLogsByTask(ctx context.Context, arg ListLogsByTaskParams) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, listLogsByTask, arg.TaskID, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Log{}
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
