// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          int64     `json:"id"`
	Description string    `json:"description"`
	Data        string    `json:"data"`
	Url         string    `json:"url"`
	CreatedAt   time.Time `json:"created_at"`
	OrgID       int64     `json:"org_id"`
}

type EventTask struct {
	EventID int64 `json:"event_id"`
	TaskID  int64 `json:"task_id"`
}

type Key struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	OrgID     int64        `json:"org_id"`
}

type Log struct {
	ID        int64     `json:"id"`
	TaskID    int64     `json:"task_id"`
	Type      string    `json:"type"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Org struct {
	ID                     int64     `json:"id"`
	Name                   string    `json:"name"`
	Owner                  string    `json:"owner"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
	Archived               bool      `json:"archived"`
	AtlassianWebhookSecret string    `json:"atlassian_webhook_secret"`
}

type OrgMember struct {
	OrgID     int64     `json:"org_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type Task struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Parent       int64     `json:"parent"`
	Runner       string    `json:"runner"`
	Workspace    string    `json:"workspace"`
	Instructions string    `json:"instructions"`
	Status       int32     `json:"status"`
	Command      int32     `json:"command"`
	Version      int64     `json:"version"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Archived     bool      `json:"archived"`
	OrgID        int64     `json:"org_id"`
}

type TaskLink struct {
	ID        int64     `json:"id"`
	TaskID    int64     `json:"task_id"`
	Relevance string    `json:"relevance"`
	Url       string    `json:"url"`
	Title     string    `json:"title"`
	Subscribe bool      `json:"subscribe"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                 string         `json:"id"`
	Email              string         `json:"email"`
	Name               string         `json:"name"`
	GithubUserID       sql.NullInt64  `json:"github_user_id"`
	GithubUsername     sql.NullString `json:"github_username"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	DefaultOrgID       sql.NullInt64  `json:"default_org_id"`
	AtlassianAccountID sql.NullString `json:"atlassian_account_id"`
	AtlassianUsername  string         `json:"atlassian_username"`
}

type Workspace struct {
	ID          int64     `json:"id"`
	RunnerID    string    `json:"runner_id"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updated_at"`
	OrgID       int64     `json:"org_id"`
	Description string    `json:"description"`
}
