// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          int64     `json:"id"`
	Description string    `json:"description"`
	Data        string    `json:"data"`
	Url         string    `json:"url"`
	Owner       string    `json:"owner"`
	CreatedAt   time.Time `json:"created_at"`
}

type EventTask struct {
	EventID int64 `json:"event_id"`
	TaskID  int64 `json:"task_id"`
}

type Key struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	TokenHash string       `json:"token_hash"`
	Owner     string       `json:"owner"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type Log struct {
	ID        int64     `json:"id"`
	TaskID    int64     `json:"task_id"`
	Type      string    `json:"type"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Task struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Parent       int64     `json:"parent"`
	Runner       string    `json:"runner"`
	Workspace    string    `json:"workspace"`
	Instructions string    `json:"instructions"`
	Status       string    `json:"status"`
	Command      string    `json:"command"`
	Version      int64     `json:"version"`
	Owner        string    `json:"owner"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Archived     bool      `json:"archived"`
}

type TaskLink struct {
	ID        int64     `json:"id"`
	TaskID    int64     `json:"task_id"`
	Relevance string    `json:"relevance"`
	Url       string    `json:"url"`
	Title     string    `json:"title"`
	Notify    bool      `json:"notify"`
	CreatedAt time.Time `json:"created_at"`
}

type Workspace struct {
	ID        int64     `json:"id"`
	RunnerID  string    `json:"runner_id"`
	Name      string    `json:"name"`
	Owner     string    `json:"owner"`
	UpdatedAt time.Time `json:"updated_at"`
}
