// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const addOrgMember = `-- name: AddOrgMember :exec
INSERT INTO org_members (org_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4)
`

type AddOrgMemberParams struct {
	OrgID     int64     `json:"org_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error {
	_, err := q.db.ExecContext(ctx, addOrgMember,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const archiveOrg = `-- name: ArchiveOrg :exec
UPDATE orgs SET archived = TRUE, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) ArchiveOrg(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveOrg, id)
	return err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name, owner, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateOrgParams struct {
	Name      string    `json:"name"`
	Owner     string    `json:"owner"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrg,
		arg.Name,
		arg.Owner,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const destroyOrg = `-- name: DestroyOrg :exec
DELETE FROM orgs WHERE id = $1
`

func (q *Queries) DestroyOrg(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, destroyOrg, id)
	return err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, owner, created_at, updated_at, archived
FROM orgs
WHERE id = $1
`

type GetOrgRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Owner     string    `json:"owner"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Archived  bool      `json:"archived"`
}

func (q *Queries) GetOrg(ctx context.Context, id int64) (GetOrgRow, error) {
	row := q.db.QueryRowContext(ctx, getOrg, id)
	var i GetOrgRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const getOrgAtlassianWebhookSecret = `-- name: GetOrgAtlassianWebhookSecret :one
SELECT atlassian_webhook_secret FROM orgs WHERE id = $1
`

func (q *Queries) GetOrgAtlassianWebhookSecret(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getOrgAtlassianWebhookSecret, id)
	var atlassian_webhook_secret string
	err := row.Scan(&atlassian_webhook_secret)
	return atlassian_webhook_secret, err
}

const getOrgRoutingRules = `-- name: GetOrgRoutingRules :one
SELECT routing_rules FROM orgs WHERE id = $1
`

func (q *Queries) GetOrgRoutingRules(ctx context.Context, id int64) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getOrgRoutingRules, id)
	var routing_rules json.RawMessage
	err := row.Scan(&routing_rules)
	return routing_rules, err
}

const getRoutingRulesByOrgs = `-- name: GetRoutingRulesByOrgs :many
SELECT id, routing_rules FROM orgs WHERE id = ANY($1::BIGINT[])
`

type GetRoutingRulesByOrgsRow struct {
	ID           int64           `json:"id"`
	RoutingRules json.RawMessage `json:"routing_rules"`
}

func (q *Queries) GetRoutingRulesByOrgs(ctx context.Context, dollar_1 []int64) ([]GetRoutingRulesByOrgsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoutingRulesByOrgs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoutingRulesByOrgsRow{}
	for rows.Next() {
		var i GetRoutingRulesByOrgsRow
		if err := rows.Scan(&i.ID, &i.RoutingRules); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isOrgMember = `-- name: IsOrgMember :one
SELECT EXISTS(
    SELECT 1 FROM org_members om
    JOIN orgs o ON o.id = om.org_id
    WHERE om.org_id = $1 AND om.user_id = $2 AND o.archived = FALSE
) AS is_member
`

type IsOrgMemberParams struct {
	OrgID  int64  `json:"org_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) IsOrgMember(ctx context.Context, arg IsOrgMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isOrgMember, arg.OrgID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT om.org_id, om.user_id, om.role, om.created_at
FROM org_members om
WHERE om.org_id = $1
ORDER BY om.created_at
`

func (q *Queries) ListOrgMembers(ctx context.Context, orgID int64) ([]OrgMember, error) {
	rows, err := q.db.QueryContext(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgMember{}
	for rows.Next() {
		var i OrgMember
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembersWithUsers = `-- name: ListOrgMembersWithUsers :many
SELECT om.org_id, om.user_id, om.role, om.created_at, u.email, u.name
FROM org_members om
JOIN users u ON om.user_id = u.id
WHERE om.org_id = $1
ORDER BY om.created_at
`

type ListOrgMembersWithUsersRow struct {
	OrgID     int64     `json:"org_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
}

func (q *Queries) ListOrgMembersWithUsers(ctx context.Context, orgID int64) ([]ListOrgMembersWithUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgMembersWithUsers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgMembersWithUsersRow{}
	for rows.Next() {
		var i ListOrgMembersWithUsersRow
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsByMember = `-- name: ListOrgsByMember :many
SELECT o.id, o.name, o.owner, o.created_at, o.updated_at, o.archived
FROM orgs o
JOIN org_members om ON o.id = om.org_id
WHERE om.user_id = $1 AND o.archived = FALSE
ORDER BY o.name
`

type ListOrgsByMemberRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Owner     string    `json:"owner"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Archived  bool      `json:"archived"`
}

func (q *Queries) ListOrgsByMember(ctx context.Context, userID string) ([]ListOrgsByMemberRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgsByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgsByMemberRow{}
	for rows.Next() {
		var i ListOrgsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrgMember = `-- name: RemoveOrgMember :exec
DELETE FROM org_members
WHERE org_id = $1 AND user_id = $2
`

type RemoveOrgMemberParams struct {
	OrgID  int64  `json:"org_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeOrgMember, arg.OrgID, arg.UserID)
	return err
}

const setOrgAtlassianWebhookSecret = `-- name: SetOrgAtlassianWebhookSecret :exec
UPDATE orgs SET atlassian_webhook_secret = $2 WHERE id = $1
`

type SetOrgAtlassianWebhookSecretParams struct {
	ID                     int64  `json:"id"`
	AtlassianWebhookSecret string `json:"atlassian_webhook_secret"`
}

func (q *Queries) SetOrgAtlassianWebhookSecret(ctx context.Context, arg SetOrgAtlassianWebhookSecretParams) error {
	_, err := q.db.ExecContext(ctx, setOrgAtlassianWebhookSecret, arg.ID, arg.AtlassianWebhookSecret)
	return err
}

const setOrgRoutingRules = `-- name: SetOrgRoutingRules :exec
UPDATE orgs SET
    routing_rules = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type SetOrgRoutingRulesParams struct {
	ID           int64           `json:"id"`
	RoutingRules json.RawMessage `json:"routing_rules"`
}

func (q *Queries) SetOrgRoutingRules(ctx context.Context, arg SetOrgRoutingRulesParams) error {
	_, err := q.db.ExecContext(ctx, setOrgRoutingRules, arg.ID, arg.RoutingRules)
	return err
}

const updateOrg = `-- name: UpdateOrg :exec
UPDATE orgs SET
    name = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateOrgParams struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) error {
	_, err := q.db.ExecContext(ctx, updateOrg, arg.ID, arg.Name, arg.UpdatedAt)
	return err
}
