// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_integration.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const deletePendingIntegration = `-- name: DeletePendingIntegration :exec
DELETE FROM pending_integrations
WHERE type = $1 AND external_id = $2
`

type DeletePendingIntegrationParams struct {
	Type       string `json:"type"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) DeletePendingIntegration(ctx context.Context, arg DeletePendingIntegrationParams) error {
	_, err := q.db.ExecContext(ctx, deletePendingIntegration, arg.Type, arg.ExternalID)
	return err
}

const getPendingIntegration = `-- name: GetPendingIntegration :one
SELECT type, external_id, options, created_at
FROM pending_integrations
WHERE type = $1 AND external_id = $2
`

type GetPendingIntegrationParams struct {
	Type       string `json:"type"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetPendingIntegration(ctx context.Context, arg GetPendingIntegrationParams) (PendingIntegration, error) {
	row := q.db.QueryRowContext(ctx, getPendingIntegration, arg.Type, arg.ExternalID)
	var i PendingIntegration
	err := row.Scan(
		&i.Type,
		&i.ExternalID,
		&i.Options,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPendingIntegration = `-- name: UpsertPendingIntegration :exec
INSERT INTO pending_integrations (type, external_id, options, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (type, external_id) DO UPDATE SET
    options = EXCLUDED.options
`

type UpsertPendingIntegrationParams struct {
	Type       string          `json:"type"`
	ExternalID string          `json:"external_id"`
	Options    json.RawMessage `json:"options"`
	CreatedAt  time.Time       `json:"created_at"`
}

func (q *Queries) UpsertPendingIntegration(ctx context.Context, arg UpsertPendingIntegrationParams) error {
	_, err := q.db.ExecContext(ctx, upsertPendingIntegration,
		arg.Type,
		arg.ExternalID,
		arg.Options,
		arg.CreatedAt,
	)
	return err
}
