// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const advanceSchedule = `-- name: AdvanceSchedule :exec
UPDATE schedules
SET next_run_at = $1, last_run_at = $2, last_task_id = $3,
    updated_at = (NOW() AT TIME ZONE 'UTC')
WHERE id = $4 AND org_id = $5
`

type AdvanceScheduleParams struct {
	NextRunAt  sql.NullTime  `json:"next_run_at"`
	LastRunAt  sql.NullTime  `json:"last_run_at"`
	LastTaskID sql.NullInt64 `json:"last_task_id"`
	ID         int64         `json:"id"`
	OrgID      int64         `json:"org_id"`
}

func (q *Queries) AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error {
	_, err := q.db.ExecContext(ctx, advanceSchedule,
		arg.NextRunAt,
		arg.LastRunAt,
		arg.LastTaskID,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const claimDueSchedules = `-- name: ClaimDueSchedules :many
SELECT id, org_id, created_by, name, workspace, runner, namespace, instructions,
       auto_archive, cron_expr, timezone, enabled,
       next_run_at, last_run_at, last_task_id, created_at, updated_at
FROM schedules
WHERE enabled = TRUE
  AND next_run_at IS NOT NULL
  AND next_run_at <= (NOW() AT TIME ZONE 'UTC')
ORDER BY next_run_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Lock and return up to $1 due, enabled schedules, skipping any row another server
// instance already holds. FOR UPDATE SKIP LOCKED makes the claim atomic across instances:
// two schedulers ticking at the same instant partition the due set instead of both firing
// the same schedule. The locks are held until the caller's transaction commits, by which
// point next_run_at has been advanced past now, so the row is no longer due.
func (q *Queries) ClaimDueSchedules(ctx context.Context, limit int32) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, claimDueSchedules, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CreatedBy,
			&i.Name,
			&i.Workspace,
			&i.Runner,
			&i.Namespace,
			&i.Instructions,
			&i.AutoArchive,
			&i.CronExpr,
			&i.Timezone,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (org_id, created_by, name, workspace, runner, namespace, instructions, auto_archive, cron_expr, timezone, enabled, next_run_at, last_run_at, last_task_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id
`

type CreateScheduleParams struct {
	OrgID        int64           `json:"org_id"`
	CreatedBy    string          `json:"created_by"`
	Name         string          `json:"name"`
	Workspace    string          `json:"workspace"`
	Runner       string          `json:"runner"`
	Namespace    string          `json:"namespace"`
	Instructions json.RawMessage `json:"instructions"`
	AutoArchive  int64           `json:"auto_archive"`
	CronExpr     string          `json:"cron_expr"`
	Timezone     string          `json:"timezone"`
	Enabled      bool            `json:"enabled"`
	NextRunAt    sql.NullTime    `json:"next_run_at"`
	LastRunAt    sql.NullTime    `json:"last_run_at"`
	LastTaskID   sql.NullInt64   `json:"last_task_id"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.OrgID,
		arg.CreatedBy,
		arg.Name,
		arg.Workspace,
		arg.Runner,
		arg.Namespace,
		arg.Instructions,
		arg.AutoArchive,
		arg.CronExpr,
		arg.Timezone,
		arg.Enabled,
		arg.NextRunAt,
		arg.LastRunAt,
		arg.LastTaskID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = $1 AND org_id = $2
`

type DeleteScheduleParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, arg.ID, arg.OrgID)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, org_id, created_by, name, workspace, runner, namespace, instructions, auto_archive, cron_expr, timezone, enabled, next_run_at, last_run_at, last_task_id, created_at, updated_at
FROM schedules
WHERE id = $1 AND org_id = $2
`

type GetScheduleParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) GetSchedule(ctx context.Context, arg GetScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, arg.ID, arg.OrgID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Name,
		&i.Workspace,
		&i.Runner,
		&i.Namespace,
		&i.Instructions,
		&i.AutoArchive,
		&i.CronExpr,
		&i.Timezone,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleForUpdate = `-- name: GetScheduleForUpdate :one
SELECT id, org_id, created_by, name, workspace, runner, namespace, instructions, auto_archive, cron_expr, timezone, enabled, next_run_at, last_run_at, last_task_id, created_at, updated_at
FROM schedules
WHERE id = $1 AND org_id = $2
FOR UPDATE
`

type GetScheduleForUpdateParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) GetScheduleForUpdate(ctx context.Context, arg GetScheduleForUpdateParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleForUpdate, arg.ID, arg.OrgID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Name,
		&i.Workspace,
		&i.Runner,
		&i.Namespace,
		&i.Instructions,
		&i.AutoArchive,
		&i.CronExpr,
		&i.Timezone,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastTaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, org_id, created_by, name, workspace, runner, namespace, instructions, auto_archive, cron_expr, timezone, enabled, next_run_at, last_run_at, last_task_id, created_at, updated_at
FROM schedules
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSchedules(ctx context.Context, orgID int64) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CreatedBy,
			&i.Name,
			&i.Workspace,
			&i.Runner,
			&i.Namespace,
			&i.Instructions,
			&i.AutoArchive,
			&i.CronExpr,
			&i.Timezone,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastTaskID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE schedules
SET name = $1, workspace = $2, runner = $3, namespace = $4, instructions = $5, auto_archive = $6, cron_expr = $7, timezone = $8, enabled = $9, next_run_at = $10, last_run_at = $11, last_task_id = $12, updated_at = $13
WHERE id = $14 AND org_id = $15
`

type UpdateScheduleParams struct {
	Name         string          `json:"name"`
	Workspace    string          `json:"workspace"`
	Runner       string          `json:"runner"`
	Namespace    string          `json:"namespace"`
	Instructions json.RawMessage `json:"instructions"`
	AutoArchive  int64           `json:"auto_archive"`
	CronExpr     string          `json:"cron_expr"`
	Timezone     string          `json:"timezone"`
	Enabled      bool            `json:"enabled"`
	NextRunAt    sql.NullTime    `json:"next_run_at"`
	LastRunAt    sql.NullTime    `json:"last_run_at"`
	LastTaskID   sql.NullInt64   `json:"last_task_id"`
	UpdatedAt    time.Time       `json:"updated_at"`
	ID           int64           `json:"id"`
	OrgID        int64           `json:"org_id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateSchedule,
		arg.Name,
		arg.Workspace,
		arg.Runner,
		arg.Namespace,
		arg.Instructions,
		arg.AutoArchive,
		arg.CronExpr,
		arg.Timezone,
		arg.Enabled,
		arg.NextRunAt,
		arg.LastRunAt,
		arg.LastTaskID,
		arg.UpdatedAt,
		arg.ID,
		arg.OrgID,
	)
	return err
}
