// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package sqlc

import (
	"context"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (name, runner, workspace, status, command, version, org_id, archived, created_at, updated_at, auto_archive, shell_session)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type CreateTaskParams struct {
	Name         string    `json:"name"`
	Runner       string    `json:"runner"`
	Workspace    string    `json:"workspace"`
	Status       int32     `json:"status"`
	Command      int32     `json:"command"`
	Version      int64     `json:"version"`
	OrgID        int64     `json:"org_id"`
	Archived     bool      `json:"archived"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	AutoArchive  int64     `json:"auto_archive"`
	ShellSession string    `json:"shell_session"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Name,
		arg.Runner,
		arg.Workspace,
		arg.Status,
		arg.Command,
		arg.Version,
		arg.OrgID,
		arg.Archived,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.AutoArchive,
		arg.ShellSession,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1 AND org_id = $2
`

type DeleteTaskParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteTask, arg.ID, arg.OrgID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, name, runner, workspace, status, command, version, org_id, archived, created_at, updated_at, auto_archive, shell_session
FROM tasks
WHERE id = $1 AND org_id = $2
`

type GetTaskParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.ID, arg.OrgID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Runner,
		&i.Workspace,
		&i.Status,
		&i.Command,
		&i.Version,
		&i.OrgID,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoArchive,
		&i.ShellSession,
	)
	return i, err
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT id, name, runner, workspace, status, command, version, org_id, archived, created_at, updated_at, auto_archive, shell_session
FROM tasks
WHERE id = $1 AND org_id = $2
FOR UPDATE
`

type GetTaskForUpdateParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) GetTaskForUpdate(ctx context.Context, arg GetTaskForUpdateParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskForUpdate, arg.ID, arg.OrgID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Runner,
		&i.Workspace,
		&i.Status,
		&i.Command,
		&i.Version,
		&i.OrgID,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoArchive,
		&i.ShellSession,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, runner, workspace, status, command, version, org_id, archived, created_at, updated_at, auto_archive, shell_session
FROM tasks
WHERE archived = FALSE AND org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context, orgID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Runner,
			&i.Workspace,
			&i.Status,
			&i.Command,
			&i.Version,
			&i.OrgID,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoArchive,
			&i.ShellSession,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksDueForArchive = `-- name: ListTasksDueForArchive :many
SELECT id, version, org_id
FROM tasks
WHERE archived = FALSE
  AND auto_archive <> 0
  AND command = 0
  AND status IN (5, 6, 7)
  AND updated_at + (INTERVAL '1 microsecond' * auto_archive) < (NOW() AT TIME ZONE 'UTC')
ORDER BY updated_at
LIMIT $1
`

type ListTasksDueForArchiveRow struct {
	ID      int64 `json:"id"`
	Version int64 `json:"version"`
	OrgID   int64 `json:"org_id"`
}

func (q *Queries) ListTasksDueForArchive(ctx context.Context, limit int32) ([]ListTasksDueForArchiveRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksDueForArchive, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksDueForArchiveRow{}
	for rows.Next() {
		var i ListTasksDueForArchiveRow
		if err := rows.Scan(&i.ID, &i.Version, &i.OrgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksForRunner = `-- name: ListTasksForRunner :many
SELECT id, name, runner, workspace, status, command, version, org_id, archived, created_at, updated_at, auto_archive, shell_session
FROM tasks
WHERE runner = $1 AND org_id = $2 AND command != 0 AND archived = FALSE
ORDER BY created_at DESC
`

type ListTasksForRunnerParams struct {
	Runner string `json:"runner"`
	OrgID  int64  `json:"org_id"`
}

func (q *Queries) ListTasksForRunner(ctx context.Context, arg ListTasksForRunnerParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksForRunner, arg.Runner, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Runner,
			&i.Workspace,
			&i.Status,
			&i.Command,
			&i.Version,
			&i.OrgID,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoArchive,
			&i.ShellSession,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET name = $1, runner = $2, workspace = $3, status = $4, command = $5, version = $6, updated_at = $7, archived = $8, auto_archive = $9, shell_session = $10
WHERE id = $11 AND org_id = $12
`

type UpdateTaskParams struct {
	Name         string    `json:"name"`
	Runner       string    `json:"runner"`
	Workspace    string    `json:"workspace"`
	Status       int32     `json:"status"`
	Command      int32     `json:"command"`
	Version      int64     `json:"version"`
	UpdatedAt    time.Time `json:"updated_at"`
	Archived     bool      `json:"archived"`
	AutoArchive  int64     `json:"auto_archive"`
	ShellSession string    `json:"shell_session"`
	ID           int64     `json:"id"`
	OrgID        int64     `json:"org_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Name,
		arg.Runner,
		arg.Workspace,
		arg.Status,
		arg.Command,
		arg.Version,
		arg.UpdatedAt,
		arg.Archived,
		arg.AutoArchive,
		arg.ShellSession,
		arg.ID,
		arg.OrgID,
	)
	return err
}
