// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_event.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const createTaskEvent = `-- name: CreateTaskEvent :one
INSERT INTO task_events (task_id, type, content, meta, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateTaskEventParams struct {
	TaskID    int64           `json:"task_id"`
	Type      string          `json:"type"`
	Content   string          `json:"content"`
	Meta      json.RawMessage `json:"meta"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) CreateTaskEvent(ctx context.Context, arg CreateTaskEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTaskEvent,
		arg.TaskID,
		arg.Type,
		arg.Content,
		arg.Meta,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTaskEventsByTask = `-- name: DeleteTaskEventsByTask :exec
DELETE FROM task_events WHERE task_id = $1
`

func (q *Queries) DeleteTaskEventsByTask(ctx context.Context, taskID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskEventsByTask, taskID)
	return err
}

const pollTaskEvents = `-- name: PollTaskEvents :many
SELECT id, task_id, type, content, meta, created_at
FROM task_events
WHERE task_id = $1 AND id > $2
ORDER BY id ASC
LIMIT $3
`

type PollTaskEventsParams struct {
	TaskID int64 `json:"task_id"`
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) PollTaskEvents(ctx context.Context, arg PollTaskEventsParams) ([]TaskEvent, error) {
	rows, err := q.db.QueryContext(ctx, pollTaskEvents, arg.TaskID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskEvent{}
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Type,
			&i.Content,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
