// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :execlastid
INSERT INTO tasks (name, parent, runner, workspace, instructions, status, command, version, owner, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	Name         string       `json:"name"`
	Parent       int64        `json:"parent"`
	Runner       string       `json:"runner"`
	Workspace    string       `json:"workspace"`
	Instructions string       `json:"instructions"`
	Status       string       `json:"status"`
	Command      string       `json:"command"`
	Version      int64        `json:"version"`
	Owner        string       `json:"owner"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTask,
		arg.Name,
		arg.Parent,
		arg.Runner,
		arg.Workspace,
		arg.Instructions,
		arg.Status,
		arg.Command,
		arg.Version,
		arg.Owner,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ? AND owner = ?
`

type DeleteTaskParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteTask, arg.ID, arg.Owner)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, name, parent, runner, workspace, instructions, status, command, version, owner, created_at, updated_at
FROM tasks
WHERE id = ? AND owner = ?
`

type GetTaskParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.ID, arg.Owner)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Parent,
		&i.Runner,
		&i.Workspace,
		&i.Instructions,
		&i.Status,
		&i.Command,
		&i.Version,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasTask = `-- name: HasTask :one
SELECT EXISTS(SELECT 1 FROM tasks WHERE id = ? AND owner = ?)
`

type HasTaskParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) HasTask(ctx context.Context, arg HasTaskParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasTask, arg.ID, arg.Owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listTaskChildren = `-- name: ListTaskChildren :many
SELECT id, name, parent, runner, workspace, instructions, status, command, version, owner, created_at, updated_at
FROM tasks
WHERE parent = ? AND owner = ?
ORDER BY created_at DESC
`

type ListTaskChildrenParams struct {
	Parent int64  `json:"parent"`
	Owner  string `json:"owner"`
}

func (q *Queries) ListTaskChildren(ctx context.Context, arg ListTaskChildrenParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTaskChildren, arg.Parent, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Parent,
			&i.Runner,
			&i.Workspace,
			&i.Instructions,
			&i.Status,
			&i.Command,
			&i.Version,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, parent, runner, workspace, instructions, status, command, version, owner, created_at, updated_at
FROM tasks
WHERE status != 'archived' AND owner = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context, owner string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Parent,
			&i.Runner,
			&i.Workspace,
			&i.Instructions,
			&i.Status,
			&i.Command,
			&i.Version,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByEvent = `-- name: ListTasksByEvent :many
SELECT t.id, t.name, t.parent, t.runner, t.workspace, t.instructions, t.status, t.command, t.version, t.owner, t.created_at, t.updated_at
FROM tasks t
JOIN event_tasks et ON t.id = et.task_id
WHERE et.event_id = ?
ORDER BY t.created_at DESC
`

func (q *Queries) ListTasksByEvent(ctx context.Context, eventID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Parent,
			&i.Runner,
			&i.Workspace,
			&i.Instructions,
			&i.Status,
			&i.Command,
			&i.Version,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksForRunner = `-- name: ListTasksForRunner :many
SELECT id, name, parent, runner, workspace, instructions, status, command, version, owner, created_at, updated_at
FROM tasks
WHERE runner = ? AND owner = ? AND command != '' AND status != 'archived'
ORDER BY created_at DESC
`

type ListTasksForRunnerParams struct {
	Runner string `json:"runner"`
	Owner  string `json:"owner"`
}

func (q *Queries) ListTasksForRunner(ctx context.Context, arg ListTasksForRunnerParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksForRunner, arg.Runner, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Parent,
			&i.Runner,
			&i.Workspace,
			&i.Instructions,
			&i.Status,
			&i.Command,
			&i.Version,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET name = ?, parent = ?, runner = ?, workspace = ?, instructions = ?, status = ?, command = ?, version = ?, updated_at = ?
WHERE id = ? AND owner = ?
`

type UpdateTaskParams struct {
	Name         string       `json:"name"`
	Parent       int64        `json:"parent"`
	Runner       string       `json:"runner"`
	Workspace    string       `json:"workspace"`
	Instructions string       `json:"instructions"`
	Status       string       `json:"status"`
	Command      string       `json:"command"`
	Version      int64        `json:"version"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	ID           int64        `json:"id"`
	Owner        string       `json:"owner"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Name,
		arg.Parent,
		arg.Runner,
		arg.Workspace,
		arg.Instructions,
		arg.Status,
		arg.Command,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
		arg.Owner,
	)
	return err
}
