// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package sqlc

import (
	"context"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (name, parent, runner, workspace, instructions, status, command, version, owner, created_at, updated_at, archived)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type CreateTaskParams struct {
	Name         string    `json:"name"`
	Parent       int64     `json:"parent"`
	Runner       string    `json:"runner"`
	Workspace    string    `json:"workspace"`
	Instructions string    `json:"instructions"`
	Status       int32     `json:"status"`
	Command      int32     `json:"command"`
	Version      int64     `json:"version"`
	Owner        string    `json:"owner"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Archived     bool      `json:"archived"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Name,
		arg.Parent,
		arg.Runner,
		arg.Workspace,
		arg.Instructions,
		arg.Status,
		arg.Command,
		arg.Version,
		arg.Owner,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Archived,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1 AND owner = $2
`

type DeleteTaskParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteTask, arg.ID, arg.Owner)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, name, parent, runner, workspace, instructions, status, command, version, owner, created_at, updated_at, archived
FROM tasks
WHERE id = $1 AND owner = $2
`

type GetTaskParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.ID, arg.Owner)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Parent,
		&i.Runner,
		&i.Workspace,
		&i.Instructions,
		&i.Status,
		&i.Command,
		&i.Version,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT id, name, parent, runner, workspace, instructions, status, command, version, owner, created_at, updated_at, archived
FROM tasks
WHERE id = $1 AND owner = $2
FOR UPDATE
`

type GetTaskForUpdateParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) GetTaskForUpdate(ctx context.Context, arg GetTaskForUpdateParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskForUpdate, arg.ID, arg.Owner)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Parent,
		&i.Runner,
		&i.Workspace,
		&i.Instructions,
		&i.Status,
		&i.Command,
		&i.Version,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const hasTask = `-- name: HasTask :one
SELECT EXISTS(SELECT 1 FROM tasks WHERE id = $1 AND owner = $2)
`

type HasTaskParams struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
}

func (q *Queries) HasTask(ctx context.Context, arg HasTaskParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasTask, arg.ID, arg.Owner)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listTaskChildren = `-- name: ListTaskChildren :many
SELECT id, name, parent, runner, workspace, instructions, status, command, version, owner, created_at, updated_at, archived
FROM tasks
WHERE parent = $1 AND owner = $2
ORDER BY created_at DESC
`

type ListTaskChildrenParams struct {
	Parent int64  `json:"parent"`
	Owner  string `json:"owner"`
}

func (q *Queries) ListTaskChildren(ctx context.Context, arg ListTaskChildrenParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTaskChildren, arg.Parent, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Parent,
			&i.Runner,
			&i.Workspace,
			&i.Instructions,
			&i.Status,
			&i.Command,
			&i.Version,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, parent, runner, workspace, instructions, status, command, version, owner, created_at, updated_at, archived
FROM tasks
WHERE archived = FALSE AND owner = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context, owner string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Parent,
			&i.Runner,
			&i.Workspace,
			&i.Instructions,
			&i.Status,
			&i.Command,
			&i.Version,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByEvent = `-- name: ListTasksByEvent :many
SELECT t.id, t.name, t.parent, t.runner, t.workspace, t.instructions, t.status, t.command, t.version, t.owner, t.created_at, t.updated_at, t.archived
FROM tasks t
JOIN event_tasks et ON t.id = et.task_id
WHERE et.event_id = $1
ORDER BY t.created_at DESC
`

func (q *Queries) ListTasksByEvent(ctx context.Context, eventID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Parent,
			&i.Runner,
			&i.Workspace,
			&i.Instructions,
			&i.Status,
			&i.Command,
			&i.Version,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksForRunner = `-- name: ListTasksForRunner :many
SELECT id, name, parent, runner, workspace, instructions, status, command, version, owner, created_at, updated_at, archived
FROM tasks
WHERE runner = $1 AND owner = $2 AND command != 0 AND archived = FALSE
ORDER BY created_at DESC
`

type ListTasksForRunnerParams struct {
	Runner string `json:"runner"`
	Owner  string `json:"owner"`
}

func (q *Queries) ListTasksForRunner(ctx context.Context, arg ListTasksForRunnerParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksForRunner, arg.Runner, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Parent,
			&i.Runner,
			&i.Workspace,
			&i.Instructions,
			&i.Status,
			&i.Command,
			&i.Version,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET name = $1, parent = $2, runner = $3, workspace = $4, instructions = $5, status = $6, command = $7, version = $8, updated_at = $9, archived = $10
WHERE id = $11 AND owner = $12
`

type UpdateTaskParams struct {
	Name         string    `json:"name"`
	Parent       int64     `json:"parent"`
	Runner       string    `json:"runner"`
	Workspace    string    `json:"workspace"`
	Instructions string    `json:"instructions"`
	Status       int32     `json:"status"`
	Command      int32     `json:"command"`
	Version      int64     `json:"version"`
	UpdatedAt    time.Time `json:"updated_at"`
	Archived     bool      `json:"archived"`
	ID           int64     `json:"id"`
	Owner        string    `json:"owner"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Name,
		arg.Parent,
		arg.Runner,
		arg.Workspace,
		arg.Instructions,
		arg.Status,
		arg.Command,
		arg.Version,
		arg.UpdatedAt,
		arg.Archived,
		arg.ID,
		arg.Owner,
	)
	return err
}
