// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace.sql

package sqlc

import (
	"context"
	"time"
)

const clearWorkspacesByOrgID = `-- name: ClearWorkspacesByOrgID :exec
DELETE FROM workspaces
WHERE org_id = $1
`

func (q *Queries) ClearWorkspacesByOrgID(ctx context.Context, orgID int64) error {
	_, err := q.db.ExecContext(ctx, clearWorkspacesByOrgID, orgID)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (runner_id, name, description, org_id)
VALUES ($1, $2, $3, $4)
`

type CreateWorkspaceParams struct {
	RunnerID    string `json:"runner_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	OrgID       int64  `json:"org_id"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.RunnerID,
		arg.Name,
		arg.Description,
		arg.OrgID,
	)
	return err
}

const deleteWorkspacesByRunner = `-- name: DeleteWorkspacesByRunner :exec
DELETE FROM workspaces
WHERE runner_id = $1 AND org_id = $2
`

type DeleteWorkspacesByRunnerParams struct {
	RunnerID string `json:"runner_id"`
	OrgID    int64  `json:"org_id"`
}

func (q *Queries) DeleteWorkspacesByRunner(ctx context.Context, arg DeleteWorkspacesByRunnerParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspacesByRunner, arg.RunnerID, arg.OrgID)
	return err
}

const listWorkspacesByOrgID = `-- name: ListWorkspacesByOrgID :many
SELECT id, runner_id, name, description, updated_at, org_id
FROM workspaces
WHERE org_id = $1
ORDER BY name ASC
`

type ListWorkspacesByOrgIDRow struct {
	ID          int64     `json:"id"`
	RunnerID    string    `json:"runner_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	UpdatedAt   time.Time `json:"updated_at"`
	OrgID       int64     `json:"org_id"`
}

func (q *Queries) ListWorkspacesByOrgID(ctx context.Context, orgID int64) ([]ListWorkspacesByOrgIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesByOrgIDRow{}
	for rows.Next() {
		var i ListWorkspacesByOrgIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RunnerID,
			&i.Name,
			&i.Description,
			&i.UpdatedAt,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
