// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package dockerx

import (
	"context"
	"github.com/docker/docker/api/types/container"
	"sync"
)

// Ensure, that ContainerWaiterMock does implement ContainerWaiter.
// If this is not the case, regenerate this file with moq.
var _ ContainerWaiter = &ContainerWaiterMock{}

// ContainerWaiterMock is a mock implementation of ContainerWaiter.
//
//	func TestSomethingThatUsesContainerWaiter(t *testing.T) {
//
//		// make and configure a mocked ContainerWaiter
//		mockedContainerWaiter := &ContainerWaiterMock{
//			ContainerWaitFunc: func(ctx context.Context, containerID string, condition container.WaitCondition) (<-chan container.WaitResponse, <-chan error) {
//				panic("mock out the ContainerWait method")
//			},
//		}
//
//		// use mockedContainerWaiter in code that requires ContainerWaiter
//		// and then make assertions.
//
//	}
type ContainerWaiterMock struct {
	// ContainerWaitFunc mocks the ContainerWait method.
	ContainerWaitFunc func(ctx context.Context, containerID string, condition container.WaitCondition) (<-chan container.WaitResponse, <-chan error)

	// calls tracks calls to the methods.
	calls struct {
		// ContainerWait holds details about calls to the ContainerWait method.
		ContainerWait []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerID is the containerID argument value.
			ContainerID string
			// Condition is the condition argument value.
			Condition container.WaitCondition
		}
	}
	lockContainerWait sync.RWMutex
}

// ContainerWait calls ContainerWaitFunc.
func (mock *ContainerWaiterMock) ContainerWait(ctx context.Context, containerID string, condition container.WaitCondition) (<-chan container.WaitResponse, <-chan error) {
	if mock.ContainerWaitFunc == nil {
		panic("ContainerWaiterMock.ContainerWaitFunc: method is nil but ContainerWaiter.ContainerWait was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ContainerID string
		Condition   container.WaitCondition
	}{
		Ctx:         ctx,
		ContainerID: containerID,
		Condition:   condition,
	}
	mock.lockContainerWait.Lock()
	mock.calls.ContainerWait = append(mock.calls.ContainerWait, callInfo)
	mock.lockContainerWait.Unlock()
	return mock.ContainerWaitFunc(ctx, containerID, condition)
}

// ContainerWaitCalls gets all the calls that were made to ContainerWait.
// Check the length with:
//
//	len(mockedContainerWaiter.ContainerWaitCalls())
func (mock *ContainerWaiterMock) ContainerWaitCalls() []struct {
	Ctx         context.Context
	ContainerID string
	Condition   container.WaitCondition
} {
	var calls []struct {
		Ctx         context.Context
		ContainerID string
		Condition   container.WaitCondition
	}
	mock.lockContainerWait.RLock()
	calls = mock.calls.ContainerWait
	mock.lockContainerWait.RUnlock()
	return calls
}
